### ISSUE TITLE
Need to keep track of library dependencies for testing and dev

### ISSUE THREAD

**Issue by jeromekelleher** [ga4gh/server#100]
We are keeping track of library dependencies for deployment using the `install_requires` keyword in `setup.py`. We should try to keep track of our requirements for testing and development also, as we have quite a few now. One option is to use a [requirements.txt](https://pip.readthedocs.org/en/1.1/requirements.html) file. This would allow us to install all our requirements in a virtualenv using `pip install -r requirements.txt`.  Thoughts?

**Comment by Naburimannu** [comment]
On Wed, Jan 28, 2015 at 6:25 AM, Jerome Kelleher <notifications@github.com>
wrote:

> One option is to use a requirements.txt
> <https://pip.readthedocs.org/en/1.1/requirements.html> file. This would
> allow us to install all our requirements in a virtualenv using pip
> install -r requirements.txt.
>

Sounds good to me.

**Comment by dcolligan** [comment]
Here's what I have in my virtualenv, so presumably the app requires some subset of this:
```
$ pip freeze
Flask==0.10.1
Flask-API==0.6.2
Flask-Cors==1.10.2
Jinja2==2.7.3
MarkupSafe==0.23
PyYAML==3.11
Werkzeug==0.9.6
argparse==1.3.0
avro==1.7.7
coverage==3.7.1
ga4gh==0.5.0
google-api-python-client==1.3.1
httplib2==0.9
itsdangerous==0.24
mock==1.0.1
nose==1.3.4
oauth2client==1.4.6
pep8==1.5.7
pyasn1==0.1.7
pyasn1-modules==0.0.5
pysam==0.8.1
requests==2.5.1
rsa==3.1.4
simplejson==3.6.5
six==1.9.0
uritemplate==0.6
wormtable==0.1.3
wsgiref==0.1.2
```

**Comment by dcolligan** [comment]
Maybe a good way to determine what modules are required would be to add a `pip freeze` command to the end of the Travis run and then just stuff whatever it prints out in a new requirements.txt ... I'm not sure  if there's an easier way of going about how to create a requirements.txt

**Comment by dcolligan** [comment]
Travis gives me on master right now: https://travis-ci.org/ga4gh/server/builds/48792706
```
$ pip freeze
Flask==0.10.1
Flask-API==0.6.2
Flask-Cors==1.10.2
Jinja2==2.7.3
MarkupSafe==0.23
Werkzeug==0.9.6
avro==1.7.7
coverage==3.7.1
ga4gh==0.1.0a1
itsdangerous==0.24
mock==1.0.1
nose==1.3.4
numpy==1.9.1
pep8==1.5.7
py==1.4.26
pysam==0.8.1
pytest==2.6.4
requests==2.5.1
six==1.9.0
wheel==0.24.0
wormtable==0.1.3
wsgiref==0.1.2
```
So I guess we can go with that.
