### ISSUE TITLE
Document dependencies on libcurl

### ISSUE THREAD

**Issue by jeromekelleher** [ga4gh/server#1011]
Once #880 is merged, we should have access to htslib's new libcurl based network access code. However, this is only enabled if a libcurl  and crypto installation is found on the target system when pysam is built. We need to figure out exactly what these requirements are on (at least) Ubuntu and document them.

We should also make sure these packages are installed during CI so we're invoking the relevant code paths on Travis. Ideally we'd like to have a way of verifying that pysam is using the libcurl at run time, but this seems tricky. The only way I've found is to open a remote BAM and look at the user agent string on the server logs...

**Comment by dcolligan** [comment]
"The only way I've found is to open a remote BAM and look at the user agent string on the server logs..."

Ugh.  There's got to be a better way.  (And if there's not, we should ask htslib/pysam to put one in!)

**Comment by jeromekelleher** [comment]
Agreed!

**Comment by jmarshall** [comment]
> _The only way I've found is to open a remote BAM and look at the user agent string on the server logs..._

I suggest rereading [#335 comments](https://github.com/ga4gh/server/issues/335#issuecomment-176683477): that one, and the second half of [[on enumerating]](https://github.com/ga4gh/server/issues/335#issuecomment-176725710).

**Comment by jeromekelleher** [comment]
It's tricky @jmarshall --- setting ``hts_verbose`` doesn't work because there are multiple different versions of htslib compiled in to each module within pysam, and we're not touching the correct instance of ``hts_verbose``.  Trying to access a https URL doesn't work either because libcurl won't accept self-signed certificates (I think), and we don't have access to the internals. Anyway, this isn't a self-contained fail-safe way to determine whether we're using libcurl --- we need to be serving a BAM from a web server somewhere in any case. Any number of reasons could cause this test to fail.

Checking the user agent string is the only way I could find that worked, after a _lot_ of experimentation.

**Comment by bioinformed** [comment]
The multiple versions of htslib problem within pysam should be resolved
when Andreas changed the default build mode to "shared".  I'll look into
adding a more obvious way to determine which networking code is available
at runtime.  Apologies for not thinking of this wrinkle in advance.

**Comment by jeromekelleher** [comment]
Thank @bioinformed, that would be great!

**Comment by kozbo** [comment]
@bioinformed Any progress on this?

**Comment by david4096** [comment]
Haven't seen an issue with this in any recent versions.
