### ISSUE TITLE
Thousand genomes variant annotations special case

### ISSUE THREAD

**Issue by david4096** [ga4gh/server#1035]
The split ANN field has become more or less a standard for representing annotated variants in VCF, however, the Thousand Genomes annotated variant sets have a `CSQ` field that is arranged differently. If we would like to host the thousand genomes annotated variants we either have to detect this case or munge them into the expected form.

From ALL.chr1.phase3_shapeit2_mvncall_integrated_v5.20130502.sites.annotation.vcf
```
1       13382   .       C       G       100     PASS    AC=1;AF=0.000199681;AN=5008;NS=2504;DP=28817;EAS_AF=0;AMR_AF=0;AFR_AF=0;EUR_AF=0;SAS_AF=0.001;AA=c|||;CSQ=G|ENSG00000223972|ENST00000456328|Transcript|non_coding_transcript_exon_variant&non_coding_transcript_variant|630|||||||1||||||;ERB=G||proximal_2|Regulatory_Feature|proximal_enhancer,G||ctcf_2|Regulatory_Feature|ctcf_insulator;FUNSEQ=0.0000
```

**Comment by jeromekelleher** [comment]
I would vote for  the format. Munging 1KG data is not something to be taken lightly, and probably other people have adopted the convention anyway.

**Comment by david4096** [comment]
This feature is ready for review/merge.
