### ISSUE TITLE
Reorganize server data directory hierarchy for sequence annotations

### ISSUE THREAD

**Issue by macieksmuga** [ga4gh/server#1038]
The current folder hierarchy is 
`datasets/<dataset>/sequenceAnnotations/<feature_files...>`
I'd like to change this to:
`datasets/<dataset>/sequenceAnnotations/features/<feature_files...>`
so as to accommodate a future:
`datasets/<dataset>/sequenceAnnotations/continuous/<wiggle_files...>`

**Comment by diekhans** [comment]
+1 for this, since wiggle will be an important data type.

**Comment by jeromekelleher** [comment]
No objections.

**Comment by dcolligan** [comment]
sounds good

**Comment by jeromekelleher** [comment]
Closed by #1166.
