### ISSUE TITLE
URL support for reads and variants within data repo

### ISSUE THREAD

**Issue by jeromekelleher** [ga4gh/server#1045]
{Kevin O: I pasted this initial comment back into the history from my email. Somehow github dropped it!}

We need to provide support for reads and variants being read from a URL. Here is a sketch of one possible implementation:

Within FileSystemDataset, glob for json files. For each JSON file, the localId is the basename of this file. So, for a readGroupSet HG00096, we would have HG00096.json.

The JSON file will look something like this

{
"data_url": "http://example.com/HG00096.bam",
"index_url": "file://ga4gh-example-data/dataset1/reads/HG00096.bam.bai",
}
The idea here is that we abstract back a bit from having the data files and indexes stored in a fixed location. We read the JSON file which stores the URL of the data file and the index file. For now, we assume that the index file is stored locally, but we might change this later to do on-demand fetching and caching. We can also use this JSON file to store metadata about the ReadGroupSet which we obtain from the repo administrator at ingestion time.

Change the signature of reads.HtslibReadGroupSet so that it takes the dataUrl and indexFile as parameters. Use these to open the underlying pysam object.
The rest should follow easily enough. Thoughts?

**Comment by jeromekelleher** [comment]
Another thought: for 1000 genomes, it's probably not such a great idea to have several thousand JSON files lying around inside one directory. We could make a single file to hold all of the URLs/metadata easily enough. Perhaps this should be done as a follow up?

**Comment by david4096** [comment]
Here's an attempt to break this into some more manageable tasks.

- [ ] Repo manager tests
Tests which show the `add-readgroupset repo datasest url` functionality working
Tests which show the `add-removereadgroupset repo datasest rgsName` when a rgs has been added to the repo via url.
- [ ] Reads unit tests
HTSLib Read group set should accept urls
Sending in a url and index file executes the remote rgs code path
- [ ] FileSystemDataset
Datasets will pickup json files as well as BAMs when adding read group sets

**Comment by jeromekelleher** [comment]
Thanks @david4096, I agree we need to split this into more manageable subtasks. However, this was intended as a design discussion rather than an assignment of work. Does anyone have any thoughts on this design, or are we all happy with what I've outlined above?

**Comment by dcolligan** [comment]
Is anyone working on this?  Seems like a prerequisite (or at least something that goes in tandem with) adding remote files via the repo manager.  We should also add it to the milestone, IMHO.

**Comment by dcolligan** [comment]
Oh, I see Jerome is working on it; I'll assign him and add it to the milestone

**Comment by jeromekelleher** [comment]
Thanks @dcolligan, probably time I did a bit of coding again!

**Comment by jeromekelleher** [comment]
Closed by #1166.
