### ISSUE TITLE
Richer ontology model support

### ISSUE THREAD

**Issue by david4096** [ga4gh/server#1046]
In the thread of #980 @cmungall raised:

> You assume id<->name will be 1:1 within any given ontology.

> (You're also using strings like sequence_ontology as unique IDs for the ontologies. The only consistent and stable way to identify an ontology is by it's ontology id (for OBO library ontologies) or IRI (for any ontology). You should see this in the ontology field for any obo formatted ontology, or the Ontology object in RDF/OWL. E.g. so, go, hp. These can easily be found on obofoundry.org (the metadata is available in a variety of formats, you can also see the list here: https://github.com/OBOFoundry/OBOFoundry.github.io/tree/master/ontology).

> I expect you will need a richer ontology model at some point, at least with support for synonyms, traversal, definitions, obsoletion metadata, versioning. Ping me if you want feedback on either requirements or code.

A more robust ontology model would support the sanctioned RDF formats, which are hosted [here](https://github.com/The-Sequence-Ontology/SO-Ontologies).

**Comment by diekhans** [comment]
We need to be able to support true ontology queries.  The
current exact match is a short-term hack.  The thinking of the
metadata group was this would alway go through the an external
ontology lookup service, not have a GA4GH server maintain a
local copy of ontology.  Of course, it would probably want to
cache the results.

**Comment by cmungall** [comment]
Separation of concerns is always good.

However, it's not always easy to distribute the query processing across services.

Consider a basic query for finding all variants of a certain phenotype ontology class `p`. The query engine should return any variant `v` where `v has-phenotype p'`, and `p' descendant-of p` 

For example, when asking for any variant implicated in an [Abnormality of the nervous system](http://purl.obolibrary.org/obo/HP_0000707) (plus other parameters), we would want to return variants annotated to [HP:0009592](http://purl.obolibrary.org/obo/HP_0009592) (Astrocytoma)

The obvious way to do this in the distributed setup is to query the ontology engine with `p`, the ontology engine returns a list `p1,...,pn`, where `p_i` is a descendant of `p`. The variant server then takes this list and threads it into a query for the other parameters (for example, using a SQL `IN` clause).

This all works as expected, but you will take a performance hit, particularly when the user is interested in very broad terms like 'Abnormality of the nervous system' which can have 1000s of descendants. If the ontology engine and the genomic engine are one and the same then you can take advantage of built in query optimization. Alternatively you index in advance using the ontology engine, and store the ancestor terms in addition to the direct term.

Maybe this is a perfectly acceptable trade-off for the simplicity win, at least for a first pass, and sorry of this is obvious. Just alerting you to this, as I've been other systems go around this a few times before eventually deciding that they need to bring some basic ontology logic into the either the main query engine, or as a pre-indexing step.

**Comment by jeromekelleher** [comment]
Again, very helpful, thanks @cmungall!

**Comment by jeromekelleher** [comment]
This should be addressed in #1147. Can we close this issue in and move discussion over there?

**Comment by diekhans** [comment]
discussion continues in #1147.
