### ISSUE TITLE
Refactor repo manager to allow user-specified metadata for reference sets

### ISSUE THREAD

**Issue by macieksmuga** [ga4gh/server#1047]
While working on #955 I noticed that the Repo manager currently assumes various metadata values when generating companion JSON files to references. These should instead be optionally specified by the user on the command line or through a user-supplied metadata file. 

Related to #1040

**Comment by dcolligan** [comment]
Please list the metadata values that you want to make user-settable.

**Comment by jeromekelleher** [comment]
Closed by #1166.
