### ISSUE TITLE
Suggestion to coordinate development of infrastructure and features

### ISSUE THREAD

**Issue by macieksmuga** [ga4gh/server#1071]
Since we're currently working on both infrastructural improvements to the server (ex: compound ID, protobuf) as well as additional endpoints and data entities (ex: sequences annotation, biodata, RNA), it would be helpful if every infrastructure PR included an explicit description of changes and warnings, if any, needed for any branch working on a new data entity or endpoint.

**Comment by jeromekelleher** [comment]
Agreed @macieksmuga, an explicit discussion of the impact for feature branches will accompany the sql repo PR.

**Comment by dcolligan** [comment]
This doesn't seem like an outstanding issue... closing...
