### ISSUE TITLE
Better handling of data source filenames in server

### ISSUE THREAD

**Issue by macieksmuga** [ga4gh/server#1087]
The current system manually counts off `.`s to strip out suffixes whenever they're encountered, which can create issues with files whose names nontrivially include `.`. Ex: #1086

**Comment by macieksmuga** [comment]
I believe there is no general mechanism to solve the problem as currently stated: Some file types we use have "double extensions" such as `.fa.gz` whereas other automatically ingested files have `.`s in their filename body, such as `GL000249.1.json` (part of the GRCh37 reference set) and even `GL000249.1.fa.gz.fai` - which have extra `.`s in both the filename body _and_ extension. 

The only proper solution that I can see to all of these is to stop relying on filenames altogether to guess at the server's data entity names. This work is already proceeding in #1079.

**Comment by diekhans** [comment]
Is this blocking anything with 1K genomes?

**Comment by macieksmuga** [comment]
Nope. The 1 line fix in #1086 removes the one existing block for me. This issue was created to capture the fact that #1086 is a pure patch, not a general solution.

**Comment by dcolligan** [comment]
The general mechanism that the repo manager uses is that you have to know what kind of file extension you are expecting.  If you scan from the right you can determine if it's the kind of filetype you want.  But yeah, absent that, I don't think there is a general solution, but I don't know if there's going to be a case where we want to parse a filename and not know the type of file we're looking for.

**Comment by jeromekelleher** [comment]
Yes, hopefully all this messiness goes away post #1079.

**Comment by jeromekelleher** [comment]
Closed by #1166.
