### ISSUE TITLE
Landing page -- support

### ISSUE THREAD

**Issue by david4096** [ga4gh/server#1088]
The index page of the server that prints configuration about the server could include an optional HTML fragment so we can add support blurbs for a deployed server.

This could be a HTML snippet that gets injected into the template if it is present. It would provide a support email for our next deployment.

**Comment by jeromekelleher** [comment]
Good idea. The support email should be provided as a Flask configuration option, e.g., SUPPORT_EMAIL.

**Comment by diekhans** [comment]
We need a bit more than support e-mail.  A HTML block to insert
would be describe the site.

**Comment by jeromekelleher** [comment]
Sure, whatever works. I just don't want to hard-code in any specific information to the source.

**Comment by diekhans** [comment]
A conf variable pointing the html frag would do the trick.
