### ISSUE TITLE
Mac OS X Development install instructions

### ISSUE THREAD

**Issue by david4096** [ga4gh/server#1090]
Although people aren't deploying on Mac we can offer better onboarding instructions for developers using Mac. This means determining the necessary equivalent libraries based on the current installation instructions. Apache will not be needed.

**Comment by bjea** [comment]
When i followed your instructions below, it seemed to be fine until running the test.
1. Install libraries and header code (which you have partially done)
2. Download source code
Using git, the method in the directions is fine here.
3. Install python dependencies
from within the server:
pip install -r dev-requirements.txt
4. Download/extract example data
5. Start server/run tests
To start the server simply navigate to the directory and run `python server_dev.py` and pointing a web browser to http://localhost:8000.

The error message was:  "OSError: [Errno 2] No such file or directory: 'ga4gh-example-data/datasets/1kg-p3-subset/sequenceAnnotations'"

There seemed to be no such a file or directory named "sequenceAnnotations" in the example data downloaded from https://github.com/ga4gh/server/releases/download/data/ga4gh-example-data-v3.2.tar, should i download some other example data or what should i do?  Thank you very much!

**Comment by david4096** [comment]
Thanks Bettie! I added an empty `sequenceAnnotations` directory to the example data. If you redownload and extract the example data you should not see that error anymore. I'm glad the pip install worked without having to circle back to homebrew.

**Comment by bjea** [comment]
Good morning David!  Sorry for my delayed response, kinda swamped yesterday.  Thanks a lot for your prompt reply!  I tried to run the test several times, but it showed "socket.error: [Errno 48] Address already in use" every time.

**Comment by david4096** [comment]
Closed with https://github.com/ga4gh/server/pull/1279
