### ISSUE TITLE
Versioning scheme for sql data repo

### ISSUE THREAD

**Issue by dcolligan** [ga4gh/server#1116]
Right now we are just inserting a literal arbitrary value into the `System` table.  We need to come up with a better scheme than this.

**Comment by macieksmuga** [comment]
I'm not sure what you're thinking here @dcolligan - Having a literal schema version satisfies the need for a migration path as the schema evolves (application checks schema version in the DB against the value in its codebase, performs any needed actions on DB to update it). Are there any other requirements here that need to be satisfied?

**Comment by jeromekelleher** [comment]
I agree with @macieksmuga  here. Initially I was thinking just a simple ``major.minor`` version scheme using semantic versioning: we increment ``minor`` each time we make a non-breaking change, and ``major`` each time we make a breaking change. What do you think @dcolligan?

**Comment by dcolligan** [comment]
If it's as easy as that and adding an `if` to make sure the version is correct, fine... just as long as we have something!

**Comment by jeromekelleher** [comment]
Sounds like you'd like to implement this @dcolligan!

**Comment by dcolligan** [comment]
Fixed in #1128
