### ISSUE TITLE
IDs for SQL repo

### ISSUE THREAD

**Issue by jeromekelleher** [ga4gh/server#1119]
A number of questions have popped up about how we're going to manage IDs in the SQL repo. Here is the current state-of-play, and a sketch for how we might proceed.

In the current branch and PRs #1104, #1117, IDs work in precisely the same way as they do in the master branch. A CompoudId is constructed based on the object's name and the names of its enclosing containers. This constructed ID is stored in the DB in the ``id`` field and is used as the primary key. This works quite well and has the advantage of not breaking too much code at once.

Once we have merged the SQL repo into master, I propose that we look at the ID system again. Now, we can do something much simpler for container types. I think that we create a unique integer for each container as the ID, and store a lookup table mapping this value to the table in question. For, example, we might have
```
id           table
1234     Dataset
3223     ReadGroupSet
5234     CallSet
....
```

This will allow us to run GET queries efficiently without having to put any structure into the IDs themselves (for these container types). I think we should use randomly generated values for the IDs so that there is no danger of information leakage.

We are still in a difficult situation when it comes to supporting GET for (e.g.) variants. I think we will have to continue using a CompoundId structure here (albeit a flattened one, just being the tuple ``(variantSetId, variantId)``) , as there just isn't any alternative, beyond reading in the entire VCF file at load time and creating an auxiliary index.

**Comment by macieksmuga** [comment]
+1 Yes! All containers get a simple auto-generated ID upon ingestion by the repo manager tool (which I'm thinking of more as a registry manager, now that the container files themselves can be stored in arbitrary locations), and all GA4GH entities within a container have an ID that decodes into a pair `(containerID, entityID)`, the second entry determined differently per container type.

**Comment by david4096** [comment]
@jeromekelleher have you addressed this elsewhere, can we close?

**Comment by jeromekelleher** [comment]
Yes, let's close this, thanks.
