### ISSUE TITLE
Repo manager not ingesting references and reference sets correctly

### ISSUE THREAD

**Issue by macieksmuga** [ga4gh/server#1120]
The repo manager currently seems to expect a single FASTA file as input for its `add-referenceset` command, and creates a corresponding full reference set for it with a single JSON file for the first record encountered. This is incorrect regardless of how many records the FASTA file contains.

Since ingesting novel reference sets is not at present a critical function of the server (most of the time, we'll just be using copies of pre-ingested GRCh37 or 38 reference sets), I propose we solve this fully in the upcoming repo manager SQL refactor #1104, along with a proper solution to #955

**Comment by diekhans** [comment]
Are the servers we are currently deploying using split FASTAs?

Does this impact compliance?

**Comment by macieksmuga** [comment]
@diekhans: Yes, and no.
😄

**Comment by david4096** [comment]
If this is going to be fixed in a future version we should list it as a known issue in our documentation somewhere.

**Comment by jeromekelleher** [comment]
This is solved in the current sql repo branch.

**Comment by jeromekelleher** [comment]
Closed by #1166.
