### ISSUE TITLE
File handles being opened for ReadGroupSet search

### ISSUE THREAD

**Issue by jeromekelleher** [ga4gh/server#1129]
When we run a readgroupsets/search operation in the SQL repo we should not have to look at the underlying file handles (indeed, it's essential that we don't, is this operation will be cripplingly slow when we're opening connections to thousands of remote URLs.)

We need to track down why this is happening and eliminate the open call. All the data we need to satisfy a search readgroupsets call should be derived from the BAM file at import time and stored in the DB.

To reproduce: Put a print statement into ``openFile``, and run a search-readgroupsets

**Comment by dcolligan** [comment]
The initial reason this is happening is because of the `getAlignedReads` and `getUnalignedReads` calls in `AbstractReadGroupSet.toProtocolElement`, which access the file.  These values should be constant, so we should cache them.

**Comment by jeromekelleher** [comment]
Excellent --- these go into the ``Stats`` object, right? If so, we should populate this at load time and store the JSON in the DB.

**Comment by dcolligan** [comment]
Fixed in #1140
