### ISSUE TITLE
Experiment and ReadStats not stored in DB

### ISSUE THREAD

**Issue by jeromekelleher** [ga4gh/server#1130]
We're currently not storing Experiment and ReadStats in the DB for ReadGroupSets. These need to be stored. We should follow the approach taken elsewhere for now, and store the JSON version of the protocol element, which can then be read in at run time.

This is probably related to #1129.

**Comment by dcolligan** [comment]
For ReadGroups, you mean... ReadGroupSets do not have an experiment field (and storing ReadGroupSets.stats is #1129)

**Comment by dcolligan** [comment]
Fixed in #1140
