### ISSUE TITLE
add robot.txt to production server files

### ISSUE THREAD

**Issue by kozbo** [ga4gh/server#1136]
Place the file next to the application.wsgi file in the root of the server. 

Suggested content is

```
User-agent: *
Disallow: /
User-agent: Googlebot
Disallow:
```

**Comment by diekhans** [comment]
Is the googlebot entry for allowing indexing of static pages?
We want to make sure it doesn't hit the API end points.

**Comment by kozbo** [comment]
@diekhans Yes, the googlebot entry will only index static pages, it will not hit the API endpoints.

**Comment by dcolligan** [comment]
Fixed in 1136_robots_txt
