### ISSUE TITLE
datasetId should not be optional in rnaquantification search

### ISSUE THREAD

**Issue by saupchurch** [ga4gh/server#1144]
for consistency with the rest of the API datasetId should be required by RNAQuantification search not an optional argument

**Comment by david4096** [comment]
The schema should reflect this as well (I believe).

**Comment by saupchurch** [comment]
the change has already been made in the rna branch of ga4gh/schemas

**Comment by saupchurch** [comment]
PR #1146

**Comment by saupchurch** [comment]
fixed in #1146
