### ISSUE TITLE
Document database write access

### ISSUE THREAD

**Issue by jeromekelleher** [ga4gh/server#1161]
As @david4096 pointed out in #1158 we might need to allow for write permissions for the web server when pointing it at a repository DB file. See [here](https://www.sqlite.org/tempfiles.html) for information on sqlite temp files.

It seems a bit wasteful though, since these files are all for transational updates and so on, and we really just want to open the DB in read-only mode when running within the webserver. This would avoid this problem, and also give us some extra strength-in-depth security wise in terms of data modification through SQL injection attacks.

Unfortunately, there doesn't seem to be an easy way to do this in [Python < 3.4](http://stackoverflow.com/questions/10205744/opening-sqlite3-database-from-python-in-read-only-mode).

Thoughts?

**Comment by dcolligan** [comment]
In that SO thread there's a workaround for our version of python.

**Comment by jeromekelleher** [comment]
Yeah, looks a bit gnarly though. I can imagine that getting messy when we're running under a web server --- SELinux or something might not like us accessing ``/dev/df/x``. Or maybe not...

**Comment by david4096** [comment]
Yeah, I don't think we need to go to those ends yet. I'd just like it documented that the server needs write access to the directory containing the `.db`.

**Comment by kozbo** [comment]
Also, in a related note, we found that the Sequence Annotations files needed to have www-data ownership when running under apache
"""
datasets/1kgenomes/sequenceAnnotations:
-rwxrwxr-x 1 www-data    www-data         32768 May 17 17:35 gencode_v24lift37.db-shm
-rwxrwxr-x 1 www-data    www-data             0 Apr 20 13:58 gencode_v24lift37.db-wal
"""

**Comment by david4096** [comment]
I think as long as we're using SQLite the best practice is to run the repo as the same user as the server.
