### ISSUE TITLE
Client no longer displays sent JSON in verbose mode

### ISSUE THREAD

**Issue by jeromekelleher** [ga4gh/server#117]
The client CLI provides a verbosity option to provide increasing levels of detail on the transactions between the client and server. This no longer shows the JSON sent to the server, which was a very useful debugging tool. Here is a possible behaviour for -v:

- -v: shows summary of HTTP messages sent to and received from server.
- -vv: shows full JSON messages sent and received.

**Comment by MollyZhang** [comment]
working on this

**Comment by dcolligan** [comment]
fixed in #127
