### ISSUE TITLE
Repo manager should have a catch-all error exception handler

### ISSUE THREAD

**Issue by jeromekelleher** [ga4gh/server#1172]
Assumes #1166 has been merged.

If an unexpected exception occurs in repo manager, this should be considered a bug. Therefore, we should add a catch-all exception handler to repo main that prints the stack trace, along with a message like:
```
An internal error has occurred. Please file a bug report at https://github.com/ga4gh/server/issues
with all the relevant details, and the following stack trace:

Stack trace:
[stack trace]
```
Also, we need to make sure we exit with a non-zero exit status.

**Comment by dcolligan** [comment]
Fixed in #1193
