### ISSUE TITLE
Parse annotation creation times from the VCF header

### ISSUE THREAD

**Issue by jeromekelleher** [ga4gh/server#1176]
Assumes #1166 has been merged.

Annotation programs often provide the creation time of the annotations in VCF headers. We should use this information to set the creation and update times in for VariantAnnotationSets when we call ``populateFromFile``. These are then stored in the DB.

**Comment by andrewjesaitis** [comment]
I'm working on this. Pretty much have it finished (9f3df32c5e04b9b47fbbe21bd54fd373bbced3fe), just need to test it a bit more.

**Comment by jeromekelleher** [comment]
Great, thanks @andrewjesaitis.
