### ISSUE TITLE
``tests/unit/test_faultydata.py`` should be reinstated

### ISSUE THREAD

**Issue by jeromekelleher** [ga4gh/server#1179]
Assumes #1166 has been merged.

The ``tests/unit/test_faultydata.py`` is intended to check that we get the correct behaviour when we try to insert bad data into our repo. The tests currently in the module will need some refactoring, and should be reinstated. We should also aim to add quite a few more tests here, as dealing properly with dodgy inputs is one of the most important usability criteria for bioinformatics software, and will really help our users do their job better and more efficiently.

**Comment by dcolligan** [comment]
Fixed in #1221
