### ISSUE TITLE
Add tests to ``tests/unit/test_datarepo.py`` to verify behaviour when incorrect indexes are passed

### ISSUE THREAD

**Issue by jeromekelleher** [ga4gh/server#1180]
Assumes #1166 has been merged.

The ``add-variantset`` and ``add-referenceset`` functions in repo manager allow the option of specifying index files to go with the data URLs provided. We should add some tests to check that we correctly catch problems such as providing files that (a) aren't actually indexes; and (b) are indexes but are for the wrong file. It might be tricky to do this with pysam, but we should figure out what we need to do to detect this situation and raise an informative error message.

**Comment by dcolligan** [comment]
The `add-referenceset` command doesn't allow specification of indexes... presumably you meant `add-readgroupset`?

**Comment by jeromekelleher** [comment]
Yes, sorry, that was a typo.

**Comment by david4096** [comment]
Related https://github.com/ga4gh/server/issues/1210

**Comment by dcolligan** [comment]
Fixed in #1214
