### ISSUE TITLE
Add tests to ``tests/unit/test_datarepo.py`` to verify behaviour when duplicate names exist

### ISSUE THREAD

**Issue by jeromekelleher** [ga4gh/server#1181]
Assumes #1166 has been merged.

When we have (e.g.) ``dataset1/variantset1`` and ``dataset2/variantset1``, we need to ensure that calling  ``ga4gh_repo delete-variantset dataset1 variantset1`` correctly deletes ``dataset1/variantset1`` and doesn't affect  ``dataset2/variantset1``. Likewise across other containers.

See comments on line 342.

**Comment by dcolligan** [comment]
Fixed in #1195
