### ISSUE TITLE
variants-search should with no arguments should return all variants on server

### ISSUE THREAD

**Issue by jeromekelleher** [ga4gh/server#119]
The `variants-search` client command is a useful development tool, but tedious to use as it needs a lot of input to return anything. We should change the default behaviour to return variants from the server, if there are any. So:
- `--end` should default to some large number, so we always overlap with something. (Ideally, the `end` value should be nullable in the protocol so that we can specify this requirement more naturally);
- If no variantSetIds are specified, we should run a searchVariantSets request, and get the IDs for these from the server.

**Comment by dcolligan** [comment]
Fixed in #154
