### ISSUE TITLE
document how to run development server with profiling

### ISSUE THREAD

**Issue by diekhans** [ga4gh/server#1192]
running the development server with profiling is tricky because flask gets in the way by starting a second process for the reloader functionality.  Please document the process:

`python -m cProfile -s cumulative -o profile.out ko-server/server_dev.py -H 100.70.26.73 --dont-use-reloader --config-file /srv/ga4gh/config.py`

**Comment by dcolligan** [comment]
A wiki page on profiling might be a good place to put that:

https://github.com/ga4gh/server/wiki

Or we could put it in the server docs somewhere.
