### ISSUE TITLE
Python 3 support 

### ISSUE THREAD

**Issue by jeromekelleher** [ga4gh/server#120]
This issue is to collect discussion on our Python 3 support, or lack thereof. 

The major blocker for Python 3 support seems to be the [avro]( https://pypi.python.org/pypi/avro) module, which does not support Python 3. There is a separate [Python 3 avro module](https://pypi.python.org/pypi/avro-python3/1.7.7). Both seem to be associated with the official Avro project, so it's difficult to tell if one is official and the other is not.

The problem with the Python 3 module is that it has a completely different API. For example, in the Python 2 version we have `avro.schema.parse` and in Python it is `avro.schema.Parse`. Even working around these (insanely gratuitous) changes, there seems to be deeper differences, so we'll need to choose one or the other (or neither).

Any thoughts on this?

**Comment by hershman** [comment]
While Flask works with Python 3, they [don't recommend using it under most circumstances](http://flask.pocoo.org/docs/0.10/python3/).  I get the sense that it's still too early to move to Python 3 so I'm -1.

**Comment by dcolligan** [comment]
It seems like there are library issues with python 3, and we don't currently support python 3, and as @diekhans says "Part of being a reference server, you get to limit your audience to people who know what they are doing."  So, why support python 3 in the first place?  Correct me if I am wrong, but I think python 2 has a much larger install base and mindshare.

**Comment by diekhans** [comment]
Yes, python 2->3 conversion is going slowly.  In hindsight, I
think they made some mistakes in their approach [not that I
would have had a better idea].  I also think some of there
changes were not worth the breakage (like rich comparisons).

If that the libraries server depends on are not ready for python
3, then, yes avoid it.  The main point of this suggestion was to
remove having to worry about being compatible, which has been a
pain in my experience.

Mark

**Comment by jeromekelleher** [comment]
OK, let's shelve Python 3 support for the moment so. We can revisit when we've got a more complete implementation and see if we can replace the Avro parts we're using. Also the Flask issue is a good one, thanks @hershman.

**Comment by diekhans** [comment]
I completely agree with shelve Python 3 for now.  If the
dependencies are not ready, it wastes time, not saves it.

sigh, maybe Python 3000 was not such a bad name..

**Comment by diekhans** [comment]
Jerome Kelleher <notifications@github.com> writes:
> is avro.schema.Parse. Even working around these (insanely gratuitous) changes,
> there seems to be deeper differences, so we'll need to choose one or the other
> 
> Any thoughts on this?

This is much worse than insanely gratuitous; it's changing the code
to go against the common conventions.  I highly suggest filing
tickets on this.
