### ISSUE TITLE
SQL repo needs absolute paths

### ISSUE THREAD

**Issue by david4096** [ga4gh/server#1204]
The full path must be used when adding a file because the server may be running from a different location than the database. Even if the file exists according to `ga4gh_repo`, without an absolute path the installed server may not be able to find it.

I made this mistake adding a feature set to the 1kgenomes server and the failure wasn't detected leading to a 500 when issuing requests against that featureset.

**Comment by jeromekelleher** [comment]
This is a slightly tricky one, because we do sometimes want relative paths too. The only time I can think of right now is for our example data,  which we couldn't just download and run anymore if paths we're obligately fully qualified. 

Perhaps the most useful thing to do is to automatically expand all paths in the repo manager CLI when adding objects, but to provide a command line option to suppress this behaviour?

**Comment by david4096** [comment]
I would always expand relative paths to absolute paths. I think it's fine if the administrator needs to generate the registry, for the example data it will only take a few seconds.

However, we could handle it via documentation: "If the server is running from a different location than the data files then you must specify an absolute path when adding files to the registry."

**Comment by macieksmuga** [comment]
With an emphasis on non-development deployments (either via pip install & apache setup or just via docker), I agree with @david4096 here - let's require fully qualified paths, can always provide a shell-expandable idiom (`./mypath` or `$PWD/mypath`) when spinning up local dev instances.

**Comment by diekhans** [comment]
having the repo manager expand that than relying on the user to do it is more robust and user friendly

**Comment by jeromekelleher** [comment]
Come to think of it, we don't use the repo manager to create the example data for development, so expanding all input paths to be absolute is the way to go. So, to be clear, if I say
```
ga4gh_repo add-readgroupset file.bam
```
the path in the DB will be stored as /full/path/to/file.bam.

**Comment by dcolligan** [comment]
I'll make a comment here similar to the one I made in #1211, which is that it might be a good idea to make the datarepo insertion code more OO and then have methods for handling each insertion step.  In a `prepare` method, the objects that have file paths could have them expanded to absolute paths, for instance.
