### ISSUE TITLE
CLI docs for repo manager need rewriting

### ISSUE THREAD

**Issue by jeromekelleher** [ga4gh/server#1205]
The CLI docs for repo manager are very limited. We need to create a comprehensive reference resource for all the commands on line. It would be good if we could use something like [sphinx-argparse]
(http://sphinx-argparse.readthedocs.io/en/latest/)  so that we have a single definitive source for our CLI docs, defined in the help text.

**Comment by kozbo** [comment]
can be closed based on PR #1218

**Comment by jeromekelleher** [comment]
I don't think so --- we still need a rewrite to make this actually usable. I'll make a start on it and make a PR later.

**Comment by david4096** [comment]
Can we close via https://github.com/ga4gh/server/pull/1228?

**Comment by jeromekelleher** [comment]
I think so. There's still work to be done, but #1228 should bring us a long way towards useful documentation.
