### ISSUE TITLE
An administration tutorial is needed

### ISSUE THREAD

**Issue by jeromekelleher** [ga4gh/server#1206]
We need a full tutorial for the process of administering a repo. This should go through the full process of downloading and installing a reference, creating a dataset, and all the rest. This will be essential in getting people started in working with the repo.

**Comment by david4096** [comment]
Leaving the cookbook I used to stand up the 1kgenomes server here.

https://gist.github.com/david4096/fa83f6bbe85b7f3342accdbaa4e7d9d1

**Comment by macieksmuga** [comment]
Also, a sketch of a document for putting up a dockerized instance of the GA4GH server:

https://github.com/BD2KGenomics/ga4gh-integration/wiki/Setting-up-data-for-a-docker-instance

**Comment by david4096** [comment]
This work in progress can be seen here. Given the UI for ontologies is changing I've left that as a TODO. https://github.com/BD2KGenomics/ga4gh-integration/wiki/Server-Repo-Admin-Tutorial

**Comment by jeromekelleher** [comment]
This is great @david4096, exactly what we want.
