### ISSUE TITLE
New end-to-end test required

### ISSUE THREAD

**Issue by jeromekelleher** [ga4gh/server#1213]
Recent issues have shown some weaknesses in our test coverage (see e.g. #1209, #1164), where we're only discovering some issues when the compliance suite is run against the server. The root cause of this is that we're not really exercising our production data interfacing layer (i.e., where we interact with BAM, VCF and FASTA) in our end-to-end tests.

I think we could resolve this by adding a new end-to-end test, that uses the test data repository and runs a bunch of queries on it. Rough outline:

- Create a SqlDataRepository based on ``tests/data/repo.db``, and a ``LocalClient`` that uses this repo.
- Run a bunch of queries, exercising as much of the query interface as possible on all the objects. It's fine for these queries to be exhaustive, we don't have that much data in the test repo. This should also verify with page sizes, ensuring we always get back the same result set for different page sizes.

This should probably be done in a series of PRs, as there might be quite a lot to do in one go. References seem like a good place to start. We will probably find that our test data is inadequate to test all the query interfaces, so we should update the test data as necessary.

**Comment by kozbo** [comment]
@jeromekelleher It seems like the ideal way to do actual end to end tests is to use the repo manager to put data into the repository and then queries to pull data back out again. Is this what you are suggesting here or is the repo.db a pre-ingested database?

**Comment by jeromekelleher** [comment]
This is true @kozbo, and we should also do what you're talking about I think. However, what I had in mind here was just using the pre created repo.db that is checked into Git. For this test I think we need to concentrate on stressing the query interface, so we get into all the little cracks in the data interfacing code.

But yeah, another end-to-end test where we bung a bunch of stuff that we know about into the repo using repo manager, and then do queries on the server via a local client to make sure that the stuff we expect to find is something we want.

**Comment by dcolligan** [comment]
Fixed in #1219
