### ISSUE TITLE
Create a new release for PyPI that captures the sql repo changes

### ISSUE THREAD

**Issue by kozbo** [ga4gh/server#1216]
I would like to have another tagged release before we merge in the Protobuf code. I don't have a firm date for the Protobuf code but I am hoping it can be reviewed for merge by May 13, 2016.

**Comment by jeromekelleher** [comment]
Completely agree @kozbo, it should be a strong priority to make a solid release before we take on the protobuf transition pain. Some points to note:

- I think we should decide on our nomenclature (#1217), and improve our administration documentation (#1205, #1206) before we release. These are critical for our admin user experience.
- Do we need updated ontology handling (#1147) for a new release? In either case, we need to think about the admin user experience for dealing with variant and sequence annotations, which is not entirely smooth right now.
- We should think about the forward compatibility issues that we are taking on. Specifically, our planned updated ID scheme (#1119) will require new IDs to be created for all objects in the DB, as well as a schema change if we change the type from string to int (not sure if this is worth the trouble, though). We will need to create an upgrade program to help admins upgrade their DB to the new version. I don't think we can avoid this, given the strong requirement to deploy now and the need to incorporate protobuf as quickly as possible, but I thought I should raise the point so we have visibility on this issue.

**Comment by kozbo** [comment]
Do we want to deal with the larger problem of upgrading as part of this issue? To quote @diekhans, we don't have to worry about upgrade/backwards compatibility until we get out of Alpha. That said, I think we need a thought-out plan for how we will handle it once we do get to beta.

**Comment by jeromekelleher** [comment]
No, I don't think we need to worry about upgrading in any formal sense, just keep this issue in the back of our minds as we're releasing.

**Comment by david4096** [comment]
Given the additions to the administration documentation and ontologies PR awaiting merge, is there anything else blocking a release?

**Comment by jeromekelleher** [comment]
No, I don't think so. Lets try and get them in and push the button!

**Comment by jeromekelleher** [comment]
OK, I think we're ready to tag 0.3.0 once #1236 has been merged. Over to you @kozbo, @david4096!

**Comment by jeromekelleher** [comment]
Ugh, just realised we need release notes... Can't tag quite yet.

**Comment by kozbo** [comment]
@jeromekelleher Would you like me to draft up some release notes for 0.3.0?

**Comment by jeromekelleher** [comment]
Yes please @kozbo! We need a PR on ``docs/status.rst`` with the notes before we can tag.

**Comment by david4096** [comment]
Here is a documentation only PR that you may want to include as well: https://github.com/ga4gh/server/pull/1239.

**Comment by jeromekelleher** [comment]
Version 0.3.0 released and pushed to pypi.

**Comment by kozbo** [comment]
Awesome @jeromekelleher
