### ISSUE TITLE
Repo manager returns an error when adding Sequence Ontologies last

### ISSUE THREAD

**Issue by kozbo** [ga4gh/server#1223]
While configuring a reference server I added all the components and then realized that I had't added the Sequence Ontologies file yet. I received an error:
"""
ga4gh_repo add-ontology repo.db /srv/ga4gh/compliance/sequence_ontology.txt
/srv/ga4gh/ga4gh-server-env/bin/ga4gh_repo: error: Ontology with name
'sequence_ontology' not found
"""
I was able to work around the problem by removing my repo.db file and restarting the process from the beginning, adding the SO file first.

**Comment by jeromekelleher** [comment]
Fixed in #1225.
