### ISSUE TITLE
Create python client library that is independent from the reference server codebase

### ISSUE THREAD

**Issue by kozbo** [ga4gh/server#1230]
A python client library for the GA4GH APIs would be usable for accessing any GA4GH compliant servers.  It could also be used for quickly prototyping python applications that sit on top of the API. Many people will be interested in this. Our current library comes with the reference server but there is no reason to link the two. This library should be a separate deliverable in the PyPi build. This is related to #934 because the CLI will need to use this library.

**Comment by kozbo** [comment]
Note that this issue came from a request from David Glazer in our scientific advisory board meeting.

**Comment by jeromekelleher** [comment]
OK, but this is not a trivial change and it will take time and disrupt development. I really don't see what we gain from this disruption: right now, the client can be used by anyone:

```bash
$ pip install ga4gh
$ ga4gh_client search-datasets server.com
$ python script_using_ga4gh_client_api.py
```

Splitting up our packages will result in _exactly_ the same user experience. The only difference is that they'll pull in a few more dependencies at the moment. So, why do we want to make this a priority? I'm not saying that we shouldn't do this, but we should be _at least_ in beta first before we start bringing this  extra  headache on ourselves.

**Comment by jeromekelleher** [comment]
See #355 and #785 for previous discussion on this topic.

**Comment by kozbo** [comment]
Agreed that this issue has been discussed in detail in other issues, especially #785 but this one splits out the client library request from the more general request to rename the pypi package. The arguments made for the stand-alone client library are still valid. 

I wrote this issue because I see this is a key deliverable for the project, though it is not high priority at this point. I would like us to publish client libraries once we have a complete API, and I think we should do that by the end of the summer.

**Comment by diekhans** [comment]
this is also a request from members of our SAB...

**Comment by david4096** [comment]
:100: https://github.com/ga4gh/ga4gh-client
