### ISSUE TITLE
enhance ENCODE RNA downloader 

### ISSUE THREAD

**Issue by saupchurch** [ga4gh/server#1232]
1) improve compatibility with sql repo manager
2) parse and process more of the metadata available from ENCODE DCC

**Comment by kozbo** [comment]
@saupchurch would you mind elaborating on each of these?
1. Is this referring to the effort to remove the ETL script? Please add some specific goals so that we4 know when we are done :-)
2. Which metadata fields would you like to include?

**Comment by kozbo** [comment]
Now covered by #1386 (formerly #1368)

**Comment by saupchurch** [comment]
this is really more of an extended example of importing RNA data and probably isn't really part of the core of the reference server.  Thoughts on moving this to the API Examples repository under BD2KGenomics?

**Comment by david4096** [comment]
+1 perfect
