### ISSUE TITLE
Link to bioapi examples in the documentation

### ISSUE THREAD

**Issue by kozbo** [ga4gh/server#1247]
We are starting to collect a number of different sets of sample code. We have a number of iPython notebooks and we have at least one visualization (planning to have more). We should have a page that gives a TOC of our example code with a brief explanation of each example to facilitate other programmers. 

Should this be in our [Development](https://github.com/ga4gh/server/blob/master/docs/development.rst) section or should it be a section on the Wiki?

Here are a few of the samples we have so far
#954
#746

https://github.com/david4096/bioapi-examples/blob/master/python_notebooks/1kg.ipynb

http://ga4gh-david.cloudapp.net:8080/map.html?start=&url=http://1kgenomes.ga4gh.org/&variantSetId=WyIxa2dlbm9tZXMiLCJ2cyIsInJlbGVhc2UiXQ&featureSetId=WyIxa2dlbm9tZXMiLCJnZW5jb2RlX3YyNGxpZnQzNyJd

**Comment by jeromekelleher** [comment]
Code samples are a great idea @kozbo. I don't think they should be in the Development section of our docs though, as these are intended for developers of the reference implementation, not client side developers using the API. 

I guess the simplest thing to do for now is put these together in their own page? Wiki is good too, whatever works out the easiest.
