### ISSUE TITLE
Client API docs broken by protobuf

### ISSUE THREAD

**Issue by jeromekelleher** [ga4gh/server#1252]
Currently, we have nice documentation for the client API derived directly from the Avro docs:

http://ga4gh-reference-implementation.readthedocs.io/en/stable/api.html#types

This works by taking the documentation comments from Avro, assigning them the docstrings for each type, and using Sphinx to automatically generate the documentation. It's not perfect, but it's a lot better than maintaining a second copy of the same documentation.

This no longer works with protobuf; we just get generic documentation for the protobuf types, and documentation like "Magic attribute generated for “assembly_id” proto field." for every attribute. It appears that protobuf doesn't transfer the docs into the Python objects at all, so there's no way we can fiddle things to get the right docstrings.

I don't see any easy answer to this, other than deleting this section of the docs and just pointing towards the generic explanations of what  the types are on the main documentation site. Any thoughts on this?

**Comment by diekhans** [comment]
Extraction of documentation from protobuf is going to be done before
the project is completely.

If you have special needs, let l-shift know.

**Comment by david4096** [comment]
I think the docs look alright, it could be improved by adding the type being iterated over.
