### ISSUE TITLE
Current status of OIDC support for ga4gh_server and ga4gh_client

### ISSUE THREAD

**Issue by rudyzhou2** [ga4gh/server#1257]
Hi ga4gh devs,

I am currently trying to implement ga4gh server and want to run the server with some degree of security, so I was wondering whats the current status of the OIDC implementation for both ga4gh server and ga4gh client since the documentation is very brief?

Thank you!

Rudy

**Comment by jeromekelleher** [comment]
The status of OIDC is that it is fully implemented, but hasn't been tried out in a deployment situation yet. The development work was done professionally, and it's well tested, so we're fairly confident it's correct. There may well be some rough edges that occur though, as we haven't had any feedback from a deployment situation.

The documentation should cover how to set up the server using Goole as the auth provider (http://ga4gh-reference-implementation.readthedocs.io/en/stable/configuration.html#openid-connect-providers) and work with the client application (http://ga4gh-reference-implementation.readthedocs.io/en/stable/demo.html#with-oidc). It's not great as you point out, and should be put into it's own section.

What are your security requirements? Do you have an authentication provider in mind? It would be great to get your feedback on how this works for you, so please let us know how you get on. We'll be happy to help if you hit any issues.

**Comment by rudyzhou2** [comment]
Hi Jerome,

We are looking to deploy ga4gh and currently I have setup an internal demo which works great (except no security). 

Unfortunately, our research center do not allow use of external authentication services such as Google, and we dont currently have an OIDC compatible Identity Provider yet... so I was looking to see whether you guys had any deployment experience using OIDC services other than Google, preferably something we can deploy ourselves... I guess not...

My plan right now is to test with Google OIDC first to see how it goes, then I am looking to deploy an internal IdP preferably linked with LDAP. I am currently looking at dex from CoreOS.
https://github.com/coreos/dex

I will report back once I get it fully deployed and working, any additional documentation regarding ga4gh OIDC implementation would be greatly appreciated though!!

Cheers,

Rudy

**Comment by jeromekelleher** [comment]
That sounds like a great plan @rudyzhou2, please let us know how you get on. Apologies for the lack of documentation --- up to now, we've had no real demand from users for this feature, and so it has fallen off our radar a bit. Unfortunately, we're all tied up working on other parts of the code right now, so I can't see the docs being updated in the short term. However, I've opened an issue on the topic (#1261), and it would really help if you could identify the places where the docs are most lacking there.

In the mean time, if you hit any issues, please just drop us a line here or via email and we'll be happy to help out any way we can.

**Comment by rudyzhou2** [comment]
Great! Thanks for the update jerome! I will report on the ticket regarding my findings!

**Comment by dcolligan** [comment]
Seems like this ticket was opened to ask a question that has been answered... objections to closing?  If there are problems that come up additional, more specific issues can be opened.

**Comment by jeromekelleher** [comment]
No objections from me; what do you think @rudyzhou2?

**Comment by rudyzhou2** [comment]
No problems! I am happy to report that I almost got the full setup going with LDAP connecting to OIDC and authenticating against ga4gh in a docker setup, just trying to figure out which proper callback URL to use since the documentation one does not work...

**Comment by dcolligan** [comment]
Cool.  Closing...
