### ISSUE TITLE
Process schemas assumes directory structure

### ISSUE THREAD

**Issue by david4096** [ga4gh/server#1268]
When running in various environments we should not assume the relative directory of schemas versus the server. As suggested by Gabriel, we should just accept an explicit path to the schemas as this is more clear and reliable.

`scripts/process_schemas.py`

        script_path = os.path.dirname(os.path.realpath(__file__))
        server = os.path.realpath(os.path.join(script_path, ".."))
        schemas = os.path.join(server, args.schema_path)

**Comment by diekhans** [comment]
A relative path is a reasonable default, as this is common
practice.  However it should be easily overridden with an
explicit check and clear error message on how to specific it if
if it's not there.

**Comment by jeromekelleher** [comment]
I agree we should take the schema path as a mandatory positional argument to the script and be done with it. We shouldn't need any path expansion if we do this.
