### ISSUE TITLE
ga4gh-example-data-v4.3 not available

### ISSUE THREAD

**Issue by dfornika** [ga4gh/server#1270]
Latest docs suggest downloading v4.3 of the example data, but it doesn't seem to be available.

http://ga4gh-reference-implementation.readthedocs.io/en/latest/demo.html

```
$ wget https://github.com/ga4gh/server/releases/download/data/ga4gh-example-data-v4.3.tar
--2016-06-20 19:23:35--  https://github.com/ga4gh/server/releases/download/data/ga4gh-example-data-v4.3.tar
Resolving github.com (github.com)... 192.30.252.121
Connecting to github.com (github.com)|192.30.252.121|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2016-06-20 19:23:35 ERROR 404: Not Found.
```

**Comment by jeromekelleher** [comment]
Thanks for this @dfornika, the file has been uploaded and should be available now.

However, unless you're working from the current version in git master, you should probably be working from the stable docs branch:

http://ga4gh-reference-implementation.readthedocs.io/en/stable/

Hopefully our on disk data structures will be stabilising soon, and we won't need to update the example data so often.

**Comment by dfornika** [comment]
Thanks.
