### ISSUE TITLE
Add release notes for the protocol buffer support release

### ISSUE THREAD

**Issue by kozbo** [ga4gh/server#1271]
@jeromekelleher shall we make this 0.3.1?

**Comment by jeromekelleher** [comment]
Yeah, 0.3.1 seems like the right version. From an outside perspective, the changes are fairly minor so it doesn't warrant a new major version.

**Comment by kozbo** [comment]
closed by #1272. Any reason to postpone the release @jeromekelleher?

**Comment by jeromekelleher** [comment]
No, I'll crank out the release tomorrow @kozbo.
