### ISSUE TITLE
error 500 when accessing features/search

### ISSUE THREAD

**Issue by alexanderDoria** [ga4gh/server#1274]
`{"featureSetId":"WyIxa2dlbm9tZXMiLCJnZW5jb2RlX3YyNGxpZnQzNyJd",
"start":3864,
"end":11592,
"pageSize":1,
"parentId":"",
"featureTypes":[  
   "gene"
],
"referenceName":"chr1"}`

**Comment by cmdcolin** [comment]
I'm was seeing 404 on api requests (/variants/search) to http://1kgenomes.ga4gh.org/

**Comment by kozbo** [comment]
@cmdcolin We just upgraded the 1kgenomes server to the protobuf version [here](https://github.com/ga4gh/server/releases/tag/0.3.1) As part of that effort we had to re-import all of the data. This changed all the hash ids so you may be running into a problem with trying to access a stale id. That is just a guess. If that is not your problem then please post the exact query you are making and we will have a look.

**Comment by cmdcolin** [comment]
@kozbo gotcha. I had some inkling that it might be related to this 500 error, but i'll recheck hash ids. thanks!

**Comment by kozbo** [comment]
We had a permissions issue on one of the directories holding the data. Added 777 permissions to the directory holding the gencode annotations file. Original error should be fixed. @cmdcolin Please open a new ticket if you are still getting a 404 error.
