### ISSUE TITLE
snake case required on featureSetId

### ISSUE THREAD

**Issue by alexanderDoria** [ga4gh/server#1276]
when searching for features, featureSetId is unavailable due to incorrect casing ([line 362](https://github.com/alexanderDoria/server/blob/master/ga4gh/client.py))

**Comment by kozbo** [comment]
@alexanderDoria - can you add a little more contextual information to this report? A link to the file and/or a code fragment will save time. In general, more information is better.

**Comment by alexanderDoria** [comment]
I'm working on it right now

**Comment by david4096** [comment]
Closed with #1278
