### ISSUE TITLE
Deprecate CLI client

### ISSUE THREAD

**Issue by david4096** [ga4gh/server#1286]
The CLI client doesn't offer much functionality other than, it works! I would argue for deprecating the CLI client to improve long term maintenance, since it doesn't offer any functionality to the rest of the server it could be moved to a separate module. If it is identified as a priority by the user base to provide a CLI client we can respond by adding methods there, but they should not be blocking for evaluating schema changes.

This change would move a number of issues not central to the server implementation or design to a separate repo, allowing maintenance risks to not be centralized in a single code base. This would move a number of the server issues to a new repository and allow more rapid development against this code base.

Some HTTP CLI client issues outstanding

https://github.com/ga4gh/server/issues/429
https://github.com/ga4gh/server/issues/1264
https://github.com/ga4gh/server/issues/875
https://github.com/ga4gh/server/issues/293

**Comment by diekhans** [comment]
Conceptually, yes, separate git modules makes sense.  However,
it's low-priority, as there are no other implementations to work
against.

If it's useful, it can stay where it is until the need is
demonstrated to split it out. It will still have to be
maintained no matter where it is in git.  If it's not useful, it
should just be deleted and forgotten, not moved to another
repository.

**Comment by jeromekelleher** [comment]
I disagree with this. The CLI client is a very useful development utility, and is the only simple way of running client commands against a server.  It is a central part of my development methodology, and I see no good reason to remove it.

I'm going to close this issue to avoid having it hanging around. Please reopen it if you think there is more to discuss @david4096.
