### ISSUE TITLE
WormtableVariantSet.getMetadata() should return VCF compatible values

### ISSUE THREAD

**Issue by jeromekelleher** [ga4gh/server#129]
In WormtableVariantSet.getMetadata() we return metadata information about the INFO and sample fields in a VariantSet. The spec does not specify the format of these fields (which is a bug), but without a better option, VCF compatibility seems like the best approach.

**Comment by macieksmuga** [comment]
I can take a shot at this.

**Comment by jeromekelleher** [comment]
This is low priority, since we are removing wormtable.
