### ISSUE TITLE
Search Variant annotations bug

### ISSUE THREAD

**Issue by david4096** [ga4gh/server#1294]
Thanks @Kusdhill!

> I found a bug in the **searchVariantAnnotations** function where duplicate transcript effects are returned.

<a href="https://gist.github.com/Kusdhill/770c2754687a29a199e4e4f44d8691d0" target="_blank">This code</a> gives the following output of ID's:

> c8222b12ee2dafeeaaba593cc44cb3c6
**cc90d63e3a5b7e14bc2954414b0cf649**
2824090d5107a819c2e29bbc823c09e5
d7179d31c57b5bcc59d34997447ab1b2
c8222b12ee2dafeeaaba593cc44cb3c6
**cc90d63e3a5b7e14bc2954414b0cf649**

As you can see in the output, the second and last ID are the same.

The issue can be found <a href="https://github.com/ga4gh/server/blob/master/ga4gh/backend.py#L302" target="_blank">here</a>. Extending the two lists adds duplicate entries into the new list which can be problematic.

**Comment by Kusdhill** [comment]
Here is my proposed fix:

`ann.transcript_effects.append(list(set(newTxE)-set(ann.transcript_effects)))`

I am open to cleaner solutions!
