### ISSUE TITLE
Installation instructions for OSX don't include build_test_data.py

### ISSUE THREAD

**Issue by dcolligan** [ga4gh/server#1295]
The installation instructions for OSX don't include the `build_test_data.py` step, so the tests fail when run.  This can be remedied in one of two ways:

1. Edit the installation instructions to include this step
2. Modify `run_tests.py` such that it checks for a `repo.db` before a test run, creating it if it does not exist

I prefer 2.

**Comment by diekhans** [comment]
The short the instructions, the better.

**Comment by dcolligan** [comment]
Fixed in #1296
