### ISSUE TITLE
Need to implement callsets/search method

### ISSUE THREAD

**Issue by jeromekelleher** [ga4gh/server#13]
We need to implement the `callsets/search` method. Currently, the concept of a `CallSet` does not exist; we just generate `Calls` and map  the  `callSetId` and `callSetName` (do we _really_ need both of these?) to the sample name in VCF.  Can we simply map `CallSet.id`, `CallSet.name` and `CallSet.sampleName` to the VCF sample name?

**Comment by dcolligan** [comment]
Fixed in #140
