### ISSUE TITLE
Client library needs logging/debug output

### ISSUE THREAD

**Issue by jeromekelleher** [ga4gh/server#130]
The client library currently does not have any facility for logging or debugging events that occur. We should include log prints for HTTP events at a minimum to allow us to debug network issues.

**Comment by diekhans** [comment]
FWIW, attached [we will see if github can handle attachments] is
code I use to parse command line for logging level and facility,
setup loggers to syslog or stderr.

General gripe is that python doesn't split up messages so that
they don't get truncated by syslog.

**Comment by dcolligan** [comment]
Doesn't look like GitHub supports anything but picture attachments

https://help.github.com/articles/issue-attachments/

Because we all know how useful uploading pictures of squirrels saying 'ship it' is vs txt uploads...

**Comment by dcolligan** [comment]
Ok, you can upload a txt file using gist but you need to drag-and-drop it into the UI

**Comment by diekhans** [comment]
ohhh modern technology
![adm3a](https://cloud.githubusercontent.com/assets/110053/6062972/a80e8fc8-ad08-11e4-89eb-9b11d421b8c4.jpg)

**Comment by dcolligan** [comment]
Fixed in #150
