### ISSUE TITLE
Nosetests opening too many files

### ISSUE THREAD

**Issue by dcolligan** [ga4gh/server#131]
Sometimes running the tests seems to run into system resource limits for open files, causing tests to fail.  Here are two sample runs that illustrate this problem, the first using `run_tests.py` and the second just executing `nosetests` directly:

https://gist.github.com/dcolligan/a8743d84a302529b161a
https://gist.github.com/dcolligan/bca0d356fb3ad367f235

The default open file limit on OSX Mavericks (my environment) is 256.  You can find out yours by using any of these commands:

```
launchctl limit maxfiles
python -c "import resource; print(resource.getrlimit(resource.RLIMIT_NOFILE))"
ulimit -n
```

I got around this by bumping up my resource limits: http://unix.stackexchange.com/questions/108174/how-to-persist-ulimit-settings-in-osx-mavericks

I'm not sure what is causing the open files count to explode.  We seem to close all subprocesses that we launch in the tests.  Maybe we are just opening a large amount of packages / test files.  Or maybe nosetests manages its file handling stupidly.  Not sure.

**Comment by jeromekelleher** [comment]
Interesting... can you try to wrap an strace around it please? I don't see any good reason for opening that many files.

**Comment by dcolligan** [comment]
OSX has dtruss, which is similar; here's a run of `sudo dtruss nosetests > dtruss.txt 2>&1` https://gist.githubusercontent.com/dcolligan/ccde9e6a0a3a941dca0b/raw/dtruss.txt

**Comment by jeromekelleher** [comment]
Hmmm, looks pretty normal to me  from our side. We seem to hit errors very early on in the process, so I'm guessing it's a problem particular to your setup. Install a Linux VM on your machine?

**Comment by dcolligan** [comment]
I'm happy to close this issue if no one else is having it.  I don't think nosetests is going to exceed a two-orders-of-magnitude increase in file limits anytime soon.

**Comment by diekhans** [comment]
Maybe a missing try/finally block with a close?  It seems very
odd that any of the tests I have looked at would open more than
a few files.

**Comment by jeromekelleher** [comment]
Nope, I'm wrong, it is a real problem. On my machine
```
strace nosetests 2>&1 | grep ^read | tail
```
shows that the last fd number is > 500, which is definitely wrong. We're missing a close somewhere...

**Comment by dcolligan** [comment]
Are you sure that indicates a problem?  Does the OS reuse file descriptors?  That is, if fd 1 is opened and then closed, will the next opened file be fd 1 or 2?  If the later, that would not seem to indicate a problem.  (Not sure of the answer myself, and could be OS-dependent... )

It seems like the errors are happening a lot around wormtable functionality.  Perhaps it's a bug in the library?

**Comment by dcolligan** [comment]
Just ran a little experiment which suggests that fds are indeed reused, so the fd number indicates the number of simultaneously open files for that process, which would indicate a problem: https://gist.github.com/dcolligan/15d946087b0c65949be0

**Comment by jeromekelleher** [comment]
Yeah, looks like a wormtable issue. Digging into it now...

**Comment by diekhans** [comment]
It reuses.  The limit is the current number that are actually open.  Worm table
maybe reopening database unnecessarily.  On linux, it's easy to see what is
open by stopping the program and looking in  /proc/<pid>/fd/

Not sure how on the mac, they have never implemented the /proc
pseudo file system.

**Comment by diekhans** [comment]
If it's easy to reproduce, I can help track this down the some day when I don't have
meeting hell..

**Comment by jeromekelleher** [comment]
OK, I've made a bit of progress on this. Basically we're not cleaning the backend up properly and we're leaking lots of file descriptors when we do the tests. I've added a quick cleanup method which reduced the maximum fd used from ~500 down to ~200. This is still too high, but acceptable. I'll look into it some more and see if I can track the leak down.

**Comment by miketwo** [comment]
I'm running into this problem too. Took an strace and graphed the file numbers as they show up in `read(###,...)` calls.  Stack trace is here: https://gist.github.com/miketwo/d13bed512ed680913f02#file-nose_output-txt
![image](https://cloud.githubusercontent.com/assets/1082033/6517507/a5c931ce-c350-11e4-9725-ae8efea4c8e3.png)

Hope this helps.

**Comment by dcolligan** [comment]
We're ripping out wormtable, and this seems like a wormtable bug, so it's doubtful anyone is going to spend time fixing it.  Closing.

**Comment by pgrosu** [comment]
I'm shedding a tear of nostalgia :)
