### ISSUE TITLE
RNA: implement search over all rnaQuantificationSets

### ISSUE THREAD

**Issue by dcolligan** [ga4gh/server#1314]
The `/rnaquantifications/search` endpoint, according to the schemas, is supposed to return all `RnaQuantification` objects in all `RnaQuantificationSet`s if the `SearchRnaQuantificationsRequest. rna_quantification_set_id` is empty.  Right now the server returns nothing in this case (see the `TODO` in `rnaQuantificationsGenerator` in `backend.py`).

We haven't implemented this pattern of iterating over multiple sets' objects anywhere else (in `/variants/search` we mandate a `variant_set_id` to be specified; we basically do the same thing in `/reads/search` with `read_group_ids`).

This seems like a bit of work to set up this new pattern, which should be generalizable to other objects where we face the same issue (e.g. reads).  What do we want to do in the mean time?  Options are:

1) Punt: insert an exception saying the server doesn't support it now and plan to implement it later
2) Change the schema so we don't have to implement this

@saupchurch @jeromekelleher

**Comment by saupchurch** [comment]
If the pattern hasn't been implemented in this way anywhere else then perhaps we should go with consistency in the API.  Since `/variants/search` and `reads/search` require their respective "container" ids to be specified, then `rnaquantifications/search` should do likewise.  I say go with option (2)

**Comment by jeromekelleher** [comment]
I definitely prefer option (2).

**Comment by dcolligan** [comment]
Fixed in #1315

**Comment by dcolligan** [comment]
And #676
