### ISSUE TITLE
Feature ID array in RNA SearchExpressionLevelsRequest

### ISSUE THREAD

**Issue by david4096** [ga4gh/server#1320]
When feature groups were removed we added in the ability to search expression levels using a list of feature IDs ([schema](https://github.com/ga4gh/schemas/blob/rna/src/main/proto/ga4gh/rna_quantification_service.proto#L136)). This feature would allow expression levels that match any of the requested feature_ids to be returned. @saupchurch @dcolligan

**Comment by saupchurch** [comment]
resoled in #1321
