### ISSUE TITLE
Add info to transcript effect record 

### ISSUE THREAD

**Issue by david4096** [ga4gh/server#1334]
To go with https://github.com/ga4gh/schemas/pull/648

**Comment by kozbo** [comment]
@david4096  #648 is merged. closing

**Comment by david4096** [comment]
Let's keep this open unless the feature is implemented in the server 👍

**Comment by andrewjesaitis** [comment]
Started working on this tonight.

**Comment by david4096** [comment]
Awesome!

I just started implementing an upgraded tag bad (info field to attributes). The field is added across the board but I haven't addressed the "other keys" in annotated VCFs yet. Take a look at https://github.com/ga4gh/server/pull/1521 . It's pretty painless to switch back and forth between the two. I think we're slowly converging toward a type reflection method that will work for read tags, VCF tags, and random metadata.

**Comment by david4096** [comment]
Closed with https://github.com/ga4gh/server/pull/1562
