### ISSUE TITLE
IndexError: No item with that key

### ISSUE THREAD

**Issue by Philip-Wu** [ga4gh/server#1360]
Hi there

I'm trying to set up my own instance of the ga4gh reference server following the instructions here:

http://ga4gh-reference-implementation.readthedocs.io/en/latest/demo.html

I tried to start up the server using the following command:

`(ga4gh-env) $ ga4gh_server`

But then i got the following errors:

`(ga4gh-env) [root@localhost philip]# ga4gh_server
Traceback (most recent call last):
  File "/home/philip/ga4gh-env/bin/ga4gh_server", line 11, in <module>
    sys.exit(server_main())
  File "/home/philip/ga4gh-env/lib/python2.7/site-packages/ga4gh/cli.py", line 144, in server_main
    parsedArgs.config_file, parsedArgs.config, parsedArgs.port)
  File "/home/philip/ga4gh-env/lib/python2.7/site-packages/ga4gh/frontend.py", line 243, in configure
    dataRepository.open(datarepo.MODE_READ)
  File "/home/philip/ga4gh-env/lib/python2.7/site-packages/ga4gh/datarepo.py", line 433, in open
    self.load()
  File "/home/philip/ga4gh-env/lib/python2.7/site-packages/ga4gh/datarepo.py", line 1318, in load
    self._readReadGroupTable(cursor)
  File "/home/philip/ga4gh-env/lib/python2.7/site-packages/ga4gh/datarepo.py", line 865, in _readReadGroupTable
    readGroup.populateFromRow(row)
  File "/home/philip/ga4gh-env/lib/python2.7/site-packages/ga4gh/datamodel/reads.py", line 751, in populateFromRow
    self._sampleName = row[b'sampleName']
IndexError: No item with that key
`
can anybody help me with this error?

Thanks

Phil

**Comment by hurchu** [comment]
I just had the same error. Any idea?

**Comment by kozbo** [comment]
@Philip-Wu @hurchu Which version of the code are you using?

**Comment by hurchu** [comment]
Hi Kevin,

I followed the doc step by step from here:
http://ga4gh-reference-implementation.readthedocs.io/en/latest/demo.html

I used the example data from the demo.

Thanks,

**Comment by kozbo** [comment]
Yes, I just reproduced the problem. It seems that our repo.db that is packaged with the demo code is out of step. Let me see if I can fix that.

**Comment by hurchu** [comment]
Thanks!

**Comment by kozbo** [comment]
OK, I created a new tar file for you [here](https://github.com/ga4gh/server/releases/download/data/ga4gh-example-data-v4.4-alpha.tar) This should get you working again. I am afraid I didn't get all the set names to be the same as before so some of the documentation will be a little different, but the test commands should work just fine. Mostly I wanted to get you something to keep you operational. I will not close this issue until I have an official repository release that works for the tip build.

Thanks @Philip-Wu and @hurchu for catching our oversight here :-)

**Comment by Philip-Wu** [comment]
Thanks for making the new data file, but i'm getting a different error. It appears that a directory path has been hardedcoded to **/Users/kosborn/Documents/dev/ga4gh-example-data/so-ex.obo**

The full stacktrace is below:

`(ga4gh-env) [philip@localhost ~]$ ga4gh_server
Traceback (most recent call last):
  File "/home/philip/ga4gh-env/bin/ga4gh_server", line 11, in <module>
    sys.exit(server_main())
  File "/home/philip/ga4gh-env/lib/python2.7/site-packages/ga4gh/cli.py", line 144, in server_main
    parsedArgs.config_file, parsedArgs.config, parsedArgs.port)
  File "/home/philip/ga4gh-env/lib/python2.7/site-packages/ga4gh/frontend.py", line 243, in configure
    dataRepository.open(datarepo.MODE_READ)
  File "/home/philip/ga4gh-env/lib/python2.7/site-packages/ga4gh/datarepo.py", line 433, in open
    self.load()
  File "/home/philip/ga4gh-env/lib/python2.7/site-packages/ga4gh/datarepo.py", line 1313, in load
    self._readOntologyTable(cursor)
  File "/home/philip/ga4gh-env/lib/python2.7/site-packages/ga4gh/datarepo.py", line 611, in _readOntologyTable
    ontology.populateFromRow(row)
  File "/home/philip/ga4gh-env/lib/python2.7/site-packages/ga4gh/datamodel/ontologies.py", line 82, in populateFromRow
    self._readFile()
  File "/home/philip/ga4gh-env/lib/python2.7/site-packages/ga4gh/datamodel/ontologies.py", line 50, in _readFile
    raise exceptions.FileOpenFailedException(self._dataUrl)
ga4gh.exceptions.FileOpenFailedException: Failed to open file '/Users/kosborn/Documents/dev/ga4gh-example-data/so-xp.obo'
`

I'd be happy to give it another go

Thanks

**Comment by Philip-Wu** [comment]
I copied the directory for ga4gh-example-data to the hardcoded directory /Users/kosborn/Documents/dev and reran the script and now I've finally got the server running.  However, you'll probably want to use a data file that isn't harded to kosborn's user directory when releasing the final version

Cheers

Phil

**Comment by kozbo** [comment]
Thanks @Philip-Wu yep, that is what I get for trying to rush something out on Friday evening :-) Nice work around. I will take another crack at creating the repo using relative paths, and with names consistent with the demo documentation. Thanks again for your help!

**Comment by kozbo** [comment]
OK, I think I have a clean set of demo files now. look [here](https://github.com/ga4gh/server/releases/tag/data) for the file ga4gh-example-data_4.4.tar

Test here looked good, let me know if they work for you as well @Philip-Wu and @hurchu

**Comment by Philip-Wu** [comment]
Thanks @kozbo 

The new data files did the trick! I can confirm that they're working

Cheers

**Comment by kozbo** [comment]
Great, thanks for testing!

**Comment by kozbo** [comment]
Note for future: used the following to create the new tar ball:
ga4gh_repo init ga4gh-example-data/repo.db
ga4gh_repo add-dataset ga4gh-example-data/repo.db 1kg-p3-subset 
ga4gh_repo add-referenceset ga4gh-example-data/repo.db -r ga4gh-example-data/GRCh37-subset.fa.gz --name GRCh37
ga4gh_repo add-ontology ga4gh-example-data/repo.db ga4gh-example-data/so-xp.obo -r -n so-xp
ga4gh_repo add-variantset ga4gh-example-data/repo.db 1kg-p3-subset ga4gh-example-data -r --name mvncall --referenceSetName GRCh37
ga4gh_repo add-readgroupset ga4gh-example-data/repo.db -n HG00096 -R GRCh37 1kg-p3-subset  ga4gh-example-data/HG00096.bam -r
ga4gh_repo add-readgroupset ga4gh-example-data/repo.db -n HG00533 -R GRCh37 1kg-p3-subset  ga4gh-example-data/HG00533.bam -r
ga4gh_repo add-readgroupset ga4gh-example-data/repo.db -n HG00534 -R GRCh37 1kg-p3-subset  ga4gh-example-data/HG00534.bam -r
