### ISSUE TITLE
ImportError: No module named flask

### ISSUE THREAD

**Issue by Philip-Wu** [ga4gh/server#1365]
Hi, 
This is most likely a configuration error on my part, but I'm not sure how to get around it.

I'm following the production installation setup guide found here:

http://ga4gh-reference-implementation.readthedocs.io/en/latest/installation.html#deployment-on-apache

I can get my apache instance running but when I go to visit the page

http://localhost/ga4gh

I get see the following error in my /var/log/httpd/error.log with the following message:

`[Mon Sep 05 04:39:10.058735 2016] [:error] [pid 28046] [remote 130.56.50.1:208] mod_wsgi (pid=28046): Target WSGI script '/srv/ga4gh/application.wsgi' cannot be loaded as Python module.
[Mon Sep 05 04:39:10.058811 2016] [:error] [pid 28046] [remote 130.56.50.1:208] mod_wsgi (pid=28046): Exception occurred processing WSGI script '/srv/ga4gh/application.wsgi'.
[Mon Sep 05 04:39:10.058847 2016] [:error] [pid 28046] [remote 130.56.50.1:208] Traceback (most recent call last):
[Mon Sep 05 04:39:10.058877 2016] [:error] [pid 28046] [remote 130.56.50.1:208]   File "/srv/ga4gh/application.wsgi", line 1, in <module>
[Mon Sep 05 04:39:10.059001 2016] [:error] [pid 28046] [remote 130.56.50.1:208]     from ga4gh.frontend import app as application
[Mon Sep 05 04:39:10.059023 2016] [:error] [pid 28046] [remote 130.56.50.1:208]   File "/srv/ga4gh/ga4gh-server-env/lib/python2.7/site-packages/ga4gh/frontend.py", line 16, in <module>
[Mon Sep 05 04:39:10.059347 2016] [:error] [pid 28046] [remote 130.56.50.1:208]     import flask
[Mon Sep 05 04:39:10.059390 2016] [:error] [pid 28046] [remote 130.56.50.1:208] ImportError: No module named flask

Any ideas?

Thanks`

**Comment by Philip-Wu** [comment]
I managed to resolve the error by running these commands:

`yum install python-flask
source ga4gh-server-env/bin/activate
pip install flask
pip install flask-cors
pip install humanize
pip install oic
pip install google.protobuf.json_format
pip install protobuf
pip install pysam
`

**Comment by kozbo** [comment]
@Philip-Wu It is possible that Apache is not using your virtualenv when running the ga4gh server, and thus it cannot find the packages that got installed as part of your pip install ga4gh operation. Installing the missing packages into the base environment is one way to work around this problem.

To configure Apache to point to your virtualenv add the following to the WSGIDaemonProcess command:
'python-path=/srv/ga4gh/<virtualenv name>/lib/python2.7/site-packages'
to the file
'/etc/apache2/sites-available/000-default.conf'
