### ISSUE TITLE
Fix testSearchFeatures in test_client_json.py

### ISSUE THREAD

**Issue by dcolligan** [ga4gh/server#1375]
In #1370 I harmonized the pagination logic of features with the rest of the code base.  This fixed `testSearchFeatures` in `tests/end_to_end/test_client_json.py`.  However, rebasing it on top of the G2P changes re-broke the test.  @bwalsh , could you figure out why the test is failing (it is currently skipped now, of course)?

**Comment by bwalsh** [comment]
@dcolligan  this should fix it.

**Comment by dcolligan** [comment]
The test fix part looks good (I suspected it was something to do with ordering).  Someone else will have to comment on the version bump.  Usually it's good to make a PR for each logically distinct issue.

**Comment by dcolligan** [comment]
Fixed in #1376
