### ISSUE TITLE
Replace process schemas

### ISSUE THREAD

**Issue by david4096** [ga4gh/server#1417]
Process schemas wraps the `protoc` call that generates the python bindings from schemas. The recent additions of API annotations caused this process to break. I suggest we remove process schemas and publish the compiled protoc classes as part of ga4gh schemas with all of the proto in it's own module that can be imported. In the meantime it should be possible to manually import the generated proto. @dcolligan

**Comment by dcolligan** [comment]
Yes, I suggest we make packaging the schemas a priority.

These branches may be of use in the interim:
https://github.com/dcolligan/schemas/tree/elgoog
https://github.com/dcolligan/schemas/tree/elgoog_ga4gh_client

**Comment by dcolligan** [comment]
Fixed: https://github.com/dcolligan/ga4gh-schemas/blob/master/scripts/process_schemas.py
