### ISSUE TITLE
Skip featureId lookup optionally

### ISSUE THREAD

**Issue by david4096** [ga4gh/server#1436]
When adding an RNA quantification to an RNA quantification set, the ReadGroupSet and FeatureSet arguments should be optional via a flag.

**Comment by david4096** [comment]
@saupchurch Can you take one more quick pass and add this in the RNA input process before we release?

**Comment by saupchurch** [comment]
@david4096 could you please clarify this? Those already appear to be optional (see `repomanager.py` lines 962-965)

**Comment by david4096** [comment]
@saupchurch Thanks you're right! The problem I'm facing now is making the looking up of `featureIds` optional. If no `featureSetName` is specified can we skip that code path?

**Comment by saupchurch** [comment]
yes, if no `featureSetName` are specified then there is no lookup.

**Comment by david4096** [comment]
`python repo_dev.py add-rnaquantification ga4gh-example-data/rnaseq.db ../compliance/test-data/rna_brca1.tsv rsem ga4gh-example-data/registry.db brca1 -n stuff` without a feature set name still seems to populate the feature IDs since it only checks whether a dataset is presence during loading.

```
sqlite3 ga4gh-example-data/rnaseq.db
select * from Expression;
```

The feature IDs are all set for me. The problem is that for loading multiple files, this process is slow and cumbersome. I'm hoping by circumventing it at data loading time we can come up with a faster solution afterwards using straight SQL.

**Comment by saupchurch** [comment]
right you are - digging deeper shows that writing the expression itself goes directly to the `dataset`.  This is very wrong as it should respect the `featureSetName`s passed in.  I'll fix this.  Also, some of the slowdown is coming from a very small `batchSize`
