### ISSUE TITLE
Documentation gives URL for old example data package

### ISSUE THREAD

**Issue by thomasd-gen** [ga4gh/server#1438]
We've been trying to work through the installation instructions [here](http://ga4gh-reference-implementation.readthedocs.io/en/stable/installation.html) and run into a problem with the repo.db database in version 4.3 of the data package.  It seems that this has been seen before (e.g. #1372) and can be fixed by using version 4.5 of the data package -- would it be possible to update the documentation?

**Comment by david4096** [comment]
Yes, thanks for pointing this out!
