### ISSUE TITLE
Authenticated API access through key

### ISSUE THREAD

**Issue by Welliton309** [ga4gh/server#1452]
I would like to know if I can configure GA4GH server to accept only authenticated requests through one or more keys. I tested the [OpenID Connect Providers tutorial](http://ga4gh-reference-implementation.readthedocs.io/en/latest/configuration.html#openid-connect-providers) but it is not exactly what I want because I understood that anyone who have a Google account will be able to access the API. Is there another method for adding authentication to GA4GH API?

I also tested https://github.com/ga4gh/server/tree/master/oidc-provider but it raises the following error:

```
Traceback (most recent call last):
  File "src/run.py", line 1, in <module>
    from provider.server.server import main
  File "/home/welliton/GA4GH/server/oidc-provider/simple_op/src/provider/server/server.py", line 16, in <module>
    from cherrypy.wsgiserver.wsgiserver2 import WSGIPathInfoDispatcher
ImportError: No module named wsgiserver2
```

**Comment by david4096** [comment]
@Welliton309 thanks we are slated to simplify the authentication process and I have demonstrated using auth0 for generating API keys [here](https://github.com/david4096/server-1/tree/auth0).

**Comment by Welliton309** [comment]
Thank you @david4096. Can you point which document that explains the authentication using Auth0? I didn't find this demonstration in your repository.

**Comment by david4096** [comment]
@Welliton309 the link I provided above is to a tree where it had been partially implemented. I have not documented this effort. I've definitely struggled with the auth offering currently in the server. I believe in the short-term we'll provide the current OIDC method alongside Auth0. I'll close this issue once I'm confident we have an easy to use auth workflow.

**Comment by david4096** [comment]
@Welliton309 I added a PR that you should be able to use to perform authentication and authorization. https://github.com/ga4gh/server/pull/1470
