### ISSUE TITLE
Delete unused scripts

### ISSUE THREAD

**Issue by david4096** [ga4gh/server#1453]
https://github.com/ga4gh/server/blob/master/scripts/generate_fasta.py

Generates random FASTA files

https://github.com/ga4gh/server/blob/master/scripts/split_fasta.py

Was added as part of our ETL process on FASTA before better pysam support.

Remove `update_data.py` will close https://github.com/ga4gh/server/issues/1291

**Comment by dcolligan** [comment]
+1
