### ISSUE TITLE
Clarify STYLE.md style in wake of hierarchical namespace changes

### ISSUE THREAD

**Issue by dcolligan** [ga4gh/server#1455]
The file could probably use some sprucing up to clarify how we want to order imports, etc.

**Comment by david4096** [comment]
I prefer `from ga4gh.schemas import protocol` or `from ga4gh.client import client` over `import ga4gh.client.client as client`.

**Comment by dcolligan** [comment]
Let's try and keep the styles we've been using so far unless there is a compelling reason to do otherwise.  I mostly opened this issue to clarify how to order imports from other ga4gh repositories.

**Comment by dcolligan** [comment]
Fixed in #1581
