### ISSUE TITLE
master is screwed up

### ISSUE THREAD

**Issue by dcolligan** [ga4gh/server#146]
It looks like someone force pushed to master and we lost two weeks worth of commits (it may have been me; not sure)... of course, thanks to git, this is a recoverable situation.  Is there any way to view the reflog through the github UI?  If not, whoever has a most recent copy of the branch should force push it to master.

**Comment by dcolligan** [comment]
I guess a "reflog" substitute is going through one's email and checking for the last merge notification that GitHub sent out.

I think the most recent commit was this one: https://github.com/dcolligan/server/commit/974c1fff197f5e2a8c90c2a2393eb6bbc9e26fd7

In these kinds of situations, should we get a consensus around which commit to restore master to, or should someone just do it since the longer master is borked the more everyone else is screwed up?

**Comment by dcolligan** [comment]
Also, after this is resolved, an admin should enable this option, if we have this edition of GitHub: https://help.github.com/enterprise/11.10.340/admin/articles/blocking-force-pushes-to-a-repository/

**Comment by dcolligan** [comment]
Another way of resolving this without resorting to the command line would be merging a PR that was going to get merged anyway and which is rebased off of the most recent version of the (real) master... for instance: https://github.com/ga4gh/server/pull/145

**Comment by dcolligan** [comment]
(FYI, here is how one could find who force pushed in the future, but it sounds like it takes some external server so I don't propose we do it, and hopefully we can enable the no-force-pushes github flag anyways: http://stackoverflow.com/questions/17503226/find-committer-of-a-force-push-on-github )

**Comment by dcolligan** [comment]
Thinking about it a bit more, the merging-a-PR strategy would modify the commit history, since the merge commit's parents would be the tip of the PR and then the tip of the current master, so I would instead advocate the force pushing from the command line strategy.  (Someone who had not fetched between the time master was screwed up and when master was fixed would not notice any problems as far as their history was concerned in the force push from command line case.)

**Comment by diekhans** [comment]
goes the git help message tell one to use -f??? ;-)

**Comment by jeromekelleher** [comment]
I've had a go at fixing it up with a force push, and it's even more screwed up now. I'll try again in a bit and report back here if there's any progress.

**Comment by jeromekelleher** [comment]
This should be fixed now. Could everybody have a quick look over the commit history and make sure they are happy we haven't done anything weird please? I'll close the issue once we've signed off on the reinstated upstream/master.

Thanks for the report and background work @dcolligan.

**Comment by dcolligan** [comment]
Okay, master should be reset to what it was before the original force push.
