### ISSUE TITLE
generate_schemas poorly named

### ISSUE THREAD

**Issue by diekhans** [ga4gh/server#147]
because it doesn't generate schemas, it generates code from them ;)

**Comment by fnothaft** [comment]
Strictly speaking, it generates a JSON schema from the AVDL description, which is then used to generate code. I think the name is OK.

**Comment by diekhans** [comment]
Hmm, input is a AVDL schema output is code, JSON schema is a
side effect.  It confused someone here Not a high priority, we
are easily confused.

Any why do bioinformatics people insist on telling me what
programming language a program is writing in (foo.py, baz.pl)
and not what it does?  Dennis Ritchie must be rolling in his
grave ;-) [sorry, pet peeve]

**Comment by jeromekelleher** [comment]
Fair enough, `process_schemas.py` or something would probably be a better name. Re the extension, this is a script written for local development purposes, and is never intended to be an installed executable (installed executables are treated in an entirely different way --- see cli.py and setup.py). 

Feel free to open a PR with a name change...

**Comment by dcolligan** [comment]
Fixed in #148
