### ISSUE TITLE
Documentation: `ga4gh.server.frontend` -> `ga4gh.frontend` in installation WSGI application file?

### ISSUE THREAD

**Issue by ljdursi** [ga4gh/server#1475]
I think this:
```
from ga4gh.server.frontend import app as application
import ga4gh.server.frontend as frontend
frontend.configure("/srv/ga4gh/config.py")
```
should now be:
```
from ga4gh.frontend import app as application
import ga4gh.frontend as frontend
frontend.configure("/srv/ga4gh/config.py")
```

**Comment by david4096** [comment]
@ljdursi Did you run into a problem using the application.wsgi provided? Could you provide any errors you're seeing?

You can see the import we are currently using to get at the frontend module [here](https://github.com/ga4gh/server/blob/master/ga4gh/server/cli/server.py#L11). If you're seeing an issue, this may have to do with having multiple `ga4gh` packages in your current environment. Thanks for pointing this out the next release will be changing some import statements, however, I believe this one is OK.

https://github.com/ga4gh/server/blob/master/ga4gh/server/frontend.py

**Comment by ljdursi** [comment]
Yup, the error was
```
mod_wsgi (pid=16884, process='ga4gh', application=''): Loading WSGI script '/srv/ga4gh/application_1.wsgi'.
mod_wsgi (pid=16884): Target WSGI script '/srv/ga4gh/application_1.wsgi' cannot be loaded as Python module.
mod_wsgi (pid=16884): Exception occurred processing WSGI script '/srv/ga4gh/application_1.wsgi'.
Traceback (most recent call last):
   File "/srv/ga4gh/application_1.wsgi", line 1, in <module>
    from ga4gh.server.frontend import app as application
ImportError: No module named server.frontend
AH00491: caught SIGTERM, shutting down
```

Making the switch as above fixed it.

`pip install ga4gh` in a new VM shows the same sort of behaviour from the REPL:

```
vagrant@minimal-xenial:~$ python
Python 2.7.12 (default, Nov 19 2016, 06:48:10)
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import ga4gh
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named ga4gh
>>>
vagrant@minimal-xenial:~$ sudo pip install ga4gh
# ...[ stuff happens ]
vagrant@minimal-xenial:~$ python
Python 2.7.12 (default, Nov 19 2016, 06:48:10)
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import ga4gh
>>> import ga4gh.server
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named server
>>> import ga4gh.frontend
INFO:rdflib:RDFLib Version: 4.2.1
```

**Comment by david4096** [comment]
Thanks @ljdursi ! I think the problem might be that you're working with a released version when the documentation is in regards to the version awaiting release. If you take a look at the `stable` docs [here](http://ga4gh-reference-implementation.readthedocs.io/en/stable/installation.html) the old syntax should be there. We could do a better job of pointing to which version of the documentation you are viewing.

Let me know if this helps. After the next release we'll check this issue to be sure your problem is handled.

**Comment by ljdursi** [comment]
Shoot, sorry.  Thanks.
