### ISSUE TITLE
Running the demo: "ga4gh-example-data/registry.db' does not exist"

### ISSUE THREAD

**Issue by jordeu** [ga4gh/server#1477]
Following the demo instructions [here](http://ga4gh-reference-implementation.readthedocs.io/en/latest/demo.html) I get this error:

    ga4gh.exceptions.RepoNotFoundException: Database file 'ga4gh-example-data/registry.db' 
    does not exist.  Either change the configuration to point to a valid file or create one 
    using the repo manager.`

I've checked and the "registry.db" is missing in the tar file. Do I have to create it first? How?

Thanks.

**Comment by david4096** [comment]
Thanks! We haven't yet updated the example data for the development branch!

You can generate the example data the same way we do using `python scripts/download_example_data.py ga4gh-example-data`.

I'll close this once the example data is updated!
