### ISSUE TITLE
API server returns string type to all attributes

### ISSUE THREAD

**Issue by Welliton309** [ga4gh/server#1478]
I am testing GA4GH API server and I observed that the server returns `string` type (quoted values) for all attributes, even for attributes that the schemas documentation says other type. For example the attributes `start` and `end` should be `long` ([reference](https://ga4gh-schemas.readthedocs.io/en/latest/schemas/variants.proto.html#protobuf.Variant)) but in the JSON these values are represented as string.

``` bash
ga4gh_client variants-search http://1kgenomes.ga4gh.org/ --variantSetId WyIxa2dlbm9tZXMiLCJ2cyIsInBoYXNlMy1yZWxlYXNlIl0 -r 1 -s 15902 -e 15903 -O json | jq .
```

``` json
{
  "id": "WyIxa2dlbm9tZXMiLCJ2cyIsInBoYXNlMy1yZWxlYXNlIiwiMSIsIjE1OTAyIiwiNWIzYjk4MzNmYmZiMGM0NzVlMGNhMTVlOTU5YTUwNWIiXQ",
  "referenceName": "1",
  "alternateBases": [
    "GC"
  ],
  "names": [
    "rs557514207"
  ],
  "info": {
    "DP": [
      "7012"
    ],
    "EX_TARGET": [
      "True"
    ],
    "NS": [
      "2504"
    ],
    "EAS_AF": [
      "0.868099987507"
    ],
    "VT": [
      "INDEL"
    ],
    "EUR_AF": [
      "0.465200006962"
    ],
    "SAS_AF": [
      "0.532700002193"
    ],
    "AC": [
      "2209"
    ],
    "AA": [
      "ccc|CC|CCC|deletion"
    ],
    "AF": [
      "0.441094011068"
    ],
    "AFR_AF": [
      "0.0430999994278"
    ],
    "AMR_AF": [
      "0.414999991655"
    ],
    "AN": [
      "5008"
    ]
  },
  "variantSetId": "WyIxa2dlbm9tZXMiLCJ2cyIsInBoYXNlMy1yZWxlYXNlIl0",
  "end": "15903",
  "calls": [],
  "created": "0",
  "updated": "0",
  "referenceBases": "G",
  "start": "15902"
}
```

Is this correct? Should the client applications parse the JSON? I also expected that INFO values should be integer or float (i.g. `DP` and `AFR_AF`) because these attributes are unpredictable (may or may not have in VCF file).

**Comment by david4096** [comment]
JavaScript [Number](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number) (2^53-1) is unreliable for large integers, so the protobuf serialization to JSON encodes them as strings. That is why the start and end have been encoded that way. You can read more discussion [here](https://github.com/ga4gh/schemas/pull/547).

On the info items, I believe the reference server could do a better job representing their types as the ListValue makes it possible to describe doubles, for example.

So we won't be changing the start/end coordinates from strings to numbers, but we can close this issue with code that infers the type of a metadata entry and then appends it to the info field with the correct protobuf type description.

Does that make sense @Welliton309 ? The JSON representation gains some complexity with this change, but will be more correct and make better use of the data model.

**Comment by Welliton309** [comment]
Thank you @david4096 for the explanation. Now I understand why start/end attributes should be string values and I agree with that. It would be very helpful if the server returns the info items with their correct data type.
