### ISSUE TITLE
running process_schemas.py creates diff in generated file

### ISSUE THREAD

**Issue by dcolligan** [ga4gh/server#165]
The generated file that is the result of running `process_schemas.py` is not predictable.  It should be written out the exact same, every time.

There is an existing issue open for the non-stable order of the postMethods, #116 .  This bug is for non-postMethods write consistency.

This gist is the diff resulting from a run of `process_schemas.py` on the latest master: https://gist.github.com/dcolligan/db8d3b24dc821fd23d8f

**Comment by Naburimannu** [comment]
Let's land @mollyzhang's textwrap change, once that's got its indentation
and wrap width correct? Some of the differences look to be instability from
wrapping which will be changed by her work.

**Comment by dcolligan** [comment]
Right, solving #164 and #116 may resolve this issue.

**Comment by dcolligan** [comment]
Okay, now that @MollyZhang has closed the two above issues, do we think we can close this one?  @jeromekelleher 

I vote for yes, until we see any difference pop up.

**Comment by Naburimannu** [comment]
Agree with @dcolligan.

**Comment by jeromekelleher** [comment]
Agreed.
