### ISSUE TITLE
Client logging should go to stdout

### ISSUE THREAD

**Issue by jeromekelleher** [ga4gh/server#168]
Currently extra client logging info goes to stderr.  This is set in the `client.HttpClient` class. This would be more useful if it was sent to stdout.

**Comment by diekhans** [comment]
-1 ;-)

With Unix commands, verbose tracing is sent to stderr.  This
keeps stdout free for output of date.

Why would it be more useful to go stdout?

With python logging, I usually have an option to send the logging
to a file.

**Comment by jeromekelleher** [comment]
Basically because I want to see the JSON going between the client and the server (using -vv), and I can never remember the arcane bash needed to redirect stderr to stdout. I'll get over it if others are strongly against this though.

**Comment by dcolligan** [comment]
I'm also -1.

If you want stdout and stderr separate, you can do:
```
python scripts/google_examples.py > out.txt 2> err.txt
```
If you want them combined, you can do:
```
python scripts/google_examples.py > out.txt 2>&1
```

The `2` always represents stderr.  The `>&` is the redirection operator.  (Of course, things are more complicated than that, but that's how I think about it.)

**Comment by diekhans** [comment]
:-)

2>&1

1 == stdout file number
2 == stderr file number

>& redirect bases on file numbers

2>&1 redirects stderr to stdout

**Comment by jeromekelleher** [comment]
Like I said: arcane! Maybe this will give me the motivation I need to learn...
