### ISSUE TITLE
Better test data required

### ISSUE THREAD

**Issue by jeromekelleher** [ga4gh/server#173]
Currently our test data is limited to a handful of small and synthetic VCFs (see https://github.com/ga4gh/server/tree/master/tests/data). We need a wide spread of test data to exercise our APIs, across variants, reads and references. We should have a collection typical small data files spanning many anticipated use cases.

**Comment by dcolligan** [comment]
This issue is too general.  Can you try and narrow the scope a bit?

**Comment by jeromekelleher** [comment]
OK, fair enough. We need the following to close this issue:

1. Test reference data;
2. Test read data;
3. More test VCF data, covering different format versions, numbers of samples, ploidy levels, etc. How much more depends on how much we think it's worth covering exotic corner cases.

I'm not really informed enough to know what would be considered a representative spread of examples, so it would be good to get some wider opinions here. Anyone like to weigh in here?

**Comment by pgrosu** [comment]
@jeromekelleher, I think you gave a great suggestion a while back in using the Illumina's Platinum Genomes dataset:

https://github.com/ga4gh/compliance/issues/13#issuecomment-59219513

~p

**Comment by shajoezhu** [comment]
missing a test example such that has a variant site, where for the INFO and FORMAT field, NUMBER=R. 

For details, see http://samtools.github.io/hts-specs/VCFv4.2.pdf, section 1.2.2 and 1.2.4

**Comment by shajoezhu** [comment]
NUMBER=R is new for vcf4.2, a related entry is found on http://sourceforge.net/p/samtools/mailman/message/32900784/

**Comment by jeromekelleher** [comment]
Test data has been greatly improved since this issue.
