### ISSUE TITLE
Developers need to update `ga4gh-example-data`

### ISSUE THREAD

**Issue by jeromekelleher** [ga4gh/server#178]
Since #171 was merged, the required structure of the `dataDir` has changed. The simplest solution is to re-download the tarball from  http://www.well.ox.ac.uk/~jk/ga4gh-example-data.tar.gz

**Comment by dcolligan** [comment]
Not sure if this is really an "issue" that can be resolved, but I appreciate that there may not be a better way to message all the developers... should we close this?

**Comment by jeromekelleher** [comment]
Just seemed like the simplest way to update people --- if they we having problems they might check the issue list and see this. Let's leave it open for a few days and close it then.

**Comment by pgrosu** [comment]
@jeromekelleher, if you could add a md5sum file (i.e. `ga4gh-example-data.md5sum`) that was generated on compressed file, then when the server is started a function can be used compare the local md5sum against the one from the ftp site for any changes.  If there are any changes then the updated datasets will be downloaded automatically.

Thanks,
Paul

**Comment by dcolligan** [comment]
(if we're going to do that it might be worth discussing what hash algorithm to use)

**Comment by jeromekelleher** [comment]
This isn't worth writing code into the server for. It's just example data, and the format will change a couple of more times over the next few months.

**Comment by dcolligan** [comment]
People shouldn't update their example data folder until #181 is resolved

**Comment by dcolligan** [comment]
Nevermind, false alarm.

**Comment by dcolligan** [comment]
You know, it might be worthwhile to have a script like `scripts/update_data.py` that a dev can run and get the most recent version of the data initialized (in this case, it would download and extract the archive, and either delete the previous data -- if it exists -- or put it in a known location).  Thoughts?

**Comment by pgrosu** [comment]
+1, absolutely.  As more people join this project, the default should be assumed that everyone is in sync and works from the same datasets.

**Comment by dcolligan** [comment]
Alright, people should have this by now (and if they don't, they can run `scripts/update_data.py`).

**Comment by pgrosu** [comment]
+1, Many thanks @dcolligan! :)
