### ISSUE TITLE
Server should determine variant file handler type automatically

### ISSUE THREAD

**Issue by jeromekelleher** [ga4gh/server#186]
At the moment, the server CLI takes an argument telling it what type of VariantSet to allocate. This is a poor design choice, and makes it difficult to try out new data. A simpler option would be to dynamically decide what type of VariantSet to allocate at run time. One possible outline would be

- Remove the variantSetClass from the `backend.Backend()` constructor, and call `variants.variantSetFactory(variantSetId, relativePath)` to construct the variantSet.
- Update the CLI to remove the redundant positional arg.
- In `variantSetFactory` we do a simple name based check: if the directory ends with ".wt" we allocate a `WormtableVariantSet` if not allocate a `TabixVariantSet`. (This will require us to update our example data.)

**Comment by pgrosu** [comment]
+1, I'm always in favor of having the code adapt to the data :)

**Comment by dcolligan** [comment]
@jeromekelleher can you update the directory structure in the example data to have this '.wt' convention?  I'm not exactly sure which level of the directory hierarchy you want it at.

**Comment by jeromekelleher** [comment]
@dcolligan - done. I've also added the same data in tabix indexed VCF form, which should make it easy to compare the two approaches.

**Comment by dcolligan** [comment]
Fixed in #204
