### ISSUE TITLE
Data-updating dev script

### ISSUE THREAD

**Issue by dcolligan** [ga4gh/server#189]
Provide a script that, when run, correctly initializes the database.

**Comment by jeromekelleher** [comment]
This is a bit vague @dcolligan --- we're just talking about the example data for development here, right?

I'm definitely +1 on the idea though.

**Comment by pgrosu** [comment]
This is basically this:

https://github.com/ga4gh/server/issues/178#issuecomment-75970882

with the need to ensure things start from a clean environment.

And definitely +1.  If the data gets into the terabytes then we might need another solution, but for now we definitely want people to focus on the API more than worrying about having all the proper data/clean environment which should happen in the background - and this will basically solve it.

**Comment by dcolligan** [comment]
Closed in #190
