### ISSUE TITLE
README is incorrect about Python versions

### ISSUE THREAD

**Issue by jeromekelleher** [ga4gh/server#191]
The README states that we fully support Python 2 and 3. This is incorrect, as we are currently supporting Python 2.7 only. We plan to support Python 3 in the future, but we're primarily held back from this by upstream libraries.

**Comment by macieksmuga** [comment]
I resolved this in PR 185.

**Comment by dcolligan** [comment]
@macieksmuga typically we don't write that until the PR has been merged

Also, you can use GitHub's syntax to link the PR like so: #185
