### ISSUE TITLE
Avro integration

### ISSUE THREAD

**Issue by dcolligan** [ga4gh/server#207]
Modify the client and server so that they are optionally able to use the Avro binary protocol to communicate.

**Comment by IanRogers-LShift** [comment]
This is superceded by https://github.com/ga4gh/schemas/pull/485 I guess (convert server to use Protocol Buffers)?

PB can also generate a binary format. We need to agree the http accepts mime types to trigger the negotiation though. See http://stackoverflow.com/questions/30505408/what-is-the-correct-protobuf-content-type

I'd suggest:
- "application/json" forces json
- "application/octet-stream" or "application/x-protobuf" (deprecated) to force binary

default to json if there's no header?

Related to https://github.com/ga4gh/server/issues/526

**Comment by jeromekelleher** [comment]
Yes, I think we can close this issue for clarity.

ps. See https://github.com/ga4gh/schemas/pull/431  for previous discussion on the mimetype.
