### ISSUE TITLE
Removing wormtable dependency

### ISSUE THREAD

**Issue by jeromekelleher** [ga4gh/server#210]
This is a meta-issue collecting the steps we need to take to remove the wormtable dependency. Some of these may be turned into several separate issues, if they turn out to be sufficiently complex.

~~1. Merge #194 and #208, and start building data driven tests for the HtslibVariantSet. Once we are satisfied that it works well, remove the existing TabixVariantSet, and update the `variantSetFactory`.~~
~~2. Perform some performance analysis on the WormtableVariantSet and the HtslibVariantSet using the ga4gh-example-data. This now contains VCF versions of 1000g_2011 and 1000g_2013 variant sets, so we'll want to get some basic throughput stats on (a) wormtable; (b) plain VCF; and (c) BCF. If performance of the htslib backend is similar to or better than the wormtable backend, then we are free to continue with ripping out wormtable. ~~
~~3. Replace the Wormtable test fixture in tests/test_backends.py with other tests. Too much is currently tested in one place here. We should put the majority of the tests of variant sets (including data consistency and search semantics tests) into datadriven/test_variants.py. These should be fairly straight forward to convert. Paging and other issues handled exclusively by the backend module should be tested in unit/test_backends.py, perhaps using a simulated backend (see #202).~~
~~4. Replace other dependencies on the WormtableTestFixture in the testing infrastructure with a simulated backend.~~
5. Update documentation, example data, and all the rest to fully purge wormtable from the source.

**Comment by dcolligan** [comment]
Is there anything preventing us from removing Tabix now?

**Comment by jeromekelleher** [comment]
No, I don't hink so. HtslibVariantSet already has better support I think. Feel free to nuke it.

**Comment by macieksmuga** [comment]
@jeromekelleher looks like the biggies - 1,2 and 3 of your original list are taken care of. Can I take this one and yank out wormtable now?

**Comment by jeromekelleher** [comment]
Yeah, go for it!

**Comment by dcolligan** [comment]
Looks like number 5 / #298 is the only thing left to do here.

PS I find it hilarious that GitHub allows one to edit other people's comments.

**Comment by dcolligan** [comment]
Fixed in 7ed8f1d3202b23c704bff03819bc009f781b4ec4
