### ISSUE TITLE
A compliance tester would be useful

### ISSUE THREAD

**Issue by jeromekelleher** [ga4gh/server#22]
The compliance test suite (https://github.com/ga4gh/compliance) is extremely useful, but does not allow for easily automating the process of API compliance testing. Checking for API compliance is a minimal requirement of our test suite, so we will need to do these checks in any case. Since having a command line application to test an arbitrary API endpoint is a useful additional tool to have, we may as well wrap this in with the suite of applications we are developing as part of the reference implementation.

Here are some ideas for how we might proceed:

- Create a new module called `ga4gh.compliance` and put the compliance testing code in here. This should make calls to the endpoints using the `ga4gh.client` module, and test the form of the responses. This should be done in as automated a manner as possible using the information encoded in the Avro schemas (see issue #19 for discussion on this point).
- Create a new CLI to run this compliance test against an arbitrary endpoint.
- Include calls to the compliance code in the test suite.

**Comment by dcolligan** [comment]
@diekhans was wondering if we're still attached to doing these in javascript (or node.js?) or if we want to create python scripts for them... thoughts?

**Comment by diekhans** [comment]
Does anyone know why JS was chosen to develop the compliance suite?   Having the suite run in a web browser seems to be an unimportant goal.

**Comment by sarahhunt** [comment]
I think the original idea was to be able to show how compliant the available implementations were during the initial stages of the project. Cassie had the test suite running from her github repository (http://cassiedoll.github.io/compliance-staging.html). Automated tests and a different way to list available servers make sense going forward.

**Comment by diekhans** [comment]
Hi Sarah,

Does it make sense to continue to develop the compliance tests
in javascript?  We would need to make it run under node.js and
I don't know how easy this is to integrate into continuous integration
system.

Running in a web browser seems like a very unimportant compared
to having a the right environment.

Mark

**Comment by jeromekelleher** [comment]
I think it's probably a good thing to have independent compliance testing systems. There is definitely a role for the web-based tester that @cassiedoll has developed. I don't think it's a huge amount of work to develop a compliance tester here. We have all of the end points, the types and default values from the Avro definitions. We can use our built in Avro validation to check the returned objects conform to the spec. 

I don't think we should check against a known dataset like the existing tester. We just pull some data down and check that it conforms to the schema, which we can do well because of the automated schema processing infrastructure. The JS tester assumes NA12878 is available, so it can do different tests. The different approaches are then complementary, I think.

**Comment by diekhans** [comment]
+100 to developing separate compliance tests as a part of the
server.

A serious compliance tests need to go hand in hand with the
reference implementation.  They are vital for the evolution
of the API.  Really, every PR should include changes to the
complacence tests.

**Comment by benedictpaten** [comment]
In the compliance suite it would be good to have some *very* limited performance testing - so in addition to testing that the functions work as designed - some timing information could be returned in the report. Alternatively this could be broken out separately, but for now it is probably pragmatic to do both in the same set. 

There was some discussion here at UCSC about the performance requirements an endpoint would need for it to be practical for interactive use. I propose that such a test be added in this suite.

**Comment by jeromekelleher** [comment]
Performance monitoring can be included easily, and should be part of the basic functionality.

**Comment by jeromekelleher** [comment]
Closing this, as the (very sophisticated) compliance tester is now based in its own repo.
