### ISSUE TITLE
HtslibVariantSet should support metadata.

### ISSUE THREAD

**Issue by jeromekelleher** [ga4gh/server#220]
The `getMetadata` method in HtslibVariantSet has not been implemented. This should be filled out with all available information, as indicated in the comments. This can use the definition in WormtableVariantSet as a model.

The results of this should be tested in `tests/datadriven/test_variants.py` using PyVCF to check that the values are correctly mapped into the GA4GH API.

**Comment by shajoezhu** [comment]
reporting for duty

**Comment by pgrosu** [comment]
Welcome back Joe :)

**Comment by dcolligan** [comment]
Fixed in #234
