### ISSUE TITLE
Unit tests required for SimulatedBackend

### ISSUE THREAD

**Issue by jeromekelleher** [ga4gh/server#222]
We need some basic tests for the simulator, to ensure that it works reasonably sensibly. We should make a new test module, `tests/test_simulator.py`, and create a test class in there, `TestVariantSet`. This class should test (e.g.)

1. The values passed into the constructor are stored correctly (after adding getter methods). For example, we'd want to check `self.assertEqual(seed, simulator.getRandomSeed()).
2. The variants we generate have the required properties (i.e., `start` and `end` are in the correct range).
3. The variants we generate are consistent. That is, if we allocate two simulators with the same seed and other parameters, they should produce identical variants when called on the same data.
4. The variants produced are `self-consistent`. This means that if we run the same query on a variantset more than once, we get the same result back.

These tests should be run at the VariantSet level. That is, we allocate instances of `datamodel.variants.SimulatedVariantSet`; we do not allocate any instances of `Backend`.

**Comment by dcolligan** [comment]
Fixed in #229
