### ISSUE TITLE
README is out of date

### ISSUE THREAD

**Issue by jeromekelleher** [ga4gh/server#224]
The README has not been updated to reflect the change over to a fully config-file driven input system. We should also take this opportunity to simply the README, and start preparing the way for a wormtable-free, deployable server. Some notes:

- We should remove the distinction between wormtable and Tabix variants. Now, we should explain the structure of the data directory (reads and variants), and state we can support VCF and BCF files.
- Our worked examples should only include references to the raw VCF files, and not mention wormtable at all. We should explain how to create a custom config file, and run this using the '-f' argument to the server.
- Remove the section on `Converting 1000G data`.
- Update the Code Layout section, to reflect more recent developments.

**Comment by jeromekelleher** [comment]
I'm working on this.

**Comment by dcolligan** [comment]
Fixed in #238
