### ISSUE TITLE
HtslibVariantSet should verify that metadata in different files is consistent

### ISSUE THREAD

**Issue by jeromekelleher** [ga4gh/server#231]
Because variant sets are often split into several VCF files (for example, each chromosome is in a separate VCF file in 1000 genomes), the `HtslibVariantSet` corresponds to a directory containing a set of VCF/BCF files. We currently assume that these VCF files are consistent, and have the same metadata. This should be verified at construction time.

**Comment by shajoezhu** [comment]
reporting for duty

**Comment by dcolligan** [comment]
Hi @shajoezhu , I infer from your previous activity to mean that "reporting for duty" means "I am working on this issue."  I'll assign the issue to you.

**Comment by shajoezhu** [comment]
sure. :)

**Comment by bioinformed** [comment]
Feel free to ping me if you have any questions on the metadata structure or
find any bugs or issues that need to be addressed.  I'm working on the
mutable API now and it is an ideal time to smooth over any rough edges.

**Comment by shajoezhu** [comment]
Thanks! Will do

**Comment by shajoezhu** [comment]
hi @bioinformed @jeromekelleher , i have a question, should metadata associate with each vcf file, or with the vcf file set? I was thinking, we should only call the getmetadata function once to build the metadata. I know we should still check through each vcf file in the set, but it seems cleaner to just build the metadata once, then check it with the vcffile.header, right?

**Comment by pgrosu** [comment]
How about just having a `combineVariants` function (like GATK) and then apply the metadata or annotation to it.  What do you think?  It could streamline things.

`p

**Comment by pgrosu** [comment]
Joe this is great, but could you substitute more meaningful variable names?

```Python
 def _updateMetadata(self, variantFile):
        """
        Updates the metadata for his variant set based on the specified
        variant file, and ensures that it is consistent with already
        existing metadata.
        """
        def compareItems(itemsOne, itemsTwo, name):
            exceptionMsg = "Variant file {} not equal".format(name)
            for x_item, y_item in zip(itemsOne, itemsTwo):
                if x_item[0] != y_item[0]:
                    raise Exception(exceptionMsg)
                if x_item[1].id != y_item[1].id:
                    raise Exception(exceptionMsg)
                if x_item[1].number != y_item[1].number:
                    raise Exception(exceptionMsg)
                if x_item[1].type != y_item[1].type:
                    raise Exception(exceptionMsg)
```

**Comment by jeromekelleher** [comment]
I agree @shajoezhu, we should just build the metadata once. The metadata is associated with the VariantSet --- it's an error if someone tries to make a VariantSet that contains VCF files with inconsistent metadata.

**Comment by shajoezhu** [comment]
Hi @bioinformed , description is missing for both infos and formats for the metadata of pysam. just wondering could you include them in the future? Thanks! :)

**Comment by dcolligan** [comment]
Fixed in #234

**Comment by shajoezhu** [comment]
Hi @bioinformed , I have a question, I was wondering in pysam, how was VariantRecordSample identified as a phased or not phased genotype?

**Comment by bioinformed** [comment]
Currently I don't expose phase information.  There are some big semantic
questions -- like what is a phased monoploid call?  Or a partially phased
triploid call set that doesn't have a disjoint block structure?  My
preference is to use allele-specific phase links rather than a vector of
boolean values.  This is where GATK has been moving, but I have yet to see
allele-specific phase links make it into the working VCF 4.3 spec.

In the mean time, perhaps a simple scalar phase attribute is reasonable:
gt.phased == True if all alleles are phased, gt.phased == False if all
alleles are unphased, and gt.phased is None otherwise?

-Kevin

**Comment by shajoezhu** [comment]
Cool! Thanks for this
