### ISSUE TITLE
Readme deployment instructions need to be verified

### ISSUE THREAD

**Issue by jeromekelleher** [ga4gh/server#239]
The README now contains instructions for deploying to Apache. These are somewhat complex and it would be good to independently verify that the work.

Once this issue is closed we should tag 0.1.0a2 in github and push a release to PyPI.

**Comment by macieksmuga** [comment]
Tried following the deployment instructions to the letter (on a fresh Ubuntu Server 14.04.2 install on a VM). I have a couple of minor notes that I'll put into a PR shortly.

**Comment by pgrosu** [comment]
Thanks Maciek for helping out on this - definitely being thorough is the best way :)

~p

**Comment by jeromekelleher** [comment]
Great, thanks @macieksmuga. Feel free to edit any of the rest of the README while you're in there --- it's in draft status at the moment, so any updates would be good (even big structural changes, anything that'll make it easier for to people to follow).

**Comment by macieksmuga** [comment]
The version of the ga4gh server that I installed via pip (for deployment) isn't the latest dev version. In particular, it fails to start up properly due to an interface mismatch in the `configure` method of `frontend.py` (which expects a configuration object in the version loaded via pip, as opposed to a file path in the latest dev version.

What's the thinking/procedure/script/schedule behind keeping the pip-installed version up-to-date with master?

**Comment by dcolligan** [comment]
Changes are going on in master all the time and it shouldn't be assumed that that version of the code and files from the pip installed version can be mixed.

Deployment to pypi right now is ad-hoc.  I presume @jeromekelleher essentially decides when he wants to upload a version.  I think the intention is to upload a new version whenever we bump the version number.

**Comment by macieksmuga** [comment]
@dcolligan Thanks! that makes sense. @jeromekelleher The above-mentioned issue will need to be addressed by pushing a more recent version with the appropriate configure code in it.

**Comment by macieksmuga** [comment]
...or simply amend the `application.wsgi` file in the README to read: 
```
frontend.configure(configFile="/srv/ga4gh/config.py")
```

**Comment by jeromekelleher** [comment]
There's a chicken and egg problem here - I would like the README to be correct _before_ we upload to PyPI. 

We should only upload to PyPI when we tag a release in git.

Can you verify the instructions work as if the current head of master was in PyPI? I.e., just substitute `pip install ga4gh` with `python setup.py install` from git.

**Comment by macieksmuga** [comment]
@jeromekelleher confirmed server install on ubuntu with the one substitution of building from github, as you suggested - everything now works, thanks!

**Comment by jeromekelleher** [comment]
Excellent! Thanks @macieksmuga, I'll tag a 0.1.0a2 in git tomorrow and upload to PyPI.

**Comment by macieksmuga** [comment]
Thanks @jeromekelleher, I'll re-test with the new tagged PyPI version as soon as it's there.
