### ISSUE TITLE
Paging test required

### ISSUE THREAD

**Issue by jeromekelleher** [ga4gh/server#241]
As part of the drive to remove Wormtable (as detailed in #210) we need to replace the tests that are currently embedded in the `TestWormtableBackend` with more modular tests. One of the tests we require is a test of the correctness of paging over the different sets of objects. We should create a new class in `tests/unit/test_backend.py` called `TestPaging(unittest.TestCase)`, which exercises the paging code across all the supported endpoints. This should use a `SimulatedBackend` as its test fixture.

The idea then would be to run some standard queries against the endpoints on this simulated backend (searchVariantSets and searchVariants for now) for a systematic selection of page sizes, and to verify that we always get back precisely the same results.

**Comment by dcolligan** [comment]
To replace TestWormtableBackend, it looks like we're going to have to substitute `.tbi` files for the wormtable files.  How does one create those files?  (Having a `README` inside `ga4gh-example-data` with how you generated those files would be useful.)

**Comment by macieksmuga** [comment]
@dcolligan I'm looking into this now.

**Comment by macieksmuga** [comment]
`.tbi` files are tabix indices on the VCFs as read by pysam.VariantFile, and generating them is described in the now removed tabix part of `README.txt` (perhaps we should bring this part back?):
```
The tabix backend allows us to serve variants from an arbitrary VCF file.  The
VCF file must first be indexed with `tabix
<http://samtools.sourceforge.net/tabix.shtml>`_.  Many projects, including the
`1000 genomes project
<http://ftp.1000genomes.ebi.ac.uk/vol1/ftp/release/20130502/>`_, release files
with tabix indices already precomputed. 
```
`ga4gh-example-data` currently comes with these index files precomputed.

**Comment by jeromekelleher** [comment]
Generating Tabix indexes is pretty standard - you're right though, we'll need a proper discussion of how we deal with indexes in the README. We should add this as an issue.

**Comment by macieksmuga** [comment]
Ok to close this now?
