### ISSUE TITLE
Implement reads/search

### ISSUE THREAD

**Issue by dcolligan** [ga4gh/server#246]
The reads/search endpoint is not implemented on the server.  Change that.

**Comment by dcolligan** [comment]
@jeromekelleher do we also want a ReadsSimulator?  What priority would that be?

**Comment by jeromekelleher** [comment]
A `ReadsSimulator` would be great, and is certainly something we'll need. I've no real idea how this would work though---my read-data ignorance is starting to hurt!

**Comment by jeromekelleher** [comment]
We should implement #247 before tackling this.

**Comment by dcolligan** [comment]
@jeromekelleher can you add some reads to ga4gh-example-data ?

**Comment by jeromekelleher** [comment]
Sure - if you point me in the direction of the files and give me a script to generate the subsets!

**Comment by dcolligan** [comment]
Scripts are in #243

Files are here: http://hgdownload.cse.ucsc.edu/goldenPath/hg19/encodeDCC/wgEncodeUwRepliSeq/

(I picked the first two bam files for test data, so I would avoid those two)

**Comment by dcolligan** [comment]
In `FileSystemBackend`, readGroupSetIds are indexed but there is no way in `GASearchReadsRequest` to specify a readGroupSetId.  Presumably, we should be indexing readGroupIds, which can be specified in a `GASearchReadsRequest`, (and which include the readGroupSetId in their id) correct?

**Comment by jeromekelleher** [comment]
Yeah, we'll need to index all the readGroupIds so we can find them for queries. We'll still need all the readGroupSets though, as these need to be retrievable also.

**Comment by dcolligan** [comment]
With regards to the nextPageToken with reads/search:

Is it possible for two alignments in a BAM file to be at the same starting position?  If so, setting the nextPageToken to include the position of the subsequent alignment will end up returning duplicate alignments.  In that case we would need to include the ids of alignments with the same starting position that the client has already consumed in the nextPageToken in order to filter them out on the server side.

If not, then the look-ahead method will work without the readAlignmentId array in the nextPageToken.

Fortunately (?), pysam's `fetch` doesn't include unmapped reads, so we don't need to worry about that complexity.

**Comment by jeromekelleher** [comment]
Excellent point @dcolligan, this actually applies to variant search also. This is a little bit tricky. We'll need an identifier of some sort, so we don't return the same variant/read twice when there are multiple records at the same position. We could use the file position for this, as that's guaranteed to be unique and is cheap to generate and check. That is, in `getReadAlignments` we yield an iterator over (GAObject, file position) pairs and then include the file position in the next page token. Would this work?

**Comment by dcolligan** [comment]
Unfortunately, I don't think so: `seek` and `tell` seem to be orthogonal to `fetch`.  (I'm not really sure what seeking through an indexed file where we wanted random access would really get us anyway.)

**Comment by dcolligan** [comment]
Fixed in #268

**Comment by bioinformed** [comment]
@dcolligan: regarding fetch not being reflected in seek/tell.  This is because the file is often re-opened when fetching to ensure that multiple threads can query the file without interfering with each other.  It is possible to disable this behavior and then seek/tell will work as you expect.

**Comment by dcolligan** [comment]
@bioinformed interesting.  I suspect as time goes forward and we strive for a more efficient implementation we will be forced to go deeper into pysam/htslib internals.
