### ISSUE TITLE
Review PyPI page/README

### ISSUE THREAD

**Issue by jeromekelleher** [ga4gh/server#256]
The PyPI package is now uploaded for v0.1.0a2, and it should start to look like something users can actually comprehend. The package is at https://pypi.python.org/pypi/ga4gh.

We need to review this, and make sure that new users get the information they need quickly. Is the current layout effective? Is the current approach of deployment, client tools and development too complicated? 

It would be good to collect any ideas that people have on how to improve the basic documentation here. (We should think about proper documentation a little later probably.)

**Comment by macieksmuga** [comment]
Thanks @jeromekelleher! I re-ran the install instructions on my ubuntu install, and all looked good (I checked the resulting install with a couple of the suggested `ga4gh_client` example queries in the readme.)

**Comment by macieksmuga** [comment]
One minor typo, that I'll issue a PR against momentarily.
But first, a question: Do I want to issue this PR against ga4gh/server master (which has gone significantly past the v0.1.0a2 tag?) or do we want to create a PiPY pre-release branch? Your call, @jeromekelleher.

**Comment by jeromekelleher** [comment]
I would say we always make PR against master. These tags exist (in my mind anyway) so that we have a fixed point in Git-space for each PyPI release. PyPI insists on a different version number for every upload, so we need to have 0.1.0a1, 0.1.0a2, etc every time we refine the package or the README. 

More generally, I suppose we'll want to have a separate branch for the 0.5.1 protocol series (which will be in bug-fix only mode) once we shift master over to 0.6 development. I'm no expert in this sort of thing though, so if someone would prefer a different model please feel free to open an issue so we can discuss the pros and cons.

**Comment by macieksmuga** [comment]
@jeromekelleher Thanks! Looks like @dcolligan already took up the PR into master, so all's well. 

As for creating a separate release branch after 0.5.1 is released, the model you describe is exactly how I've seen this done in other projects, so I support your proposal.

**Comment by macieksmuga** [comment]
@jeromekelleher I think we're approaching a good time to make a new tag/ PyPI package. I'll look over the documentation this weekend to see if it's still tracking the latest changes (haven't done a clean redeployment on this version yet). 

Also, time to start thinking about dockerizing the server + example data?

**Comment by jeromekelleher** [comment]
I need to make some change to the README  before we roll another PyPI package@macieksmuga, but I'll get that done today.

Excellent idea on docker - open an issue on this?

**Comment by jeromekelleher** [comment]
This issue has been superseded by #315 and #317.
