### ISSUE TITLE
A beacon client would be useful

### ISSUE THREAD

**Issue by jeromekelleher** [ga4gh/server#26]
Adding scriptable support for the beacon API would be very useful. It would be good to have a `beacon` function in the `ga4gh.client.HTTPClient` class, following the existing pattern. It would then be simple to add a CLI (either as part of the existing client application or as its own standalone program, if it was sufficiently useful) using this method. This would also require #25 to be solved, as Beacons will most often be at prefixed endpoints.

**Comment by kozbo** [comment]
This effort is being tracked over [here](https://github.com/BD2KGenomics/ga4gh-integration/issues/17) I did not create a Beacon endpoint in the client lib, but rather created a stand alone service that would work as an add-on to any GA4GH server. I will post code soon, just working out consistency with the current beacon structures spec.

**Comment by kozbo** [comment]
@jeromekelleher shall we close this issue and track progress in the issue in BD2KGenomics/ga4gh-integration?

**Comment by jeromekelleher** [comment]
Good idea @kozbo, closing.
