### ISSUE TITLE
GACall field phaseset unset 

### ISSUE THREAD

**Issue by shajoezhu** [ga4gh/server#265]
currently using pysam tool to extract elements for GACall. (HtslibVariantSet)

**Comment by jeromekelleher** [comment]
Can we get some more details on this please @shajoezhu?

**Comment by bioinformed** [comment]
The pysam VCF/BCF code does not yet expose phase information.  As I
described in another thread, I am still considering how best to proceed:
https://github.com/ga4gh/server/issues/231#issuecomment-82643656

**Comment by jeromekelleher** [comment]
We should fill this in ourselves in the mean time, so we have something reasonable. It's a bug if we're exporting a phaseset that's definitely wrong.

**Comment by bioinformed** [comment]
Can you point me to the GA4GH API spec for how phase is communicated?

**Comment by jeromekelleher** [comment]
I've never really understood what this means, but this is what we're going by:

http://ga4gh.org/documentation/api/v0.5.1/ga4gh_api.html#/schema/org.ga4gh.GACall

**Comment by dcolligan** [comment]
Fixed in #285
