### ISSUE TITLE
Add README to ga4gh-example-data

### ISSUE THREAD

**Issue by dcolligan** [ga4gh/server#266]
Following up on discussion in #241

ga4gh-example-data should have a README with instructions on how to generate the files therein.

**Comment by jeromekelleher** [comment]
OK, I'll do this when we go to the next (de-wormtablified) version.

**Comment by jeromekelleher** [comment]
I've done this for the new ga4gh-example-data --- what do you think @dcolligan?

**Comment by dcolligan** [comment]
Excellent.
