### ISSUE TITLE
Datadriven variant tests should test range searches

### ISSUE THREAD

**Issue by jeromekelleher** [ga4gh/server#269]
PR #264 adds data driven tests for variants in the HtslibVariantSet, and systematically tests the output variants for correctness. However, we do not test the search method in terms of the `start` and `end` arguments. We should test this by finding the maximum and minimum position in the variants that we read in using PyVCF, and then using these values to test range search. For example, we should

1. Test that empty ranges return no values (start=0 and end=0, start=max and end=max+1, etc, etc);
2. Test that the non-empty ranges return the correct set of variants (start=min and end=max, start=min and end=median, start=median and end=max, start=max-1 and end=max, etc, etc, etc).
3. Test the interval nature of the search. Technically, we are looking for variants that _intersect_ with the specified interval. We need to ensure that this is working correctly --- does our test data contain variants that are more than one base long?

We should do this by making a local function that returns the PyVCF variants that correspond to a particular range. This can be done by simple filtering.

**Comment by dcolligan** [comment]
Fixed in #281
