### ISSUE TITLE
Compliance according to existing tester should be verified

### ISSUE THREAD

**Issue by jeromekelleher** [ga4gh/server#272]
We need to check our compliance level with the existing compliance tester at https://github.com/ga4gh/compliance. For the beta release we should aim for full compliance on the reads and variants parts of the API.

**Comment by dcolligan** [comment]
Doesn't this compliance test assume that we have a certain data set loaded?

**Comment by jeromekelleher** [comment]
It does --- I'll just test it against the data it wants.

**Comment by jeromekelleher** [comment]
After merging #316, we get a compliance score of 81/117. This is broken down as full compliance on the variants API, partial compliance on the reads API and zero compliance on the references API.

The downmarks on the reads API are due to not handling things like `dataSetId` and `ReadGroupSet.name` properly (which is fair enough), but also due to several things which appear to be wrong. The tester seems to be checking if `GAPosition.position` is a string (and the schema says its a long), so we're losing a few compliance points there by implementing the API correctly.

So, since we are looking for initial support for the reads API only (and it would be misleading to imply that it is ready for use), I think this is good enough for our beta release.

**Comment by dcolligan** [comment]
Awesome!  Closing.
