### ISSUE TITLE
Add reads to ga4gh-example-data

### ISSUE THREAD

**Issue by dcolligan** [ga4gh/server#275]
We still need to determine what reads will go in (which Danny will do at a future date).

**Comment by awz** [comment]
Suggest we include some of this data: 

* https://sites.stanford.edu/abms/content/giab-reference-materials-and-data

The PGP data is in the public domain and has phenotypes.

**Comment by dcolligan** [comment]
@jeromekelleher can you add these files:

```
ga4gh-example-data/reads/wgBam/wgEncodeUwRepliSeqBg02esS1AlnRep1.bam
ga4gh-example-data/reads/wgBam/wgEncodeUwRepliSeqBg02esS1AlnRep1.bam.bai
```

From here: http://hgdownload.cse.ucsc.edu/goldenPath/hg19/encodeDCC/wgEncodeUwRepliSeq/

And also take out the wormtable stuff in ga4gh-example-data while you're at it?

**Comment by jeromekelleher** [comment]
I've gone for a slightly different approach @dcolligan, in which we add a subset of the samples for reads in 1000G. The updated dataset is available at the usual place (but without the .gz suffix --- see PR #311).

I think it's more useful to keep the data at least notionally consistent (i.e, that these variants are called from these reads), within our example data. We'll need to deal with this shortly when we start trying to tie the two together with the references.

@awz Thanks for the tip --- we should certainly look at serving this dataset soon.

**Comment by dcolligan** [comment]
Cool, looks good.
