### ISSUE TITLE
Replace hacked phaseset implementation with correct pysam approach

### ISSUE THREAD

**Issue by jeromekelleher** [ga4gh/server#291]
As a temporary measure, PR #285 introduced a hacky workaround to add phaseset support to variants. The need for this workaround should be removed in the next version of pysam, in which the correct phaseset information will be provided natively. 

The offending code is clearly marked in the source.

**Comment by kozbo** [comment]
Was there a new release of pysam? Did it provide a way for us to remove the hack? If so then we should remove the blocked label.

**Comment by bioinformed** [comment]
Yes, there was a pysam release and the hack should no longer be necessary.
Please let me know if you have any problems.

**Comment by david4096** [comment]
Closed with https://github.com/ga4gh/server/commit/d9117b8bc0a80f6f3fbca49f73d8141ba12a7feb

**Comment by shajoezhu** [comment]
:+1:
