### ISSUE TITLE
Useful summaries needed for default client CLI output

### ISSUE THREAD

**Issue by jeromekelleher** [ga4gh/server#293]
The current output of the CLI isn't very helpful for development, as it only outputs a single attribute for each object we read from the server. We should have something that at least allows us to identify the object in question. We can make this easier by refactoring things a little.

For example, we can have something like

``` python
class SearchVariantSetsRunner(AbstractSearchRunner):
     def __init__(self, args):
           super(SearchVariantSetsRunner, self).__init__(args) 
           request = RequestFactory(args).createGASearchVariantSetsRequest()    
           self._setRequest(request, args)
           self._method = self._httpClient.searchVariantSets

     def printObject(self, variantSet):
          print(variantSet.datasetId, variantSet.id, sep="\t")
```

The idea here is that we just have to implement the `printObject` method in each of the runner classes, and all the iteration is taken care of in the superclass.

We should then define `printObjects` for many of the runners, especially ReadGroupSets and Reads.

**Comment by macieksmuga** [comment]
Would it make sense to do this by adding meaningful `__repr__()` methods to protocol classes like `VariantSet`? I know these classes are auto-generated for now, but the rest of the code makes some pretty specific assumptions about these classes' structure (as demonstrated in the above code) anyway, so it may make sense to wrap `_protocol_definitions` in some non-autogenerated module that adds functionality, and this module would then be imported by the rest of the application instead.

**Comment by jeromekelleher** [comment]
Interesting idea @macieksmuga... I guess this would imply writing out _all_ the information contained in the objects though, whereas I'm thinking of a short and simple summary here.

What sort of stuff had you in mind for the updated classes (besides repr)? We could do something simple like having the generated classes in protocol_definitions be called (say) `_VariantSet` and then have
```
class VariantSet(_VariantSet):
     # Stuff
```
at the bottom of `protocol.py`. It would work pretty well I think (although the imports would be entertaining to work out).

**Comment by macieksmuga** [comment]
@jeromekelleher pretty much that. For now, `__repr__()` is what I was thinking of - and specifically, craft each protocol class's string representation so that it only returns a minimally useful set of data (nicely formatted), not everything contained in each object.

**Comment by jeromekelleher** [comment]
One thing though: `repr` is supposed to be a machine readable version of an object. I think it's probably `__str__` that you would want to implement.

**Comment by macieksmuga** [comment]
@jeromekelleher You're absolutely correct: `__str__`, not `__repr__`. My bad.

**Comment by david4096** [comment]
Moved https://github.com/ga4gh/ga4gh-client/issues/26
