### ISSUE TITLE
More examples in the README and usability testing required

### ISSUE THREAD

**Issue by jeromekelleher** [ga4gh/server#302]
We need to do extensive 'hands-on' tests on the server and client applications to verify that they work correctly and to ensure a smooth experience for new users trying out a demo. This should include adding in more examples into the README, along with extensive testing of this on the command line.

We should, of course, aim to automate all of our tests. However, we also need to get used to using our own applications and to make them more user friendly. The best way to do this right now is to dogfood the client application and to check all of the searches and example data on the command line.

It would be useful if we could keep a record of the type of testing each person has done. If you do some testing, can you report here on what you've done and the basic experience?

**Comment by diekhans** [comment]
This is a great idea.  We can get some grad students to try it
out.  We can do one or two at a time, as fresh, un-corrupted
minds are the best test.

**Comment by pgrosu** [comment]
@diekhans, Hehehe, I'm not sure grad students such pure angels :)

**Comment by jeromekelleher** [comment]
OK, 0.1.0a3 has been tagged, the updated package is on PyPI, and the new docs should be up at http://ga4gh-reference-implementation.readthedocs.org/en/latest/

Time to test! Please go through the documentation. If you see something easy that needs fixing, please open a PR to do so. If it's more difficult, open an issue and we can decide whether we want to resolve it by tomorrow.

The [demo](http://ga4gh-reference-implementation.readthedocs.org/en/latest/demo.html) is particularly important, so please go through this with a fine-tooth comb and make sure it works and makes sense

**Comment by dcolligan** [comment]
The zlib link in the demo page is broken on http://ga4gh-reference-implementation.readthedocs.org/en/latest/demo.html

**Comment by dcolligan** [comment]
Configuration link in the demo page is broken: "see [configuration] for detailed information" on http://ga4gh-reference-implementation.readthedocs.org/en/latest/demo.html

**Comment by dcolligan** [comment]
Other than that the docs look good to me

**Comment by jeromekelleher** [comment]
I've gone through the demo on a fresh ubuntu 14.10 VM and everything works fine. What's the experience like on a Mac? Do we need to provide guidance on installing zlib headers or is this provided as standard?

**Comment by dcolligan** [comment]
Closing this issue as the beta has been released
