### ISSUE TITLE
OAuth support required

### ISSUE THREAD

**Issue by jeromekelleher** [ga4gh/server#31]
The reference implementation needs support for [OAuth](http://oauth.net/) to allow us to perform authentication. There are many problems to be resolved in this, and this issue should provide a central location for the discussion around this topic. 

Some questions:

1. What library should we use?
2. Do we use OAuth 1.0 or 2.0?
3. Lots of other questions I would ask if I knew more about OAuth.

Hopefully we can flesh out the actual requirements for the reference server here, and make a concrete plan for implementing these.

**Comment by jbu** [comment]
Hi everyone,

After the call yesterday, the consensus seems to be: 
* Use OIDC
* Go with https://github.com/rohe/pyoidc as the bulk of the implementation.
* Stick to static client registration.

**Comment by dglazer** [comment]
Glad to see momentum here. Was there also discussion on yesterday's call about the plan for authentication and access control?

For authentication -- per http://openid.net/2015/04/17/openid-connect-certification-program/, it looks like our timing is good here -- apparently several big identity providers (including Microsoft and Google) have recently certified their compliance with OIDC. Assuming pyoidc works as advertised, that means people should be able to use existing credentials to authenticate with the reference server -- great.

For access control -- server operators still need a way to say "this user can see this object". See the earlier comments (Oct 31 2014) from @delagoya and me on possible simple answers.

**Comment by jeromekelleher** [comment]
This sounds like a good plan @jbu, thanks.

@dglazer, for authentication, we're hoping to support a few OIDC providers, time allowing. Initially we'll be keeping it simple a using a local provider. For authorisation, we'll be keeping it very simple. Initially, yes/no access to the repository, and after than, yes/no access to a dataset. That will be enough to get us started.

**Comment by dglazer** [comment]
Thanks @jeromekelleher - starting simple sounds great.

Making sure I understand:
- for authN, having a "local provider" implies there's some way for users to get their id/credentials added to that local provider. Is the idea to just have a server-side text file of names and non-secure passwords, or to build an account management UI, or am I misunderstanding?
- for access control, is the idea to have a manually-maintained server-side text file with a list of authorized ids (initially a repository-level list; later adding dataset-level granularity)? If so, SGTM.

**Comment by jeromekelleher** [comment]
@dglazer, well, the local provider we have is just for testing and development. For deployments, we'll use a real authentication provider. Who the auth provider is and how we set up the login process is to be decided. There is no plan to have a password management UI.

Authz is as you described. Our config file will contain the list of user IDs that are authorised to access a particular resource.

**Comment by pgrosu** [comment]
@jeromekelleher  How granular would the resource be defined (i.e. `ReadGroup` or `ReadAlignment`, etc.)?  Probably having authentication on encompassing resources such as `ReadGroup` would improve the performance while providing the same permission requirements.  I believe @delagoya suggested something along the same lines at a previous time.

On another note, was there anything else discussed on the call yesterday?  I didn't get an invitation but would be nice to be in sync with the discussion so that I don't repeat something already discussed.

**Comment by dglazer** [comment]
@jeromekelleher -- all sounds good; I think a simple non-secure local provider is just fine for testing and development. (If we're lucky federated authentication will come for free from pyoidc, but I agree it isn't worth extra effort at this point.)

**Comment by jeromekelleher** [comment]
closing this, as we have basic OAuth support.
