### ISSUE TITLE
Script required to generate `ga4gh-example-data` from 1000G sources

### ISSUE THREAD

**Issue by jeromekelleher** [ga4gh/server#312]
The current ga4gh-example-data tarball contains a subset of the variants for 1000G phase1 and phase3. To make things managable, we also use only 3 samples, and throw away the others. We include the low coverage reads for these samples also.

Generating this dataset manually is tedious and error prone, and we should seek to automate the process using a script. The script should do the following:

1. Open remote connections to the 1000G VCF files at either the EBI or NCBI mirror (it should be command line option which one we use. Probably default to NCBI) using PySAM.
2. For each VCF file, extract the first *n* records and write these out to our example data directory. We should also only write out sample information for a small subset of the available samples. The samples to use should also be a configuration option. Record the positions of the first and last variant we see.
3. For each sample we are interested in, open a remote connection to the relevant BAM file, and retrieve all reads in the regions that intersect with the variants we extracted in (2). Save these reads into the `reads` section of our example data tree.
4. Generate the corresponding references by download the regions we are interested and saving these to FASTA files.

This script should allow us to generate a manageable subset of the 1000G data which we can use for development and demonstration purposes.

We require VCF write functionality in pysam for this, which is coming soon. I'm marking this issue as blocked until this is released.

**Comment by jeromekelleher** [comment]
I've added this to the Sync with schemas milestone as we need better example data, and this is the simplest way to do it. If pysam VCF write support doesn't arrive soon we should make a shell script to do this using Unix tools.

**Comment by jeromekelleher** [comment]
Thinking about this again, we don't actually need VCF write support in pysam. We can use the Tabix interface to obtain the raw VCF records, and output these directly.

**Comment by dcolligan** [comment]
Partially addressed in #570

**Comment by dcolligan** [comment]
Fixed in #581, etc.
