### ISSUE TITLE
New documentation outline

### ISSUE THREAD

**Issue by jeromekelleher** [ga4gh/server#317]
@shajoezhu and I have been looking at the documentation, and we think the best approach is to split it into different parts:

1. The README.rst file should just contain basic information about the project and serve as the landing page on GitHub and PyPI. This can contain links to the more detailed documentation, which is hosted on read-the-docs.org.
2. The detailed documentation is then written separately using Sphinx and reStructuredText, and hosted on read-the-docs.org. We can link this to GitHub so that our documentation is automatically rebuilt when we ship a release.

Issue #315 is the start of this process.

**Comment by dcolligan** [comment]
+1 on this approach
