### ISSUE TITLE
Fix client logging

### ISSUE THREAD

**Issue by dcolligan** [ga4gh/server#324]
Client logging has our messages entangled with urllib3's messages.  We should probably suppress all of urllib3's messages.

Also, we don't really care about printing the debugLevel for our messages.

```
$ python client_dev.py -vv -O variants-search http://localhost:8000/v0.5.1
INFO:ga4gh.client:POST http://localhost:8000/v0.5.1/variantsets/search
DEBUG:ga4gh.client:json request:
DEBUG:ga4gh.client:{
    "datasetIds": [],
    "pageSize": null,
    "pageToken": null
}
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): localhost
DEBUG:requests.packages.urllib3.connectionpool:"POST /v0.5.1/variantsets/search HTTP/1.1" 200 4887
DEBUG:ga4gh.client:json response:
DEBUG:ga4gh.client:{
    "nextPageToken": null,
    "variantSets": [
...
```

**Comment by jeromekelleher** [comment]
I quite like urllib3's messages --- it's the only way I can see direct information about what's happening at the HTTP level. In particular, the response length is useful to know. I don't have an opinion either way when it comes to the debugLevel output.

**Comment by david4096** [comment]
moved
