### ISSUE TITLE
Feature freeze for 0.1.0 release?

### ISSUE THREAD

**Issue by macieksmuga** [ga4gh/server#325]
This isn't so much an issue as a question for @jeromekelleher: 
Will there be a feature freeze before the 0.1.0 release (all PR merges between the freeze and the release would be for bug fixes only)? If so, when? And will there be an associated tag? Thanks!

**Comment by jeromekelleher** [comment]
Yes, good idea @macieksmuga. Let's call that freeze today (excluding documentation updates). I think we should try and tag 0.1.0a3 today so that we can test out installation and the docs. We should then tag 0.1.0b1 tomorrow, unless we hit any show stoppers.

**Comment by dcolligan** [comment]
Question answered, closing...

**Comment by diekhans** [comment]
May I suggest create a release branch and not just tagging.
This is often SOP and makes it much easier to do parallel
development with a release and fix bungs in the release.

this is really exciting

Mark

**Comment by jeromekelleher** [comment]
This is a good idea @diekhans -- I'm opening an issue to discuss future releases and development.
