### ISSUE TITLE
Git development and release process

### ISSUE THREAD

**Issue by jeromekelleher** [ga4gh/server#330]
Now that we're leaving the initial "let's get something working" phase and moving to a more predictable release model, we should review our development processes and release engineering plans.

Currently, all development happens on the master branch and we just tag releases when they are ready. This is simple and lightweight, but has some disadvantages:

1. Master breaks every now and then. It's unavoidable that unexpected interactions between PRs will lead to the master branch being broken every now and then.  This isn't good, because we want people who clone our repo on github to have something that is stable and works well by default.
2. When moving towards a release, the stabilisation requirements make it difficult for normal development to proceed.
3. When we want to make bugfixes to a release, we need to create ad-hoc branches off the release tag to do this.

I think it might be worthwhile adopting a more formal release and development model, perhaps something like the model discussed [here](http://nvie.com/posts/a-successful-git-branching-model/). I'd suggest something like:

1. All development is done on the `develop` branch. PRs are made on this branch and are merged back into it.
2. When a release is almost ready, we make a release branch and do the stabilisation work there.
2. When the release is ready, we merge the release branch into master and tag the release.

Thoughts?

**Comment by macieksmuga** [comment]
This is exactly the model I used on two previous git-backed projects. It worked well for us - but both those projects were significantly smaller (number of developers-wise) than this one, so I can't vouch for how it behaves at our scale.

**Comment by dcolligan** [comment]
We've adopted this model.  Closing.
