### ISSUE TITLE
URL support for variants broken

### ISSUE THREAD

**Issue by jeromekelleher** [ga4gh/server#339]
The support for using URLs as a data source in `HtslibVariantSet` is currently broken, as we insist that there is at least one VCF/BCF file in the data directory. This can be fixed easily enough by moving the check and count to after the URLs have been read in.

The `EmptyDirException` should also take the offending directory as an argument so that we can build a meaningful error message.

**Comment by dcolligan** [comment]
There's that big comment in `variants.py` saying how `urls.json` is not a good idea.  What were you envisioning for replacing it, @jeromekelleher ?

**Comment by jeromekelleher** [comment]
We'll figure out how to fix that when we can properly work with index files.

**Comment by dcolligan** [comment]
Fixed in #343
