### ISSUE TITLE
URL support for read data.

### ISSUE THREAD

**Issue by jeromekelleher** [ga4gh/server#340]
We currently have some cludgy code to allow variant data be read from a remote URL source. The same method can applied to reads. We should try to abstract the details of how we do this so that the VariantSet and ReadGroupSet share the same code --- we could try to adapt (and rename) PysamSanitizer to do this.

~~We should resolve #339 first/also.~~

**Comment by dcolligan** [comment]
What does `PysamSanitizer` have to do with this?

**Comment by jeromekelleher** [comment]
Fixed in #345
