### ISSUE TITLE
Refactoring of the datamodel code required

### ISSUE THREAD

**Issue by jeromekelleher** [ga4gh/server#346]
Currently a lot of code in the `datamodel/reads.py` and `datamodel/variants.py` modules is duplicated, and not very logically organised. PR #345 is a start towards fixing this, but the changes need to go much further. We need a logically consistent, and well-thought out and well-documented class hierarchy for our data model objects, in which as much code as possible is pushed into superclasses.

**Comment by dcolligan** [comment]
Maybe you can flesh out what you had in mind?

**Comment by macieksmuga** [comment]
When generalizing code between these two, note that reads and variants currently provide a fairly straightforward conduit to underlying file formats (BAM and VCF) - and thus the large volume of shared code. This will continue to be the case for the "classical" mode of the server, but not for the graph mode: 

There, variants are like references - they're both represented by paths, sequences and joins in an overall variation graph, and will most likely reside within a single Sqlite database in the initial reference server implementations.

**Comment by jeromekelleher** [comment]
As @macieksmuga points out, the right design here will depend heavily on how classic mode and graph mode interact. Let's see how that's working out before tackling this.

**Comment by jeromekelleher** [comment]
This has been done in a recent refactoring.
