### ISSUE TITLE
Rename master branch

### ISSUE THREAD

**Issue by dcolligan** [ga4gh/server#349]
The branch `master` should be renamed to reflect what its actual use is.  It is not the default branch anymore; that would be `develop`.

I propose we rename it to `stable` and update the documentation accordingly.  I am not proposing any changes in our development process.

**Comment by dcolligan** [comment]
If no one objects over the next day, I'll go ahead and make this change.

**Comment by macieksmuga** [comment]
+1

**Comment by jeromekelleher** [comment]
+1

**Comment by dcolligan** [comment]
Alright, I just deleted the master branch and added the stable branch to upstream (I did feel kind of instinctually queasy about running `git push --delete upstream master`).  #351 is the PR to update the docs to reflect this.

**Comment by dcolligan** [comment]
Fixed in #351
