### ISSUE TITLE
Re-enable &  fix unit tests in test_schemas.py for schemas_e6d6074

### ISSUE THREAD

**Issue by macieksmuga** [ga4gh/server#356]
Resulting from schema update in PR #353

**Comment by macieksmuga** [comment]
Fixing this issue is uncovering inconsistencies in the Avro schemas themselves since 0.5.1. I'll shortly create a PR in ga4gh/schemas to address all the ones I've found.

**Comment by dcolligan** [comment]
Fixed in #515
