### ISSUE TITLE
PyPI package required

### ISSUE THREAD

**Issue by jeromekelleher** [ga4gh/server#36]
The standard approach for distributing Python software is to use the [Python Package Index](https://pypi.python.org/pypi). This would allow users to install the client and server tools simply by running `pip install ga4gh`.

Ultimately we want to have a pip installable package so that the server can be deployed as simply as possible. There are a few issues that should be resolved first, and this is a good place to discuss the issues:

1. What should the package be called? (ga4gh seems the obvious choice.)
2. When do we make a PyPI package available? (i.e. do we wait until we have a stable release, or do we make early alpha versions available for use, with the clear proviso that the _are_ early alpha releases?)
3. Should we create a PyPI account to upload the packages run by the GA4GH or just use an account owned by one of the developers?

**Comment by dcolligan** [comment]
I've uploaded ga4gh to pypi: https://pypi.python.org/pypi/ga4gh

If you have a pypi account and want to be added as an admin, let me know what your pypi username is so I can add you

**Comment by pgrosu** [comment]
Nice!  Thanks @dcolligan :)

**Comment by dcolligan** [comment]
Install with this command:
```
$ pip install ga4gh==0.1.0a1
```
