### ISSUE TITLE
Add CI to schemas repo?

### ISSUE THREAD

**Issue by dcolligan** [ga4gh/server#366]
This is something that @macieksmuga and I were discussing, given some of the errors that we've found in the schemas.  Would it be a good idea to add CI to the schemas repo that does a bunch of checks (using process_schemas, avrotools, etc.) to ensure the validity of the objects as they get created in python?

They do seem to have a `.travis.yml` file already that just calls mvn to compile the classes (at least that's what it looks like)... https://travis-ci.org/ga4gh/schemas

**Comment by macieksmuga** [comment]
Both I and @adamnovak agree that this would be a good idea. @jeromekelleher opinions on this?

**Comment by dcolligan** [comment]
Does their existing CI actually do anything?

**Comment by adamnovak** [comment]
It runs Maven and makes sure that the Avro IDL files compile cleanly to
Java classes.

**Comment by macieksmuga** [comment]
But... they don't. Otherwise we wouldn't be seeing the inconsistencies that we are (such as incorrect default value types for fields and repeated/conflicting definitions of records)

**Comment by jeromekelleher** [comment]
I completely agree that we should update the CI for the schema repo, it's very weak right now. I'm not sure that using process_schemas is the right way to go though --- can we toughen up the existing CI, i.e make warnings into errors, and that sort of thing? I think this would catch a lot of problems.

**Comment by dcolligan** [comment]
I just looked at the maven docs and I don't see a way to make the compilation more stringent.  The documentation for `avro-maven-plugin` is about as good as the documentation for avro, 'nuff said.

In any event, I would vote for avoiding tying ourselves to maven, since in my experience it's way more trouble than it's worth.  We can keep the existing functionality by just calling the existing mvn commands by using python's `subprocess` module or whatever.

**Comment by dcolligan** [comment]
I submitted a PR in the schemas repo https://github.com/ga4gh/schemas/pull/291

**Comment by dcolligan** [comment]
Fixed in https://github.com/ga4gh/schemas/pull/291
