### ISSUE TITLE
have generated protocol class take fields as arguments to the constructor

### ISSUE THREAD

**Issue by diekhans** [ga4gh/server#372]
Currently, the constructors to the generated protocol class don't take any arguments to initialize the fields.  This makes using them more verbose without improving readability.  Suggest generate optional arguments to protocol class that initialize each field.  Idealy, they would initialize to the default value if not specified, however just defaulting to None would a big improvement.

For example, https://github.com/ga4gh/server/blob/develop/ga4gh/datamodel/variants.py#L72 CallSet.toProtocolElement()  we currently have:
<pre>
         gaCallSet = protocol.CallSet()
         gaCallSet.created = self._variantSet.getCreationTime()
         gaCallSet.updated = self._variantSet.getUpdatedTime()
         gaCallSet.id = self._id
         gaCallSet.name = self._sampleName
         gaCallSet.sampleId = self._sampleName
         return gaCallSet
</pre>
If protocol.Callset initialized all the class members from constructor arguments, one could have
<pre>
         return protocol.CallSet(created = self._variantSet.getCreationTime(),
                                 updated = self._variantSet.getUpdatedTime()
                                 id = self._id,
                                 name = self._sampleName,
                                 sampleId = self._sampleName)
</pre>

**Comment by jeromekelleher** [comment]
This wouldn't be difficult to do, and I think would increase readability in some situations. +1 on the idea and the changes.

**Comment by dcolligan** [comment]
This depends on #369

Once that is done, this will be a pretty easy change to `process_schemas.py`

**Comment by dcolligan** [comment]
Fixed in #518
