### ISSUE TITLE
no instructions on running process_schemas

### ISSUE THREAD

**Issue by diekhans** [ga4gh/server#373]
a grep of the tree shows no information on how to run process_schemas

I have updated the schemas in the annotation branch and need to rebuild.

**Comment by dcolligan** [comment]
Running with the `--help` flag should give you a list of options to pass in.  What additional kind of docs do you think we should have on this tool?

**Comment by diekhans** [comment]
Yea, --help makes sense.  I guess mentioning it in the developer
doc and specific how it's supposed to be used for this project
would help people come up to speed.

**Comment by jeromekelleher** [comment]
Good point @diekhans: we should add a subsection on this in the Organisation section of development.rst. This should basically just explain the basic idea of how and why we generate code from the Avro IDL schemas, and an example of running process_schemas.py against a released and local version of the schema definitions.

**Comment by dcolligan** [comment]
Fixed in #377
