### ISSUE TITLE
Dataset support required

### ISSUE THREAD

**Issue by jeromekelleher** [ga4gh/server#376]
Currently, we implicitly only support one dataset. We need to support an arbitrary number of datasets. This issue acts as a meta-issue and can be closed once all of the dependent issues have been resolved.

1. ~~Choose a configuration mechanism suitable for multiple datasets (collections of reads and variants) and references. Issue #375 has been created for this. The server should insist on exactly one dataset being specified while the rest of the code is being updated.~~
3. Update the example data and the documentation to reflect this new structure. 
2. Generalise backend.py to allow for multiple datasets. *Important* We do not need to support queries spanning multiple datasets, and should require exactly one dataset be specified. (A change in the schemas to make this official will be included any month now --- see ga4gh/schemas#253)

**Comment by dcolligan** [comment]
@jeromekelleher do we have a precise definition of what a dataset is (supposed to be)?  Why are datasets even necessary?  Couldn't one keep adding directories under `/variants`, etc. if one wanted to serve more variants?

**Comment by diekhans** [comment]
It is not clear what a DataSet is to GA4GH.  The intention was not
documentation and it's use is inconsistent.  It's burred in reads.avdl,
but it appears to apply to other data types.

Might be worthwhile finding out who add this can get them to
document what it is.

**Comment by pgrosu** [comment]
@diekhans, @jeromekelleher, @dcolligan So a Dataset was added as a logical grouping for a collection of one or more of the following - just think of a dataset as a study that was performed and which joins/groups all the relevant data associated with it:

- ReadGroup
- ReadGroupSet
- VariantSet 
- FeatureSet 

This first introduced in [schemas PR #33](https://github.com/ga4gh/schemas/pull/33), and is available at the following link:

https://github.com/ga4gh/schemas/pull/33

Hope it helps,
Paul

**Comment by pgrosu** [comment]
And yes you will need querying multiple datasets, especially for metadata among other things.  For a review of the different reasons why, below is a link to [pull-request 253](https://github.com/ga4gh/schemas/pull/253) from schemas:

https://github.com/ga4gh/schemas/pull/253

~p

**Comment by dcolligan** [comment]
Seems like @jeromekelleher filed a clarification issue a while back: https://github.com/ga4gh/schemas/issues/248

**Comment by dcolligan** [comment]
Fixed in #442
