### ISSUE TITLE
better error responses for bad requests

### ISSUE THREAD

**Issue by acthp** [ga4gh/server#382]
Error responses for bad requests look like

    {blah} is not a valid instance of <class 'ga4gh._protocol_definitions.GASearchVariantsRequest'>

which is less than helpful. It would be good to return why the request is not valid, like 'referenceName is undefined', etc.

**Comment by jeromekelleher** [comment]
I agree, this would be a useful feature. I think we can now do this using the Avro technology that @dcolligan developed. How feasible would it be to add some extra information, and what could we provide @dcolligan?

**Comment by dcolligan** [comment]
Yeah, we could definitely improve error messages.  `avrotools` can't provide something like 'referenceName is undefined', but it can provide the subset of the JSON hierarchy that is erroneous.

**Comment by dcolligan** [comment]
Fixed in #383
