### ISSUE TITLE
Dense variants not handled correctly by released server

### ISSUE THREAD

**Issue by jeromekelleher** [ga4gh/server#391]
Users of the released version of the server have encountered problems in which dense variants (i.e., those in which we have more than one variant overlapping a given position) are present. This is because we don't handle interval search correctly, which has been resolved since release in  the develop branch. 

Suggested resolution:

1. Makes some tests for dense variants (we can update the variant simulator to generate many variants at a given position) to verify they are handled correctly in the 'develop' branch.
1. Make a release branch called 0.1-release from the current stable branch.
2. Backport the changes required to implement interval search on variants (plus new tests) by cherry-picking the relevant commits.
3. Release a new version. Should we call this 0.1.0b2 or 0.1.0?

**Comment by diekhans** [comment]
>  4. Release a new version. Should we call this 0.1.0b2 or 0.1.0?

b2 == beta 2 to me

suggest the original is tagged on the branch as 0.1.0 and this one
tagged a 0.1.1

This is the major.minor.bugfix  release numbering approach.  It 
is clean and easy to understand (and parse).

this is an entertaining distraction
  http://en.wikipedia.org/wiki/Software_versioning

The fact that you have to do this kind of professional releasing
management at all is exciting.

**Comment by jeromekelleher** [comment]
OK, let's go to 0.1.1 for this one so. We can make a copy of the tag for 0.1.0 so that we have a record of it (although I don't see much point in pushing a copy to PyPI).

The original motivation of using a1, a2, b1, b2 etc was to use the Python standard for managing alpha and beta version numbers. In retrospect, we should have tagged 0.1.0 instead of 0.1.0b1 as the official release. Oh well, we'll know better next time!

**Comment by diekhans** [comment]
I like that convention for alpha/beta ; but I think 0.1.0 is a real release..

Hopefully this will not be like some OSS projects where they work for
years and avoid ever releasing a 1.0 ;-)

**Comment by dcolligan** [comment]
I think we should also include this change in the new release: https://github.com/ga4gh/server/pull/386

**Comment by jeromekelleher** [comment]
@dcolligan: sure, I'm happy to roll in #386 too.

**Comment by dcolligan** [comment]
@jeromekelleher are you taking this on?

**Comment by jeromekelleher** [comment]
@dcolligan I think the person with the requisite git-foo is you. You should have the permissions on PyPI etc, so just go for it I'd say. One thing though: do we have test coverage on dense variants?

Slightly revised plan:
1. make a new branch 0.1-release from stable;
2. Update `ga4gh/__init__.py` to bump the release to 0.1.0.
3. Tag the release in github using their UI,  copying the release notes from 0.1.0b1 and call it 'Initial release for testing'.
4. Upload the code to PyPI using `python setup.py sdist; twine upload dist/[file]`
5. Do the cherry picking discussed above, and them make the release 0.1.1 following the above procedure (but with different release notes, etc, obviously).
6. merge the 0.1-release branch back on to stable?

I changed my mind about releasing an official 0.1.0 version --- we should have this here for completeness, and it's not big deal to make it now. It would be good to hear you experiences with this process and if there's anything we should consider streamlining.

**Comment by dcolligan** [comment]
I think you can only use GitHub's UI to tag branches on upstream, as opposed to the local fork.  (I know I could just use the command line to tag, but whatevs.)  Anyways, steps 1 and 2 are waiting for your merge here: https://github.com/ga4gh/server/pull/400

**Comment by jeromekelleher** [comment]
I think there's a slight confusion here --- in my head, we have a new branch 0.1-release on which we maintain the 0.1.x bugfix releases in the upstream repo. After we make a release, we then merge the state of 0.1-release back on to stable.

**Comment by dcolligan** [comment]
Fixed in #410
