### ISSUE TITLE
server should provide access to variantset metadata 

### ISSUE THREAD

**Issue by MollyZhang** [ga4gh/server#395]
The brca challenge needs to get access to metadata of a variant file via ga4gh reference server. Right now the server doesn't have an endpoint to provide that information. 

The current schemas "metadatamethods.avdl" specifies methods like "samples/search" and "individuals/search", but for now just a comprehensive key-value pairs of all available vcf header should suffice. 

Since there is a 1 to 1 correction between metadata and variantset, does it make sense to just add a method in "variantsets/search" end point and return the metadata for each variantset if specified?

**Comment by jeromekelleher** [comment]
Have you a concrete example of what's needed here @MollyZhang? The `VariantSet` object contains the metadata taken from the header of a VCF, which should have everything in there. Try running `python client_dev.py -vv variantsets-search <URL>`.

**Comment by MollyZhang** [comment]
Oh awesome, seems like -vv variantsets-search solves the problem! Thanks @jeromekelleher
