### ISSUE TITLE
HtslibVariantSet._getMetadataFromVcf() is not parsing metadata correctly

### ISSUE THREAD

**Issue by MollyZhang** [ga4gh/server#396]
The "_getMetadataFromVcf()" in HtslibVariantSet class doesn't seem to parse the metadata correctly. 

Here is a line of output in self._metadata after parsing:

VariantSetMetadata({"info": {}, "description": "", "number": "1", "value": "", "key": "FORMAT.DS", "type": "Float", "id": ""})

the "description" key,  for example, has an empty " " value while vcf file header has English words as description, shown here:

##FORMAT=\<ID=DS,Number=1,Type=Float,Description="Genotype dosage from MaCH/Thunder">

**Comment by bioinformed** [comment]
Please let me know if this is a pysam/htsib bug.  If so, please send a
minimal test case and I will fix asap.

**Comment by jeromekelleher** [comment]
When this code was being written, we weren't able to access the description in `VariantMetadata` from pysam/cbcf.pyx @bioinformed. It seemed like it hadn't been implemented (we should have filed a bug report, sorry). Has this been implemented now, or is there a different way to access the description field?

**Comment by dcolligan** [comment]
@bioinformed I just sent you an email with a test case

**Comment by bioinformed** [comment]
Thanks for the heads up.  `description` will be an attribute of `VariantMetadata` in the next pysam release.  I've also added a full mapping interface to `VariantHeaderRecord` so that access is more natural (i.e. doesn't require iterating through `attrs`).

**Comment by dcolligan** [comment]
@bioinformed Great!

**Comment by david4096** [comment]
Closed with https://github.com/ga4gh/server/pull/407
