### ISSUE TITLE
pyvcf module is returning empty metadata 

### ISSUE THREAD

**Issue by MollyZhang** [ga4gh/server#406]
In tests/data_driven/test_variants.py, it imports the module vcf to parse meta data and compares that result to pysam vcf meta data parser. However, the vcf module returns an empty metadata dictionary, and the tests in line 332-347 pass because they are not run at all.

**Comment by jeromekelleher** [comment]
This seems to work fine for me @MollyZhang --- I've put in some prints (say at line 333) to print out the infoKeys, and all the metadata seems to be there. Can you be more specific about what you're seeing?

**Comment by shajoezhu** [comment]
Hi @MollyZhang , when I add line ` print(infoKey)` to line 333, and ran,

    $ nosetests tests/datadriven/test_variants.py -vs

I get the printout something like
```
tests.datadriven.test_variants.VariantSetTest.testVariantSetMetadata:example_1 ... AC
AF
AN
BaseQRankSum
DP
DS
Dels
FS
HaplotypeScore
InbreedingCoeff
MLEAC
MLEAF
MQ
MQ0
MQRankSum
QD
RPA
RU
ReadPosRankSum
STR
ok
```

It seems working fine for me as well.

**Comment by MollyZhang** [comment]
@jeromekelleher @shajoezhu @dcolligan 
I found out that I used the pyvcf module wrong. 
basically I did this `vcf.Reader(vcfFile)` instead of `vcf.Reader(filename=vcfFile)`
and the former returns an empty metadata. (Although I would think it's more intuitive to allow for the first way to read a file)
I didn't double check the code, sorry for the trouble...so this issue can be closed.

**Comment by dcolligan** [comment]
That is unintuitive... consider filling an issue with pysam if you think it's warranted.

**Comment by diekhans** [comment]
If the vcf documentation indicates vcf.Reader(vcfFile) should
work and it doesn't, please file a ticket with the pyvcf project.

**Comment by MollyZhang** [comment]
@diekhans 
the pyvcf documentation is like this:
`class vcf.Reader(fsock=None, filename=None, compressed=None, prepend_chr=False, strict_whitespace=False)`
it's not wrong, just not very intuitive.
