### ISSUE TITLE
tests/data/graphs/graphData_v023.sql has incorrect GraphJoin_ReferenceSet_Join example

### ISSUE THREAD

**Issue by abeconnelly** [ga4gh/server#427]
In the example file [graphData_v023.sql](https://github.com/ga4gh/server/blob/graph/tests/data/graphs/graphData_v023.sql), from lines [52](https://github.com/ga4gh/server/blob/graph/tests/data/graphs/graphData_v023.sql#L52) to [59](https://github.com/ga4gh/server/blob/graph/tests/data/graphs/graphData_v023.sql#L59) it looks like the values are reversed.  It should read:

```SQL
INSERT INTO GraphJoin_ReferenceSet_Join VALUES (1, 1);
INSERT INTO GraphJoin_ReferenceSet_Join VALUES (2, 1);
INSERT INTO GraphJoin_ReferenceSet_Join VALUES (3, 1);
INSERT INTO GraphJoin_ReferenceSet_Join VALUES (4, 1);
INSERT INTO GraphJoin_ReferenceSet_Join VALUES (5, 1);
INSERT INTO GraphJoin_ReferenceSet_Join VALUES (6, 1);
INSERT INTO GraphJoin_ReferenceSet_Join VALUES (7, 1);
INSERT INTO GraphJoin_ReferenceSet_Join VALUES (8, 1);
```
Here is the definition of the `GraphJoin_ReferenceSet_Join` table:

```SQL
CREATE TABLE GraphJoin_VariantSet_Join (
    graphJoinID INTEGER NOT NULL REFERENCES GraphJoin(ID),
	variantSetID INTEGER NOT NULL REFERENCES VariantSet(ID),
	PRIMARY KEY(graphJoinID, variantSetID));
```

The resulting `graph.db` SQLite3 database also has those fields reversed.

**Comment by macieksmuga** [comment]
Resolved in PR #446 
Thank you @abeconnelly for pointing this out!
