### ISSUE TITLE
ensure all Avro JSON gerenated by the server conforms to schemas and is useable from java

### ISSUE THREAD

**Issue by diekhans** [ga4gh/server#428]
@wstidolph instructions on how to do this

The avro tools jar provides a utility we can use to validate a given JSON file against a given Avro Schema (*.avsc):

java -jar avro-tools-1.7.7.jar jsontofrag --schema-file Individual.avsc BadIndividual.json
Exception in thread "main" org.apache.avro.AvroTypeException: Expected field name not found: id
        at org.apache.avro.io.JsonDecoder.doAction(JsonDecoder.java:477)
…

If the JSON validates then a binary object is produced and can be discarded (only STDERR is interesting). On Windows, this might done with, e.g.:

java -jar avro-tools-1.7.7.jar jsontofrag --schema-file Individual.avsc BadIndividual.json >>NUL

Normal command line handling applies; for example, in a bash environment, the STDOUT can be dropped and the STDERR can be piped to cleanup or logging, etc:

java -jar avro-tools-1.7.7.jar jsontofrag --schema-file OntologyTerm.avsc RandomOntologyTerm.json 2>&1 > /dev/null | head -n 2

In a bash script, a ‘java .. jsontofrag’ exit status ($?) of 0 indicates a “good” parse, while an exit status of “1” indicates a bad parse.

This validation assumes the JSON is what would have been generated by a process that creates a JSON representation of the data, without the schema (as is done in GA4GH). An example generating process starting from a GA4GH schema would be:

java -jar avro-tools-1.7.7.jar random --schema-file ReadGroupSet.avsc --count 1 ReadGroupSet.datum

java -jar avro-tools-1.7.7.jar tojson --pretty ReadGroupSet.datum >> ReadGroupSet.json

The resulting JSON (in this case ReadGroupSet.json with dummy data embedded) can be easily edited to create bad-data test cases or examined to see the expected structure implied by the *.avsc

**Comment by jeromekelleher** [comment]
I'm confused --- the server should output JSON that is validated against the schema. We have quite a lot of technology in place to verify this, based on the Python Avro package's validation code. We have multiple test cases in place to ensure that the JSON we generate is valid (against the schema), and there is a even configuration variable (``RESPONSE_VALIDATION``) to validate the outgoing JSON, just in case. So, I'd be very surprised and disappointed if we were sending back invalid JSON. 

What version of the schema is the client using, and what version of the server are they running against? Like I say, if the server is generating invalid JSON, then this is a serious server bug and will be fixed immediately.

**Comment by wstidolph** [comment]
Followup comment - the problem which triggered this seems to be a field-ordering issue. The avro java library (ver 1.7.7, at least) expects the fields to come in the  order encountered in the SCHEMA$ string. One workaround is to use a different library (e.g., Jackson) to deserialize the wire JSON from the server into the avro-defined class.

**Comment by jeromekelleher** [comment]
Thanks for the followup @wstidolph. In my book, this is a bug in the Avro Java library, since 

> An object is an unordered set of name/value pairs.

according to http://json.org. By requiring a particular ordering of the keys in the JSON input, the Avro Java library (basically) doesn't support JSON. Since we're interested in interoperability here rather than conforming to Avro's arbitary requirements, I'm going to close this issue as it's not something we can resolve.
