### ISSUE TITLE
OIDC support for client scripts

### ISSUE THREAD

**Issue by jbu** [ga4gh/server#429]
If we have the server protected by OIDC, then the client must understand and cope with this.

**Comment by jeromekelleher** [comment]
Agreed. What are the options for authentication on the command line?

**Comment by jbu** [comment]
It's a bit awful because the CLI must somehow trigger the (google) auth process. The usual way to do this is to delegate to a browser, and then the browser displays an auth token that needs to be copied into the command line. It is possible for the client to spin up a web server and wait for the the oauth redirect itself, but this depends on firewall settings etc. I've done this before by just using the google auth libraries, but they might be too tied to google infrastructure, so I'll try and do it more according to spec (and with whatever pyoidc offers to help)

**Comment by jeromekelleher** [comment]
Actually, we have some methods in place to work with the Google auth process in the client library. I think we just have an API key which we provide when we're connecting to Google genomics. Would we be able to do something like this at the start:

1. Provide a HTML frontend on the server for logging in to whatever the appropriate auth provider is.
2. Once we are successfully logged in, just display the token we need on the screen. This can then be copied into a config file/command line argument.
3. The client then can then get the auth token from there. If it doesn't have a token and it's required, we just fail.

I know this is pretty horrible from a user experience perspective, but it would get us started at least...

**Comment by jbu** [comment]
After too much experimentation we just did as you suggested. The --key argument supplies a token that is included in the Authorization header. The token is shared between the ga4gh server and the client.

The token is generated by browsing to <server>/_login which does an oidc dance with whichever provider is configured (google and the dev OP have been tested) and ends up with a token displayed in the browser window, ready to be cut/pasted into the command line.

**Comment by jbu** [comment]
One thing is that the record about which tokens exist or are valid needs to be distributed between servers (unfortunately it's state). So we need to introduce a key/value service (memcache or redis or something). Any preferences?

**Comment by dcolligan** [comment]
Couldn't we just have a cache of state locally on each server and make it the responsibility of a load balancer (if one wanted to run multiple OIDC-enabled ga4gh servers) to route the requests intelligently via sticky sessions or some partitioning scheme or whatever?  If at all possible, it would be great to avoid another piece of software that users have to set up to run the server.

**Comment by pgrosu** [comment]
It might not be a bad idea to standardize the storage for resources as well.  Something like a distributed table for the token database with something like this:

Token ID | User ID | Granted Proxy (URI) | Resource Dataset | Resource Subdata Sets | Permissions | Expiration
-------------|-------------|-------------|-------------|-------------|-------------|-------------
     A SHA-256/512 hash           |  A SHA-256/512 hash           | If the token can be used through another | Reads | Fragment | read/write | 6/12/2015
     5CC1CC875DBA2E1ECFDB9971           |  B216A37BE27810           | http://www.ebi.ac.uk | Variants | Allele | read | 6/12/2015





~p

**Comment by jbu** [comment]
@dcolligan yes, we could do that. There's the issue that the token/userInfo map is currently in memory, so any server restarts will require the client to get a new token issued. If we want to work around this we need some sort of persistence, which could just be the filesystem, but it would be worth considering adding something that solves both these problems. Idempotent servers are generally good.

**Comment by dcolligan** [comment]
High performance was never a requirement for the server, and the number of users per server is likely going to be somewhat low (at least for now), so using the filesystem as a stopgap and then having a cache on top of it is not something I would be opposed to... thoughts, @jeromekelleher  ?

**Comment by jbu** [comment]
Another option is to abuse cookies. If all servers start with an identical signing key (distributed via env var) then they could hash the user token, sign and send as a cookie. Then whenever a client connects and passes the cookie, the server can verify it is valid, and then used the contained user info.

**Comment by jeromekelleher** [comment]
This is a tricky problem, which I don't have a strong opinion on. We do inevitably now have state, and we need to deal with that in a way that's 

1. Easy to install and configure from an admin's perspective;
2. Isn't totally terrible from a scalability perspective (but in practice, probably doesn't matter);
3. Easy to install and configure from an admin's perspective.

I guess for development, having keys persistent across server restarts is important. Otherwise, we'll end up hacking in some workarounds which might end up compromising the security. I'm not sure that implementing our own cache will save us much time though, since there must be pretty standard ways of dealing with this out there. For development, we can always start up the cache server (whatever it is) along with the OIDC provider. Perhaps we should start a new issue, and review the options there in more detail?

**Comment by david4096** [comment]
@dcolligan based on the existing test infrastructure, I believe this can be closed?
