### ISSUE TITLE
API endpoints defined in schema but not yet implemented should return 501

### ISSUE THREAD

**Issue by dcolligan** [ga4gh/server#431]
They currently return a 404

Based on discussion in #430

**Comment by dcolligan** [comment]
This would probably best be handled by also creating a `getMethods` in `_protocol_definitions` (which we can do without waiting for an error-free re-generation from a recent schema, since it will go at the bottom, separate from the rest of the data) which is used (along with `postMethods`) to check against the requested path in an error handler in `frontend.py`

**Comment by dcolligan** [comment]
@jeromekelleher did you have any ideas for creating the `getMethods` attribute in `_protocol_definitions` ?  We can't generate it in the same way since those endpoints don't correspond to a request/response class.

**Comment by jeromekelleher** [comment]
I was hoping there would be a way of getting at these using Avro. There is a method definition within the schema IDL, so I'd have hoped that the Avro library would provide a way of accessing it. I've gotten used to being disappointed by Avro though, so it might be as well to just define the functions in the frontend by hand.

**Comment by dcolligan** [comment]
Fixed in #454
