### ISSUE TITLE
server landing page should show all config

### ISSUE THREAD

**Issue by wstidolph** [ga4gh/server#435]
The server landing page ("/") should its actual values for all config variables settable in serverconfig.py. For example, someone using curl to bring back data might be concerned by response limits if they don't know the default page_size is 100. A link or mention of where in the doc one might find out how to set those variables might be nice static text, too.

**Comment by dcolligan** [comment]
We definitely don't want to show _all_ the config since some of the vars might be a security risk.  We have programmed this (in `frontend.py:ServerStatus.getConfiguration`) to be a whitelist, not a blacklist.

@wstidolph if you specify what values need to be added, I can make the appropriate change

**Comment by wstidolph** [comment]
Well,  I'm not a Flask programmer so I  don't know - is there a
comprehensive list I should choose from,  in the doc perhaps (sorry,  on
phone so tough to look up)?

**Comment by dcolligan** [comment]
http://flask.pocoo.org/docs/0.10/config/

and whatever custom values we have added in `ga4gh/serverconfig.py`

**Comment by dcolligan** [comment]
We also have documentation for our configuration values here

http://ga4gh-reference-implementation.readthedocs.org/en/develop/configuration.html#configuration-file

**Comment by jeromekelleher** [comment]
Agreed with @dcolligan --- we _definitely_ don't want to show all config variables. However, adding more stuff to make the server admin's life easier is always good.

@wstidolph, can you elaborate a bit on your page size example above? I don't really understand why a client would want to know this. If the client cares about the page size, it should set it explicitly. If not, it should just trust the server to send the response back in appropriately sized chunks.

**Comment by wstidolph** [comment]
The "client" can be a human. The client doesn't know how big the actual
response is, so default cutoffs like page size or max content length are
not clear (unless there is some indication in the response) ... in fact,
the very existence of a cutoff might not be immediately apparent to the
human if they're not savvy at this layer, if they're just pluggin in cURL
from an example or something. They just see less data than they expect
(unlike with an HTML page where we build in the little next/prev arrows for
data navigation).

And it makes the server admin's life easier to not have to go find code or
files to find out what a variable is, or to validate that a variable
actually made it from being a file entry to being effective in the server!

On Wed, Jun 3, 2015 at 1:20 AM, Jerome Kelleher <notifications@github.com>
wrote:

> Agreed with @dcolligan <https://github.com/dcolligan> --- we *definitely*
> don't want to show all config variables. However, adding more stuff to make
> the server admin's life easier is always good.
>
> @wstidolph <https://github.com/wstidolph>, can you elaborate a bit on
> your page size example above? I don't really understand why a client would
> want to know this. If the client cares about the page size, it should set
> it explicitly. If not, it should just trust the server to send the response
> back in appropriately sized chunks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ga4gh/server/issues/435#issuecomment-108242994>.
>



-- 
  Wayne Stidolph  | (831) 419 7146 | LinkedIn
<http://www.linkedin.com/in/waynestidolph> | Google+
<https://google.com/+WayneStidolph> | twitter
<https://twitter.com/#!/wstidolph> | personal blog
<http://waynedge.blogspot.com/>

**Comment by jeromekelleher** [comment]
@wstidolph --- sure, I agree we should make the admin's and client side developers lives easier. If there are config variables we can show the value of on the landing page without compromising security then I'm all for that.

**Comment by diekhans** [comment]
While showing config vars might be helpful for debugging, they
shouldn't be required for anything.

I am not sure what the max response size does, however partial
data should never be return without an error.  This is an
essential part of being a robust API.  Unlike Tweets, losing
data can be very serious in this type of application.

Not sure how we write a conformance test for this.  Might need
servers to actually implement something that forces an error.

With HTTP, there are two ways to do this:
     - set content length - requires the data be buffered in memory before sending
     - use chunked http - better for stream large amounts of data

HTTP is an amazingly good protocol if implementers actually read
the spec.  Remind me to tell you how we spent a year getting
Apache to fix chunked HTTP error handling in the proxy.  It turn
error into OK + truncated data.

As far as security goes, if there are any config variables that
would actually impact security, we should have a warning in the
install instructions.  Other than variables with password, there
shouldn't be any that truly impact security.  If so, we should
understand them.

**Comment by jeromekelleher** [comment]
@diekhans the MAX_RESPONSE_SIZE option is the approximate maximum size of a message we send back the client. Without this, a client can trivially run a memory exhaustion attack on the server by specifying a large query (say, all variants in chr1) with a large page size. We don't truncate the message, we just return a page with < page_size elements if this will cause us to go over the limit.

**Comment by diekhans** [comment]
Perfection!!!

**Comment by pgrosu** [comment]
So if the `MAX_RESPONSE_SIZE` is 10 megabytes and the amount of data we want to transfer is about 1 terabyte we would cache and transfer about 10^17 pages as a lower bound?  That could be a problem.

**Comment by dcolligan** [comment]
Fixed in #439
