### ISSUE TITLE
start and end don't get used in reads/search

### ISSUE THREAD

**Issue by Jeltje** [ga4gh/server#437]
I installed the server using pip install, as described at readthedocs. From the looks of it, this installs the stable branch (0.1.0b1). I also downloaded the example data so I could play around with curl queries.

When sending queries to reads/search, it looks like no matter what integer you fill in for start or end (including negative numbers), you always get the same results back:
`curl --data '{"readGroupIds":["low-coverage:HG00534"], "start":3, "end":10}' --header 'Content-Type: application/json' http://localhost:8000/v0.5.1/reads/search` 
has the exact same output as
`curl --data '{"readGroupIds":["low-coverage:HG00534"], "start":-100}' --header 'Content-Type: application/json' http://localhost:8000/v0.5.1/reads/search`
or any other combination I have tried (including not setting start). You always get back the first 100 reads in the file.

**Comment by dcolligan** [comment]
The command you should use to install is `$ pip install ga4gh --pre` as described here http://ga4gh-reference-implementation.readthedocs.org/en/stable/demo.html  It looks like you have the 0.1.0b1 version installed when you should be on 0.1.1.  Let us know if this problem is present on 0.1.1.

**Comment by Jeltje** [comment]
You are correct! I thought that was how I installed it but apparently I did something wrong. All is fine on 0.1.1.
Thanks!
