### ISSUE TITLE
Proposed data directory layout

### ISSUE THREAD

**Issue by jeromekelleher** [ga4gh/server#44]
Currently, we only support variant data derived from VCF, in either vcf.gz or wormtable format. We need to support other types of data as we move to support the full API. I suggest we use a designated file system layout for the data directory to discover the files and their relationships. An initial pass at this might be
```
dataDir/
     datasetId1/
           variants/
                 variantSetId1/
                       chrom1.vcf.gz
                       chrom2.vcf.gz
                 variantSetId2/
                       variants.wt
           reads/
                  [Some directory structure laying out BAM/SAM files]
           references/
                  [Some directory structure laying out references]
     dataSetId2/
           variants/
                  ....
           reads/
                  ....
           references
```  
That is, within the data directory, each directory `d` corresponds to a `Dataset` with ID `d`. Within a given dataset, we have three directories, called `variants`, `reads` and `references`. Within the `variants` directory, we then have more directories, one for each `VariantSet`. Within a `VariantSet` directory, we have a bunch of files that define these variants in what ever formats we support. 

For data within a given variant set, we could follow the existing convention used for the TabixBackend: we can split the variant set over as many files as we like, so long as we don't have data for the same chromosome in two files. I've deliberately mixed up wormtable and VCF format files in here. The input should detect the file type and make an instance of the appropriate handler based on the extension. If we don't support a given file type then we complain and quit. This would get rid of the currently very clumsy model of specifying `wormtable` or `tabix` as command line arguments to determine the type of backend to allocate.

We'd then just call the server using ``ga4gh_server dataDir`` for development and testing purposes. For deployment an absolute path to the required data directory in a config file would be all that is needed.

The idea is that we use the file system hierarchy to explicitly set out the structure of the data to be served. This keeps the number of configuration variables we need as we deal with more complex datasets down. The downside is that we do require a pretty complex file system hierarchy to specify the data to be served. One way we could alleviate this problem is by providing a tool to check the layout of the hierarchy and to raise errors if it's not well formed. This could also print some summaries about the data that's in there too, so that people can get an overview of what they're about to serve.

I've not filled out the reads and references section, as I don't understand this side of things all that well. Will this sort of decomposition make sense here too? Does this hierarchy capture the structure of the API, or is it too restrictive? Any feedback would be much appreciated!

**Comment by jeromekelleher** [comment]
We need to push ahead with the reads and references API, so I think we should use this approach for the moment unless someone has a better idea. We can always move over to something better later if it turns out to be a bad idea. Are there any objections?

**Comment by hershman** [comment]
+1 This looks immensely workable.

**Comment by kerrydc** [comment]
Proposed better idea: @Naburimannu is implementing configuration with defaults. Let's set some default directories in our default config and allow users to override via a config file. Longer term we will need to set many options (ACLs, size limits, logging retention, etc), and should consider an interactive setup script.

**Comment by jeromekelleher** [comment]
Would you mind fleshing out your idea with an example of what the config file would look like @kerrydc? I'm struggling to imagine how this approach would scale to hundreds of files (which we definitely need to support to be useful), so it would be good to talk through a concrete example here.

**Comment by jeromekelleher** [comment]
Closing this issue, as this has been resolved. For the record, the resolution is to have independent directories for each data set, and within the data set we have the required variants and reads subdirectories.
