### ISSUE TITLE
add navigation to responses - result set size, offset 

### ISSUE THREAD

**Issue by wstidolph** [ga4gh/server#440]
There should be navigational mechanisms for getting around in a query/response; e.g., I don't see how to know the total number of items in a reads/search response -  to get the total do I have to page through the response and count? Similarly, I should be able to set an Offset as a parameter to a query to fetch a page of the results starting from some point.

I suspect those sort of things could be useful not only as metadata for navigation (and testing) but in a data server it seems that's likely to be useful as just plain data: "how many items fit criteria X"

**Comment by jeromekelleher** [comment]
These are absolutely valid questions @wstidolph, which we absolutely should be able to answer. However, this is a schema issue: we can only implement what's defined in the schema. Please open this issue in the ga4gh/schemas repository.
