### ISSUE TITLE
error response missing comma (invalid JSON)

### ISSUE THREAD

**Issue by wstidolph** [ga4gh/server#445]
POST to <server root>:8000/variants/search of
```
{"variantSetIds":["1kg-phase1"],"referenceName":{"string":"22"}, "start":{"long":16050408}, "end": {"long":16052159}} 
```
and I get an error response, with a missing comma:
```
{
errorCode: 3424984409
message: "Internal Server Error"
}
```
My server's landing page reports:

GA4GH reference server 0.1.1

Protocol version 0.5.1

...
Configuration

Key	Value
DEBUG	True
REQUEST_VALIDATION	False
RESPONSE_VALIDATION	False
Data

VariantSets

1kg-phase1
1kg-phase3
ReadGroupSets

low-coverage
low-coverage:HG00533.mapped.ILLUMINA.bwa.CHS.low_coverage.20120522
low-coverage:HG00096.mapped.ILLUMINA.bwa.GBR.low_coverage.20120522
low-coverage:HG00534.mapped.ILLUMINA.bwa.CHS.low_coverage.20120522

**Comment by dcolligan** [comment]
Can't reproduce, and neither can @jeromekelleher 

It would be really weird if this was happening since we basically rely on the standard `json.dumps` to generate the return string.

**Comment by wstidolph** [comment]
This is a bug in the rendering of the response body by the chrome-extension REST Client I was using! ("Advanced Rest Client Application ver 3.1.9) The body from the server is OK... sorry.
