### ISSUE TITLE
Simulated references and reference sets need to be updated

### ISSUE THREAD

**Issue by jeromekelleher** [ga4gh/server#450]
At the moment, we cannot specify the number of references and reference sets when  we create a simulated backend. We need to provide a much more flexible interface (simular to variant sets) so that we can

1. Specify the number of reference sets;
2. specify the number of references per reference set;
3. generate random bases, for an arbitrarily large region _without_ storing the bases directly. This can be done using a similar method to the approach used for variants, where we use the position (plus another seed) to seed the generator.

Md5checksums aren't really supported as yet, so we can ignore these.

We should update the `test_simulated_stack.py` tests to thoroughly exercise this interface.

**Comment by dcolligan** [comment]
Fixed in #464
