### ISSUE TITLE
Datasets not found correctly by _getDatasetFromRequest

### ISSUE THREAD

**Issue by jeromekelleher** [ga4gh/server#453]
Currently, we try to get a dataset for all incoming search requests via the `_getDatasetFromRequest` method. This works fine for request where a `datasetIds` attribute is included, but is broken for others (searchVariants for example). Currently, if we have more than one dataset, the searchVariants method fails mysteriously. There are no plans to include a datasetIds attribute in the `searchVariants` method, so the premise of this function is flawed (which I should have caught in review; my bad).

When we have a dataset attribute, for example in readGroupSets generator, we can use `_getDatasetFromRequest`, but removing the check to see if it has the `datasetIds` attribute (as it shouldn't be called on any request object that doesn't have a datasetIds attribute).

When we do not have a dataset attribute (such as in searchVariants), we need some method of finding the dataset that a particular variant set belongs to; there are two basic options I think:

1. Maintain a map of variantSetIds to datasets in the backend; or 
2. Make a hierarchical ID scheme such that we can always derive the datasetId from a variantSetId. For example, if we make variantSetIds in the form `{dataSetId}:{localVariantSetId}`, we can decompose the datasetId quickly, allowing us to find the relevant dataset.

I think (2) is the best and simplest option. We'll need to revise the ID generation code throughout the datamodel code, and systematise it. This is overdue though.

**Comment by dcolligan** [comment]
I like (1) since it requires less changes to the wire protocol.  Plus, this should only be a temporary measure until we bring the schemas up to date, right? (Which, I know, could be a long time...)  (1) also only works if we can assume duplicate variant set ids are not present, which I think is a fair assumption.

**Comment by jeromekelleher** [comment]
I don't think there are any changes to the schema in the pipelines that would make any difference to this @dcolligan. We're not changing the wire protocol in any way: ids are server internal values, which are opaque to users. We can do whatever we want with them. 

I think it's a bit onerous in any case to require that all the variant set IDs (== directory name) within different data sets are different. Suppose I have a hundred datasets, and each of these contains 10 variant sets. I would like to put these in directories called vs1, vs2, ..., vs10 within their respective datasets. If we leave IDs as they are, then I can't do this and I have to invent unique names for variant sets across all datasets. I've already started hitting on this, and it's a pain. I want to be able to move datasets in and out by just mv'ing them. By requiring globally unique directory names for variantsets I end up having to do lots of renaming, which is very tedious.

**Comment by dcolligan** [comment]
Good point.  Would the consistent thing to do be to change all the ids now to compound ids (`datasetId:formerId`) and ignore all `datasetIds` attributes in requests?

**Comment by jeromekelleher** [comment]
Why would we need to ignore the `datasetIds` attributes? We would only make use of the "datasetId:containerId:objectId" ID structure in situations when we get a GET request for a an object where we need to find its dataset. Take ``getVariantSet(id)`` as an example: there is no datasetId included in the query, so we use the variantSetId to find out which dataset it belongs to.

**Comment by dcolligan** [comment]
Fixed in #474
