### ISSUE TITLE
Unable to use referenceId, start fields in /reads/search API call

### ISSUE THREAD

**Issue by danvk** [ga4gh/server#455]
Following the [demo instructions][1], I can query _all_ reads:

```
$ curl --data '{"readGroupIds":["low-coverage:HG00534.mapped.ILLUMINA.bwa.CHS.low_coverage.20120522"]}' --header 'Content-Type: application/json' http://localhost:8000/v0.5.1/reads/search
(many results!)
```

If I try to query a particular range, however, I get an error:

```
$ curl --data '{"readGroupIds":["low-coverage:HG00534.mapped.ILLUMINA.bwa.CHS.low_coverage.20120522"], "referenceId": "1", "start": 129650, "stop": 129670}' --header 'Content-Type: application/json' http://localhost:8000/v0.5.1/reads/search | jq .
{
  "errorCode": 2019025445,
  "message": "only one of referenceId and referenceName can be specified"
}
```

This is odd, since I didn't specify `referenceName` in the request (in fact, it's not even a valid field in [`SearchReadsRequest`][2]). Dropping the `referenceId` field, I get an even stranger error:

```
$ curl --data '{"readGroupIds":["low-coverage:HG00534.mapped.ILLUMINA.bwa.CHS.low_coverage.20120522"], "start": 129650, "stop": 129670}' --header 'Content-Type: application/json' http://localhost:8000/v0.5.1/reads/search | jq .
{
  "errorCode": 3424984409,
  "message": "Internal Server Error"
}
```

Looking at the server logs, I see this:

```
  File "pysam/calignmentfile.pyx", line 572, in pysam.calignmentfile.AlignmentFile.getrname (pysam/calignmentfile.c:8026)
ValueError: reference_id 129650 out of range 0<=tid<86
```

i.e. it looks like the `start` value is being interpreted as a `referenceId`!

I'd appreciate some help figuring out why this API endpoint is behaving so oddly. Thanks!

[1]: http://ga4gh-reference-implementation.readthedocs.org/en/latest/demo.html
[2]: https://github.com/ga4gh/schemas/blob/84927c4cc9a74a3db310026de8b31cdca8bbcfd0/src/main/resources/avro/readmethods.avdl#L16

**Comment by dcolligan** [comment]
Thanks for finding these issues.  I'll have a PR up to fix this soon.

**Comment by dcolligan** [comment]
Fixed in https://github.com/ga4gh/server/releases/tag/v0.1.2

Thanks for the excellent bug report, @danvk !
