### ISSUE TITLE
Server performance benchmarking needed

### ISSUE THREAD

**Issue by jeromekelleher** [ga4gh/server#46]
As the reference server evolves, we need to have a mechanism to keep track of how the server's performance changes as we add new features. There is currently a crude performance benchmark built into the client program, but this is not satisfactory as it includes network latency and client side JSON parsing in its timings.

One way that we might get a better handle on query performance is to build a separate benchmarking program that takes a dataset (in the same format as the server program, whatever that turns out to be --- see discussion at #44), and runs some standard queries directly against the Backend implementation. That is, we cut out the HTTP layer entirely and run the queries against the GA4GH endpoints (e.g., `searchVariants(request)`, where request is a `SearchVariantsRequest` object). We should get the response from these functions in the form of JSON strings. 

This should allow us to get some good numbers for how our backend implementation is performing, without the noise of HTTP servers, network latency, JSON parsing etc, etc. We might also track memory usage, following the approach taken by @Naburimannu  in #10.

What are the important aspects that we need to track? What standard queries should we use? @benedictpaten, any thoughts here?

**Comment by Naburimannu** [comment]
Some naive numbers using timer.clock() on my workstation, working one level higher than @jeromekelleher suggested by logging in server/views.py:handleHTTPPost()

ga4gh_client variants-search http://localhost:8000 1000g_2013 -r1 -e 60000 -c HG03279 | wc
 * trivial sample query from the documentation, produces 3 pages of output
 * 0.005 - 0.01 seconds per page (somewhat higher the first time the server gets this query)
 * adding a console dump from heapy (print(hp.heap()), qv https://github.com/Naburimannu/server/tree/heapy) adds 0.25 seconds
 * similar cost of calling print(hp.heap().domisize) for a summary of total heap size

ga4gh_client variants-search http://localhost:8000 1000g_2013 -e 100000 -r2 -c'*' | less -S
 * stress test query motivating https://github.com/ga4gh/server/issues/10
 * 3.9 - 4.6 seconds per page
 * print(hp.heap()) adds about 3.25 seconds
 * print(hp.heap().domisize) adds about 2.5 seconds

Until we address the problem in #10 we can't have always-on memory monitoring, and we probably don't want it always-on.

timer.clock() is deprecated in Python 3, but it looks like time.process_time() is a drop-in replacement.

There are tradeoffs to consider between timer/profiler weight and accuracy. If we're considering adding monitoring as well as logging, I'd like to have the simple timer in there by default, and let the environment toggle whether or not the running server is doing complex timings and memory use tracking.

**Comment by Naburimannu** [comment]
https://github.com/Naburimannu/server/commit/a464e257fdb5e7359ae5993db1ce903996759cfd is a sample naive implementation. It suggests that in the stress test query, we're typically spending 3.5 seconds in the endpoint and 1 second on serialization.

**Comment by jeromekelleher** [comment]
These are interesting numbers, and I think having the facility will to track these will certainly be useful. I'd be in favour of including something like this, as it also gives us a good benchmark for comparing the different VariantSet implementations.

**Comment by Naburimannu** [comment]
For reference, there's already a ga4gh_client benchmark command, although that doesn't seem to do any repetition and has possible network overhead

**Comment by jeromekelleher** [comment]
The `benchmark` client command is very crude and of limited use. Feel free to remove it if you think it's a distraction.

**Comment by Naburimannu** [comment]
Exploratory profiling with perf suggests that our time is entirely in spent in Python; all aggregated kernel calls are 5%, JSON is 3%, and wormtable's C code is *way* down the list:

```
+  43.04%  python  python                       [.] 0x000000000013eac0
+  13.15%  python  python                       [.] PyEval_EvalFrameEx
+   5.70%  python  [kernel.kallsyms]            [k] 0xffffffff8104f45a
+   3.25%  python  _json.x86_64-linux-gnu.so    [.] 0x000000000000a3b2
+   2.53%  python  python                       [.] PyUnicodeUCS4_Decode
+   2.49%  python  python                       [.] PyObject_GetAttr
+   2.00%  python  python                       [.] PyString_FromFormatV
+   1.98%  python  python                       [.] PyString_FromStringAndSize
+   1.70%  python  python                       [.] PyObject_SetAttr
+   1.37%  python  libc-2.19.so                 [.] __memcpy_sse2_unaligned
+   1.24%  python  python                       [.] PyList_Append
+   1.23%  python  python                       [.] PyTuple_New
+   1.03%  python  python                       [.] PyDict_SetItem
+   0.94%  python  libc-2.19.so                 [.] _int_malloc
+   0.93%  python  python                       [.] PyDict_GetItem
+   0.82%  python  libc-2.19.so                 [.] __ctype_b_loc
+   0.82%  python  libc-2.19.so                 [.] memset
+   0.79%  python  libc-2.19.so                 [.] _int_free
+   0.74%  python  python                       [.] PyFrame_New
+   0.69%  python  libc-2.19.so                 [.] malloc
+   0.66%  python  python                       [.] _PyString_Resize
+   0.62%  python  python                       [.] _PyObject_GC_New                        
```

Using cProfile to look inside python suggests that WormtableVariantSet's use of zip() and map() is expensive; at runtime the only explicit caller of zip() is convertVariant(), and of map() is convertGenotype():

```
         15898695 function calls in 20.696 seconds

   Ordered by: internal time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
  2253600    5.741    0.000    5.741    0.000 {zip}
      900    5.702    0.006   20.463    0.023 variants.py:142(convertVariant)
  2253606    3.143    0.000    3.143    0.000 {map}
  2253600    2.999    0.000    7.346    0.000 variants.py:122(convertGenotype)
  2253600    1.306    0.000    1.306    0.000 _protocol_definitions.py:115(__init__)
  2254866    0.889    0.000    0.889    0.000 {method 'split' of 'str' objects}
  2253600    0.316    0.000    0.316    0.000 variants.py:111(convertPhaseset)
  2299788    0.282    0.000    0.282    0.000 {method 'append' of 'list' objects}
      909    0.204    0.000   20.687    0.023 variants.py:193(getVariants)
      900    0.073    0.000    0.073    0.000 {method 'items' of 'dict' objects}
     1800    0.007    0.000    0.007    0.000 {method 'format' of 'unicode' objects}
     3615    0.006    0.000    0.007    0.000 variants.py:100(convertInfoField)
    37152    0.006    0.000    0.006    0.000 wormtable.py:110(get_position)
        9    0.006    0.001    0.008    0.001 wormtable.py:639(translate_columns)
        9    0.005    0.001    0.017    0.002 wormtable.py:1128(cursor)
    26403    0.003    0.000    0.003    0.000 {isinstance}
      909    0.002    0.000   20.694    0.023 backend.py:115(variantsGenerator)
      900    0.002    0.000    0.002    0.000 _protocol_definitions.py:1576(__init__)
        9    0.000    0.000    0.000    0.000 wormtable.py:616(columns)
        9    0.000    0.000    0.001    0.000 protocol.py:114(fromJsonDict)
...
```

The map() is being used to coerce parsed genotypes from string to int. Unfortunately, the protocol says that GACall.genotype is [int], but we don't seem to do anything with them and so our code runs just fine if we leave them as strings.

The zip() is being used for clean pythonic inputs to a nested parsing for loop in convertVariant().

```
            for (info, col), rowPosition in zip(self._sampleCols[callSetId],
                                                rowPositions):
```

We *can* replace it with a more C-like initialization:

```
# min() is unreasonably expensive here?
#            maxLen = min(len(self._sampleCols[callSetId]), len(rowPositions))
            maxLen = len(rowPositions)
            for i in range(maxLen):
                (info, col) = self._sampleCols[callSetId][i]
                rowPosition = rowPositions[i]
```

These two changes together save roughly 10% of CPU time, reducing cumulative time reported by the profiler in convertVariants from over 20 seconds to under 19. The server_benchmark script is a bit more noisy than I'm comfortable with yet, at least for default repeat and page counts.

As another aside, we spend 5% of our time in ```GACall.__init__()```:

```
    def __init__(self):
        self.callSetId = None
        self.callSetName = None
        self.genotype = []
        self.genotypeLikelihood = []
        self.info = {}
        self.phaseset = None
```

Sad, but I don't know what to do about it?

**Comment by jeromekelleher** [comment]
Thanks for these numbers @Naburimannu, this is very interesting. My take on it is that there's no obvious bottleneck, and we can be reasonably happy about where we are perf-wise, for the moment at least.

It would be very interesting to use this machinery to compare how we do when we use the Tabix backend though... Fancy hooking this up to @kerrydc's code and seeing how it compares?
