### ISSUE TITLE
Speed up test_intervals.py

### ISSUE THREAD

**Issue by dcolligan** [ga4gh/server#465]
The `test_intervals.py` test doubles the amount of time that the entire test suite takes to run.  We should optimize it!

**Comment by dcolligan** [comment]
Here are the times for all current tests (sorted by time at the bottom half of the file): https://gist.github.com/dcolligan/39f4ce212f9434ecc0e2

**Comment by jeromekelleher** [comment]
OK, that looks pretty bad --- It didn't hit the machine I'm working on that badly. I'll take a look when I get a chance.

**Comment by dcolligan** [comment]
Closed in #546
