### ISSUE TITLE
Optionally read from encrypted data files

### ISSUE THREAD

**Issue by kerrydc** [ga4gh/server#47]
Allow users to specify a key and possibly encryption scheme along with data files. We should accept the key, and decrypt data before processing.
The security doc (http://genomicsandhealth.org/security-infrastructure-read-online#AccessControl) says in 4.6:
"Each stakeholder that stores genomic or clinical data will use strong encryption to encrypt the data for storage."
We should therefore cut over to requiring data encryption in the long run. I lean towards private key encryption, for simplicity and portability. Supporting AES using pycrypto would be a good first step.

**Comment by jeromekelleher** [comment]
Closing this due to current impracticality. Until htslib supports reading from encrypted files we cannot do it.
