### ISSUE TITLE
doc suggestion: add fedora/redhat note to demo doc install

### ISSUE THREAD

**Issue by wstidolph** [ga4gh/server#470]
(Just to save Fedora users from a a little research)

'demo' doc says for ubuntu/debian to prep with:

`$ sudo apt-get install python-dev python-virtualenv zlib1g-dev`

on Fedora 22+ (current), the equivalent would be:

`$sudo dnf install python-devel python-virtualenv zlib-devel`

**Comment by jeromekelleher** [comment]
Great idea @wstidolph --- would you like to make a PR based on this? Just edit `docs/source/demo.rst` with the above and you're done.

**Comment by jeromekelleher** [comment]
Closed in #471

**Comment by wstidolph** [comment]
I just looked at the docs as rendered on readthedocs (http://ga4gh-reference-implementation.readthedocs.org/en/stable/demo.html#demo) and the line of fedora libraries didn't render, so I assume I did something wrong with the rst ...

**Comment by dcolligan** [comment]
You're right.  And the reason that wasn't caught is because we don't build the docs in CI in the stable branch.  We should do that.
