### ISSUE TITLE
Write audit logs for all requests and responses

### ISSUE THREAD

**Issue by kerrydc** [ga4gh/server#48]
Access to data should be logged. Flask provides a logging framework, so that may be a good start. Once we have authentication we should log user IDs along with actions.

**Comment by dcolligan** [comment]
Any preference of where we should put the log file?  It should probably be a command line option, but what should the default be?

**Comment by jeromekelleher** [comment]
There's a question here for deployment also - do we log to the HTTP server logs, or do we make our own separate log? What's the common practice for this sort of thing in Flask?

**Comment by dcolligan** [comment]
Flask looks like it provides a thin wrapper to python's standard logging package: http://flask.pocoo.org/docs/0.10/quickstart/#logging

The Flask docs page for apache config doesn't say anything about logs: http://flask.pocoo.org/docs/0.10/deploying/mod_wsgi/

Here's a Flask docs page on using some of the logging.handlers handlers: http://flask.pocoo.org/docs/0.10/errorhandling/#logging-to-a-file

From this I'm inferring that we make our own log, but if anyone else has an opinion, feel free to chime in.

In any event, the difference between logging to one place or another should be just a change in the initial logger setup configuration.

**Comment by dcolligan** [comment]
Closing for ambiguity / already implemented... see discussion in #85
