### ISSUE TITLE
API call to list references for a readGroup

### ISSUE THREAD

**Issue by danvk** [ga4gh/server#486]
Unless I'm missing something, it doesn't seem like there's a way to get a list of `referenceId`s/`referenceName`s for a BAM file using the API. This would be really helpful for determining if, say, the alignments are using `chr19` or `19` as a reference name.

**Comment by jeromekelleher** [comment]
This is indeed a problem @danvk. Currently, we don't have any proper support for linking references to either reads or variants, and this needs to be addressed. I've opened issue #489 to discuss how we might do this.

I'm not sure if your question goes further than this though. Do you think the schema itself supports the functionality you need, or is this just a missing feature in the server? If the functionality is not possible in the schema, then this issue needs to be raised on the ga4gh/schemas issues list.

**Comment by danvk** [comment]
I am in fact proposing an extension to the API. I've opened an issue in ga4gh/schemas.
