### ISSUE TITLE
Cohesive support for references across variants and reads

### ISSUE THREAD

**Issue by jeromekelleher** [ga4gh/server#489]
Currently, we have basic support for references, but we have no way of linking read and variant data to this. This is a major issue in terms of data integrity, and needs to be resolved. Informally, we need some way for the server admin to specify which reference set/reference their reads and variants relate to. 

How do we input this information? For example, do we include a `references.yml` file within the `reads` and `variants` data directories, which specifies the mapping we want? Should we consider a more general metadata input mechanism at this point? 

One of the key tasks of the input validation tool (see #417) would be to check if the specified mapping is correct.

It would be good to discuss the various options for this problem here, and how we are to ensure that coherent data (in terms of reference information) is served to the client.

**Comment by dcolligan** [comment]
Well one decision that seems necessary here is centralized metadata vs distributed (say, in each variantset, etc. folder) metadata.  The same person is probably going to be deploying the entire server, so I don't think it matters that much.  (Unless there's some permissions / access thing there I'm not thinking of, but I don't think there is.)

**Comment by jeromekelleher** [comment]
I've added this to the Sync with schemas task, as we need to have good support for linking data across variants, references and reads before we can say we have implemented these three core APIs.

**Comment by dcolligan** [comment]
@jeromekelleher suppose we did go the `references.yml` route... could you flesh out how you would want that document structured?

**Comment by jeromekelleher** [comment]
I don't really know -- I guess we just have a configuration option for all the stuff we can't infer/can't calculate on the fly? I was thinking that perhaps JSON would be more appropriate, if we're thinking of this directory structure as ultimately being generated by an import program rather than being done by hand.

So, to be concrete, we'd have a JSON document that contains, ``md5checksum``, ``sourceAccessions``, ``isDerived``, etc for each reference. We could require that the metadata file for a given reference has the same basename as the FASTA file, so if we had ``chr1.fa``, we'd also look for ``chr1.json``, which should contain this stuff. It should be nice and easy to generate the json file using your download script for 1000 genomes.

How does this sound?

**Comment by macieksmuga** [comment]
@jeromekelleher should I move this off baseline for now?

**Comment by jeromekelleher** [comment]
No, I think this is important @macieksmuga. We need to support references properly, and this is the way to do it.
