### ISSUE TITLE
Strand is always "positive"

### ISSUE THREAD

**Issue by danvk** [ga4gh/server#491]
See `TODO` in [`server/reads.py`][1]. This surprised me when I was trying to debug a disagreement between `samtools` and the GA4GH server.

[1]: https://github.com/ga4gh/server/blob/40bdc60eee6e82981abb8f18e27f7be88c7193d9/ga4gh/datamodel/reads.py#L265

**Comment by jeromekelleher** [comment]
Thanks for all digging up these issues @danvk, the reads code does need a little love. The issue really is that we currently don't have anyone developing on the server who understands read data to any real degree, so we're doing a lot of guesswork. It's great to have some more eyes on the code.

**Comment by dcolligan** [comment]
There's an issue open for the general problem @jeromekelleher is referring to 

https://github.com/ga4gh/server/issues/347

**Comment by dcolligan** [comment]
Should we close this issue?  It seems to be addressed by the more general issue #347

**Comment by jeromekelleher** [comment]
Let's keep this one open until we have a specific fix (we might forget to address this particular problem as part of the cleanup).

**Comment by macieksmuga** [comment]
Is this still an issue? Should I include it in the `baseline` milestone?

**Comment by jeromekelleher** [comment]
Yes, this is still an issue. I don't think it's a baseline issue. We know we have problems with our read handling, and we need some expert input to make sure we're interpreting the spec properly.

**Comment by diekhans** [comment]
Suggest asking the file formats task team for a review
