### ISSUE TITLE
Local index files from remote fetch not getting cleaned up property

### ISSUE THREAD

**Issue by dcolligan** [ga4gh/server#500]
On the current `develop` branch:
```
$ git status -s
$ nosetests tests/end_to_end/test_remote_fetch.py
..
----------------------------------------------------------------------
Ran 2 tests in 3.429s

OK
$ git status -s
?? chr1.vcf.gz.tbi
?? wgEncodeUwRepliSeqBg02esG1bAlnRep1_sample.bam.bai
```
We should investigate why these downloaded index files are not getting cleaned up properly.

**Comment by dcolligan** [comment]
One solution is to add a tearDown method to these tests, but that doesn't address the root cause:
```
    def tearDown(self):
        # clean up downloaded local index file
        for indexFile in glob.glob("*.tbi"):
            os.remove(indexFile)
```

**Comment by dcolligan** [comment]
Okay, here's the problem: the downloaded index files never get into the temporary directory because they are only downloaded when the first operation is performed against the remote file (say, a reads-search), not during initialization, as we erroneously assume in the code.  So here is what happens:

1) server startup -- temp dir is created, but nothing is moved into it, since no index files exist
2) fetch -- the index file is downloaded to the pwd
3) server shutdown -- the empty temp dir is deleted, but the index files in the pwd remain

Possible solutions:

A) perform some dummy search operation against the remote file immediately after initialization (troublesome; would have to know values inside file for meaningful query) to download the file and move it into the temp dir
B) for each remote file, keep track of whether it has had a successful request against it or not; if that transitions from no to yes, check for the downloaded file and move it to the temp dir
C) forget the whole temp dir thing and just delete all of the index files from the pwd on server shutdown
D) come up with some new non-urls.json design

I guess I don't like A and B because they involve changing the server's pwd, which is probably not a good idea.  C is probably the temporary solution I favor.

**Comment by jeromekelleher** [comment]
I'm not a big fan of (C) I'm afraid. In my view, programs should _never_ write anything into PWD. What if the user has files of the same name in there? Also, this doesn't get around the problem of multiple processes writing the same files in the same directory (a nasty mess).  I'm not sure what PWD is for an WSGI process running in apache; it might not even be writable. Writing to the working directory is evil, and htslib's behaviour here is really nasty. Hopefully this is being fixed at the moment though, and we'll be able to come up with a sensible design some time soon.

What we have used to work before --- perhaps this is a consequence of the file handle cache?

**Comment by dcolligan** [comment]
Oh, good call!  The commit before the file cache merge `068caf51beaf1ad840c6ab3ab84b8a2b9dc3865e` does not feature this issue but the one in which the cache is merged in `40bdc60eee6e82981abb8f18e27f7be88c7193d9` does.  So it indeed looks like the file handle cache introduced this problem.

**Comment by bioinformed** [comment]
+1 for requesting htslib API support for:

   1. whether remote index files are saved
   2. controlling where remote index files are written

-Kevin

**Comment by dcolligan** [comment]
Just filed this: https://github.com/samtools/htslib/issues/247

**Comment by dcolligan** [comment]
The htslib issue I filed has been closed; apparently they added support for this last month.

**Comment by dcolligan** [comment]
related: https://github.com/pysam-developers/pysam/issues/87

**Comment by dcolligan** [comment]
@jeromekelleher if we close this issue we should open up another one (with the blocked tag) that describes the root problem

**Comment by jeromekelleher** [comment]
Good spot @dcolligan  --- I think github closed this issue automatically.
