### ISSUE TITLE
Pin versions for all pypi dependencies?

### ISSUE THREAD

**Issue by jeromekelleher** [ga4gh/server#502]
We depend on quite a lot of upstream libraries, and these can and do make breaking changes to their APIs. We should probably start pinning these to specific versions to prevent this, and perform periodic, tested upgrades to new library versions.

Any objections to this?

**Comment by dcolligan** [comment]
Good idea; we probably should have done this a while ago.

**Comment by dcolligan** [comment]
Fixed in #507
