### ISSUE TITLE
Docker images need updating with new lib requirement

### ISSUE THREAD

**Issue by jeromekelleher** [ga4gh/server#505]
PR #504 updates the documentation to include a new library we need to apt-get. The docker images should be updated to reflect this change too. This is the underlying issue for #484.

**Comment by dcolligan** [comment]
I was thinking... should we make sure that the docker image builds as part of our CI?  If it's something that we're supporting, it would be good to know when it breaks...

**Comment by jeromekelleher** [comment]
Good idea --- does Travis support this?

**Comment by dcolligan** [comment]
Looks like the short answer is no: http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/

**Comment by jeromekelleher** [comment]
It looks like it might be possible in the future though, we should keep an eye on it. Anyway, we still need to update the images to get these new libs in.

**Comment by dcolligan** [comment]
Fixed in #561
