### ISSUE TITLE
Update example data

### ISSUE THREAD

**Issue by danvk** [ga4gh/server#509]
I'd like to run `ga4gh_server` from `origin/develop`, but I'm getting this error:

```
  File "/Users/danvk/github/ga4gh-server/ga4gh/datamodel/datasets.py", line 141, in __init__
    for variantSetId in os.listdir(variantSetDir):
OSError: [Errno 2] No such file or directory: 'ga4gh-example-data/reads/variants'
```

Has the expected data layout changed from what's provided at `http://www.well.ox.ac.uk/~jk/ga4gh-example-data.tar`? If so, it would be helpful to provide an updated version of the example data that does work.

**Comment by jeromekelleher** [comment]
Yes, the layout has changed. To make this work on the new layout, use
```
cd ga4gh-example-data
mkdir dataset1
mv reads variants dataset1
```
I'm not sure what the right thing to do is re the tarball. Certainly the existing one shouldn't change until we update the released version. Perhaps we should make a new tarball with a versioned name, and update the docs for develop to point to this?

**Comment by danvk** [comment]
Yes, you should version the sample data.

Moving `reads` and `variants` into a `dataset1` directory lets the server run, but it doesn't look like cross-linking of references is working (see my command on the linked issue).

**Comment by danvk** [comment]
(probably because `ga4gh-example-data/references` is empty)

**Comment by jeromekelleher** [comment]
References support is crude at the moment @danvk --- we're basically not checking if things link up at all, and we're not quite sure how to do this. See issue #489 and also #312. We definitely want to have some example data in which all of this stuff links up (reads, references and variants), but we don't have it at the moment.

**Comment by jeromekelleher** [comment]
I've updated the example data to have the right format. It's at http://www.well.ox.ac.uk/~jk/ga4gh-example-data-v1.0.tar.

**Comment by danvk** [comment]
Thanks. Just to be clear, the `references` directory is still empty?

**Comment by jeromekelleher** [comment]
Yes --- sorry @danvk, I just don't have the time (or the knowledge) to make the example data link up correctly. We could drop in some arbitrary stuff in as the reference, but I think this would do more harm than good. Ideally, we want 

1. A small chunk of the 1000G reference
2. A 1kg-phase1 dataset containing some reads and variants over this part of the reference
3. A 1kg-phase3 dataset (likewise).

I'll push #489 up the priority list and see if we can get some volunteers to help, as we really are slightly crippled without good data. Sorry to keep you waiting on this.

**Comment by macieksmuga** [comment]
@jeromekelleher would you like to standardize on using the compliance dataset I'm putting together?

**Comment by jeromekelleher** [comment]
@macieksmuga, no I think we should keep these separate. The script @dcolligan wrote is going to be the basis of the next example data drop, which I guess we should aim to do after #489 and #574 are fixed.

**Comment by danvk** [comment]
@jeromekelleher is the server in a usable state at `HEAD` right now? I'm having trouble issuing any `/search/reads` requests:

```
$ curl --data '{"datasetIds":["dataset1"], "name":null}' --header 'Content-Type: application/json' http://localhost:8000/reads/search
{"errorCode": 996818875, "message": "Unmapped reads are not yet supported; please specify a reference"}%
```

My `ga4gh-example-data` dir looks like this:
```
find ga4gh-example-data | grep -v 1kg-phase
ga4gh-example-data
ga4gh-example-data/dataset1
ga4gh-example-data/dataset1/reads
ga4gh-example-data/dataset1/reads/low-coverage
ga4gh-example-data/dataset1/reads/low-coverage/HG00096.mapped.ILLUMINA.bwa.GBR.low_coverage.20120522.bam
ga4gh-example-data/dataset1/reads/low-coverage/HG00096.mapped.ILLUMINA.bwa.GBR.low_coverage.20120522.bam.bai
ga4gh-example-data/dataset1/reads/low-coverage/HG00533.mapped.ILLUMINA.bwa.CHS.low_coverage.20120522.bam
ga4gh-example-data/dataset1/reads/low-coverage/HG00533.mapped.ILLUMINA.bwa.CHS.low_coverage.20120522.bam.bai
ga4gh-example-data/dataset1/reads/low-coverage/HG00534.mapped.ILLUMINA.bwa.CHS.low_coverage.20120522.bam
ga4gh-example-data/dataset1/reads/low-coverage/HG00534.mapped.ILLUMINA.bwa.CHS.low_coverage.20120522.bam.bai
ga4gh-example-data/dataset1/variants
ga4gh-example-data/README
ga4gh-example-data/references
```

**Comment by jeromekelleher** [comment]
Sorry about this @danvk --- we've changed the input file format again because of the incorrect mapping from ReadGroupSets to bam files. See #618 for an overview.

To fix this, move everything in `reads/low-coverage` into `reads`, and delete the low-coverage directory. Apologies again for the churn. We'll have a solid example data set by the end of the week and the input format should stabilise again for a good while after that.

**Comment by danvk** [comment]
Thanks @jeromekelleher. My directory now looks like this:

```
$ find ga4gh-example-data | grep reads
ga4gh-example-data/dataset1/reads
ga4gh-example-data/dataset1/reads/HG00096.mapped.ILLUMINA.bwa.GBR.low_coverage.20120522.bam
ga4gh-example-data/dataset1/reads/HG00096.mapped.ILLUMINA.bwa.GBR.low_coverage.20120522.bam.bai
ga4gh-example-data/dataset1/reads/HG00533.mapped.ILLUMINA.bwa.CHS.low_coverage.20120522.bam
ga4gh-example-data/dataset1/reads/HG00533.mapped.ILLUMINA.bwa.CHS.low_coverage.20120522.bam.bai
ga4gh-example-data/dataset1/reads/HG00534.mapped.ILLUMINA.bwa.CHS.low_coverage.20120522.bam
ga4gh-example-data/dataset1/reads/HG00534.mapped.ILLUMINA.bwa.CHS.low_coverage.20120522.bam.bai
```

What should my `/reads/search` request look like?

```
$ curl --data '{"datasetIds":["dataset1"], "readGroupIds": ["HG00096.mapped.ILLUMINA.bwa.GBR.low_coverage.20120522"], "referenceId": "chr1"}' --header 'Content-Type: application/json' http://localhost:8000/reads/search
{"errorCode": 758389611, "message": "No object of this type exists with id 'HG00096.mapped.ILLUMINA.bwa.GBR.low_coverage.20120522'"}
```

**Comment by jeromekelleher** [comment]
You need to get the ID for the readgroup you're interested in. The easiest way to do this is to point your web browser at the server root, and it should show you the names (e.g. "HG00096.mapped.ILLUMINA.bwa.GBR.low_coverage.20120522") and IDs (e.g. "ZGF0YXNldDE6bG93LWNvdmVyYWdlOkhHMDAwOTYubWFwcGVkLklMTFVNSU5BLmJ3YS5HQlIubG93X2NvdmVyYWdlLjIwMTIwNTIy"). The IDs for the example data are absurdly long right now: we'll try and fix those for the next version of the data.

**Comment by danvk** [comment]
OK, now I'm back to the "please supply a reference" error. Maybe I'll just wait for a release & docs update :)

```
$ curl --data '{"datasetIds":["dataset1"], "readGroupIds": ["ZGF0YXNldDE6bG93LWNvdmVyYWdlOkhHMDAwOTYubWFwcGVkLklMTFVNSU5BLmJ3YS5HQlIubG93X2NvdmVyYWdlLjIwMTIwNTIy"]}' --header 'Content-Type: application/json' http://localhost:8000/reads/search
{"errorCode": 996818875, "message": "Unmapped reads are not yet supported; please specify a reference"}
```

**Comment by jeromekelleher** [comment]
Ah, I think I see what's wrong here. We've starting fixing the crappy reference handling, and now we require a reference to be specified. I think you should be OK if you provide a reference ID. Try adding ``"referenceId":"R1JDaDM4LXN1YnNldDox"`` to your request. See the landing page for the IDs of the references that are in the example data.

**Comment by jeromekelleher** [comment]
The example data has been updated, and a docs update is in progress. This is the default output of the ``scripts/download_data.py`` script.

Try out:
```
http://www.well.ox.ac.uk/~jk/ga4gh-example-data-v2.0.tar
```

**Comment by danvk** [comment]
Hi @jeromekelleher, just wanted to ask about the status of the docs update you mentioned.

**Comment by jeromekelleher** [comment]
The docs should be updated on 

http://ga4gh-reference-implementation.readthedocs.org/en/develop/configuration.html

now @danvk. Just make sure that you're following the docs for the ``develop`` branch, as the ``stable`` docs are very old now. If you see anything that could be clearer please open an issue here!

**Comment by danvk** [comment]
Thanks for the pointer. The `README.md` file on the `develop` branch links to the `stable` docs. If those are out of date and don't reflect the state of `develop`, then the links should be changed.

**Comment by jeromekelleher** [comment]
Thanks @danvk --- PR #774 should fix it.
