### ISSUE TITLE
Refactor certain end-to-end tests for class-level server startup/shutdown

### ISSUE THREAD

**Issue by dcolligan** [ga4gh/server#511]
Right now for the end to end tests we have (at least) one server start up and shut down per test.  If a number of tests in a class use the same server configuration(s) there is no need for this and startup and shutdown can be done at the class level instead of the function level.

This will cut down significantly on test run time.  For instance, `test_oidc.py` runtime will drop (preliminary results indicate) from 20s to 7s.

**Comment by jeromekelleher** [comment]
Good idea.

**Comment by dcolligan** [comment]
Fixed in #512
