### ISSUE TITLE
Delete routes in frontend.py that are no longer used 

### ISSUE THREAD

**Issue by jeromekelleher** [ga4gh/server#522]
Many routes are defined in the frontend that are no longer defined in the schema version we are working with. This should be deleted. These include:

- ``/<version>/mode/<mode>``
- ``/<version>/joins/search``

Once the final version of the schema that we are targeting has been defined and the necessary schema cleanup is done (see issue ga4gh/schemas#372) we should confirm that there are no dead routes and close this issue.

**Comment by dcolligan** [comment]
Fixed in #529
