### ISSUE TITLE
Add support for  GET `/datasets/id`

### ISSUE THREAD

**Issue by jeromekelleher** [ga4gh/server#523]
This can be based on the definition for `getVariantSet` in `frontend.py`.

**Comment by pcingola** [comment]
This is my first PR to this repo, so I'd appreciate some feedback / code review

Run example:

    $ python server/client_dev.py --verbose datasets-get MTAwMEc= http://localhost:8000/
    INFO:ga4gh.client:GET http://localhost:8000/datasets/MTAwMEc=
    INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): localhost
    MTAwMEc=

**Comment by dcolligan** [comment]
The code review happens on the pull request page.  Everyone subscribing to the repo is automatically notified with a new PR is made.

**Comment by dcolligan** [comment]
Fixed in #617
