### ISSUE TITLE
Add support for GET /callsets/id

### ISSUE THREAD

**Issue by dcolligan** [ga4gh/server#527]

**Comment by dcolligan** [comment]
@jeromekelleher so here we have another what-is-the-id-actually question to decide...

We need the variantSet to look up a callset with a certain id.  So should the id of the callset that we pass in this request be `datasetId:vsId:callsetId`?  Otherwise we'd have to pass additional info in the URL.

**Comment by dcolligan** [comment]
CallSetIds seem to be formatted as such now: e.g. `'dataset1:1kg-phase1.HG00533'` ... we can turn the period into a colon, I hope?

**Comment by jeromekelleher** [comment]
Yeah, this is the way to do it (``datasetId:vsId:callsetId``). We need to make all these IDs consistent throughout --- anything else should be considered a bug. (Note, we want to see IDs of this form coming from the simulated datasets too...)

**Comment by diekhans** [comment]
This raises a very important issue.  Many of us would like to see ids being globally unique and computed by hashing the data.  Also, having server-specific ids complicates writing protable tests cases.

**Comment by jeromekelleher** [comment]
We can't do GUIDs right now @diekhans, this would take serious thought and work to do properly. I agree GUIDs are something we need, but it's not something we can implement here without widespread agreement about how it should be done and rigorous specification. Test cases will just have to discover the data using the existing API methods.

**Comment by diekhans** [comment]
no argument @jeromekelleher ; this is a thorny issue and one GA4GH needs to stop avoiding.  UUIDs or sha1 are not efficient to index due to their random nature.

Something worth bringing up with the refvar group, as they are specifying UUID in the graph

**Comment by dcolligan** [comment]
Fixed in #542

**Comment by hjellinek** [comment]
What should `GET /callsets/some-ID-not-naming-a-real-callset` return?
right now it returns a `CallSet` with all of its fields set to default values, which seems wrong.  I'll open an issue about that if you like.

**Comment by jeromekelleher** [comment]
This is wrong all right; any `GET /objects/id-that-doesn't-exist` should return a 404. I would be good to open an issue on this.
