### ISSUE TITLE
datasetId field not set in read group set objects returned by searchReadGroupSets

### ISSUE THREAD

**Issue by hjellinek** [ga4gh/server#535]
I'm using data from the server unit tests as the server's data.  The files are arranged like so:
```
dataset1/
    reads/
        1kg-low-coverage/
            ... BAM files ...
        wgBam/
            ... BAM files ...
    variants/
```

**Assumption**: each subdirectory in `reads` corresponds to a read group set.

I create a search request with `datasetId` = `dataset1` and the other fields unset (default values).

**Expected**:
The call to `searchReadGroupSets` will return a `SearchReadGroupSetsResponse` with its `readGroupSets` field containing two read group sets, each with its `datasetId` field equal to `"dataset1"`.

**Actual**:
The call to `searchReadGroupSets` returns a `SearchReadGroupSetsResponse` with its `readGroupSets` field containing two read group sets.  Both have `datasetId` equal to `null`.

**Comment by jeromekelleher** [comment]
Verified fixed in #559.
