### ISSUE TITLE
searchReadGroupSets returns SearchReadGroupSetsResponse with readGroupSets == null for nonexistent dataset ID

### ISSUE THREAD

**Issue by hjellinek** [ga4gh/server#538]
**Background**: I'm using data from the server unit tests as the server's data. There is a single dataset, `dataset1`, with files arranged like so:

```
dataset1/
    reads/
        1kg-low-coverage/
            ... BAM files ...
        wgBam/
            ... BAM files ...
    variants/
```

**Action**: I create a `SearchReadGroupSetsRequest` with `datasetId` = `xyzzy` (as you see above, there is no such dataset) and the other fields unset (left as their default values).

**Expected**:
The call to `searchReadGroupSets` will return a `SearchReadGroupSetsResponse` with its `readGroupSets` field containing an empty array.

**Actual**:
The call to `searchReadGroupSets` returns a `SearchReadGroupSetsResponse` with its `readGroupSets` field set to `null`.

**Comment by jeromekelleher** [comment]
Yep, this is a bug. Thanks @hjellinek, you're doing a great job weeding out all these problems!

**Comment by hjellinek** [comment]
You're welcome @jeromekelleher - the new Compliance Test Kit makes it pretty easy to write and execute tests like this.

**Comment by jeromekelleher** [comment]
This was fixed by recent updates. Tests for this are ``testReadGroupSetsSearch`` in ``test_simulated_stack.py``.
