### ISSUE TITLE
Fix Travis security issue

### ISSUE THREAD

**Issue by kerrydc** [ga4gh/server#54]
We get this warning from Travis builds:
"/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/pkg_resources.py:1045: UserWarning: /home/travis/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable)."
We should fix this.

**Comment by jeromekelleher** [comment]
Agreed; this makes life awkward when trying to deploy using WSGI also, so it would be good to get to the bottom of it.

**Comment by jeromekelleher** [comment]
Fixed in #75
