### ISSUE TITLE
missing class in generated code?

### ISSUE THREAD

**Issue by bwalsh** [ga4gh/server#548]
That schema contains two definitions of the class `SearchFeaturesResponse`.  How are these handled in the generated code in _protocol_definitions.py?   (Currently I only see one)

The schema project the current server is based on is  `version = '0.6.be171b00'`
Snippets from this commit follow

* One in the file genotypephenotypemethods.avdl,  protocol GenotypePhenotypeMethods
```
/** This is the response from `POST /genotypephenotype/search` expressed as JSON. */
record SearchFeaturesResponse {
  /**
  The list of matching FeaturePhenotypeAssociation.
  */
  array<org.ga4gh.models.FeaturePhenotypeAssociation> associations = [];

  ...
```

* The second one is found in sequenceAnnotationmethods.avdl 
```
  /** This is the response from `POST /features/search` expressed as JSON. */
  record SearchFeaturesResponse {
    /**
    The list of matching annotations, sorted by start position. Annotations which
    share a start position are returned in a deterministic order.
    */
    array<org.ga4gh.models.Feature> features = [];

    ... 
```

* The generated code only has the class associated with `sequenceAnnotationmethods.avdl`

```
    def __init__(self):
        self.features = []
        self.nextPageToken = None
```

**Comment by jeromekelleher** [comment]
This is surely a bug in the schemas, isn't it? We can't have two classes with the same name in the same namespace. I think this is also gone from the latest version of the schemas in master, as these features have been moved into the alpha topic branches.

**Comment by bwalsh** [comment]
Both sequenceAnnotationmethods.avdl and genotypephenotypemethods.avdl share the same namespace `@namespace("org.ga4gh.methods")` each file defines an enclosing `protocol`.

In the [names section of the spec](https://avro.apache.org/docs/1.7.7/spec.html#Names)

```
A name only is specified, i.e., a name that contains no dots. In this case the namespace is taken from the most tightly enclosing schema or protocol. For example, if "name": "X" is specified, and this occurs within a field of the record definition of org.foo.Y, then the fullname is org.foo.X. If there is no enclosing namespace then the null namespace is used.
```

I'm assuming that the schemas pass validation...
```
A schema or protocol may not contain multiple definitions of a fullname. Further, a name must be defined before it is used ("before" in the depth-first, left-to-right traversal of the JSON parse tree, where the types attribute of a protocol is always deemed to come "before" the messages attribute.)
```

Full disclosure, I haven't had the chance to walk through `process_schemas.py`.  Does it consider the protocol {} element?

**Comment by jeromekelleher** [comment]
I'm not sure that ``process_schemas`` can do anything here @bwalsh --- we'll just have to change the names of one or both of these classes in the upstream schemas. This is a schema bug. I wouldn't read too much in to the schemas passing validation: the avro tools are quite weak for this sort of thing.

**Comment by bwalsh** [comment]
Agreed.  It having repeated class names is confusing.

-Brian Walsh

**Comment by jeromekelleher** [comment]
OK, good. I'm going to close this issue in that case.
