### ISSUE TITLE
Clean up code to improve readability

### ISSUE THREAD

**Issue by kerrydc** [ga4gh/server#55]
Rewriting some of the bigger classes to make variable names more readable and improve commenting would make understanding the code and contributing to the project easier.

**Comment by jeromekelleher** [comment]
Agreed - see the comments on PR #57 for my take. Should we try to make the style that we are looking for more explicit? I.e., is there a document somewhere that we could refer to, in terms of choosing class names, variable names, etc?

**Comment by dcolligan** [comment]
IMHO this issue is too general to keep open.  Code style could always be improved, but that in and of itself doesn't need an issue.

Alternatively, we should come up with a list of specific changes we want to complete before this issue gets closed.

**Comment by jeromekelleher** [comment]
I guess we should finish cleaning up all of the existing code in terms of the single letter variable names before closing this. A quick look suggests that the following files need to be cleaned up:

- ga4gh/cli.py
- ga4gh/client.py
- tests/test_schemas.py

I would suggest closing this issue once this is done. Thanks for keeping track of this @dcolligan, we should use issues more systematically!

**Comment by dcolligan** [comment]
Fixed in d35744a9fdde68dc91596e2cf3d68866eea91708
