### ISSUE TITLE
Eliminate hardcoded object names in tests (and elsewhere?)

### ISSUE THREAD

**Issue by dcolligan** [ga4gh/server#557]
Lots of tests rely on hardcoded object names in the simulator, etc.  It would be good to refactor these out to a common module so we didn't have hardcoded names scattered throughout different places in the code, and just call methods/attrs in that module when we need an example valid object name.

**Comment by jeromekelleher** [comment]
Yes please! We might not need a module to do it, just using some methods in the backend object to get a variantset (say) and then storing the ids as instance variables on the test case should be fine. Ideally this should be done along with ID obfuscation, as this will break a lot of test cases and we might as well do it all in one go.

**Comment by dcolligan** [comment]
Fixed in #558
