### ISSUE TITLE
Handle native filetypes gracefully, without conversion 

### ISSUE THREAD

**Issue by kerrydc** [ga4gh/server#56]
We should support .vcf, .bcf, .bam, and .sam files as input. Conversion to internal formats and choice of backend should happen on our end, with backend choice determined by performance benchmarking.

**Comment by jeromekelleher** [comment]
This is definitely the goal we should aim at I think. Removing the dependency on wormtable and the need for pre-conversion of the data would greatly improve usability. For now, however, there are some pretty severe performance penalties associated with accessing VCF directly---we go from serving thousands of variants per second down to something like ten variants per second. This is too slow to be useful.

Once we have a Python interface to the [htslib](https://github.com/samtools/htslib) code for reading BCF data, we will hopefully have the performance that we need, and can then drop wormtable entirely.

I'm not sure about converting to internal formats on the fly though, as this is very, very expensive (might take many days to complete), and not something that should be done in the context of a webserver process.

**Comment by bioinformed** [comment]
On Fri, Jan 2, 2015 at 9:28 AM, Jerome Kelleher <notifications@github.com>
wrote:

> Once we have a Python interface to the htslib
> <https://github.com/samtools/htslib> code for reading BCF data, we will
> hopefully have the performance that we need, and can then drop wormtable
> entirely.
>

I'm working on adding support for the htslib VCF/BCF API to pysam right
now.  I hope to have a fully featured alpha version ready on Monday and
would value feedback on the API mapping.  When ready, serving indexed BCF
and VCF files should be quite zippy.

-Kevin

**Comment by hershman** [comment]
To take advantage of the full BCF API will we need to do anything beyond appending a <code>parser=pysam.asVCF()</code> the <code>TabixFile.fetch()</code> call in ga4gh/backends.py:339-340 and then and then using the right [asVCF fields](http://pysam.readthedocs.org/en/latest/api.html?highlight=asvcf#pysam.asVCF) in the convertVariant function?

**Comment by jeromekelleher** [comment]
This is great new @bioinformed! This would be massively useful for us. Let us know if there's anything we can do to help...

**Comment by bioinformed** [comment]
> On Jan 2, 2015, at 11:48 AM, Steve Hershman <notifications@github.com> wrote:
> 
> To take advantage of the full BCF API will we need to do anything beyond appending a parser=pysam.asVCF() the TabixFile.fetch() call in ga4gh/backends.py:339-340 and then and then using the right asVCF fields in the convertVariant function?
> 

My htslib wrapper is not based at all on the existing pysam VCF API. Rather, it is a full extrapolation of the htslib API where VCF and BCF processing is unified using a compact BCF-like in memory representation, all values are properly typed according to the metadata, access to headers/formats/filters/info/sample information is available via light weight mapping objects, tabix/csi/bcf indexing is supported transparently, etc.  All of the heavy lifting is in Cython, so performance should be very close to the native API once some basic optimizations are in place. 

So adopting the new code will not be quite as simple as you state, but not particularly difficult either.   I'm happy to provide an initial ga4gh backend implementation, if that will be useful.  

Note that my work is pre-alpha and has yet to be reviewed or blessed by the other pysam developers. At best, they will like it and it will supersede or live alongside the existing pysam VCF code, at worst I'll spin it off as standalone package. 

-Kevin=

**Comment by jeromekelleher** [comment]
This sounds perfect to me @bioinformed --- an outline ga4gh backend implementation based on this would be a huge step in the right direction.

**Comment by bioinformed** [comment]
Quick update: My pre-alpha pysam branch with the new htslib VCF/BCF API is
available here:

https://github.com/bioinformed/pysam/tree/bcf


This code is incomplete and preliminary.  It does offer a nearly complete
immutable Pythonic interface to VCF/BCF metadata and data with reading and
writing capability, but has no capability (yet) to mutate the resulting
data (beyond dropping all samples).  Documentation still needs to be
written and a unit test suite is in the works.  The code is also
superficially specific to Python 2 and will require a bit of work to
properly adapt to Python 3.

Some very preliminary documentation is available at the top of this Cython
module <https://github.com/bioinformed/pysam/blob/bcf/pysam/cbcf.pyx>.

I'll start working on a ga4gh/server backend that demonstrates its use.

-Kevin

**Comment by lh3** [comment]
Would be good to support extracting a subset of samples. Useful functionality and should be easy with htslib. Also, is random access supported yet?

**Comment by jeromekelleher** [comment]
@bioinformed has made a htslib backed VariantSet implementation available at https://github.com/bioinformed/server/tree/paging-cleanup, using a not-yet-released version of pysam. See https://github.com/jeromekelleher/server/pull/1 for discussion.

**Comment by lh3** [comment]
Look good! Thanks.

**Comment by jeromekelleher** [comment]
This is being worked on, and has been superseded by more specific issues, so I'm closing.
