### ISSUE TITLE
GET /callsets/nonexistent-ID returns skeleton CallSet

### ISSUE THREAD

**Issue by hjellinek** [ga4gh/server#565]
`GET /callsets/some-ID-not-naming-a-real-callset` returns a `CallSet` object with all of its fields set to default values.  Per @jeromekelleher, this is the wrong behavior:

> This is wrong all right; any GET /objects/id-that-doesn't-exist should return a 404.

(Incidentally, I found this issue using the [new compliance test kit](https://github.com/ga4gh/compliance/pull/27).)

**Comment by jeromekelleher** [comment]
Verfied fixed in #569
