### ISSUE TITLE
Should objects be sorted?

### ISSUE THREAD

**Issue by jeromekelleher** [ga4gh/server#567]
PR #564 drops the requirement that all datasets, variantsets, readgroupsets, etc are returned in sorted order. This is possibly dangerous when paging with several processes, and also it is a good property the the order of these objects be preserved across server restarts. We should check to see if this is really a problem, and if so re-impose the ordering requirement.

**Comment by diekhans** [comment]
+1

More seemingly simple additions to a paper specification that add complexity to implementations.  We really need to documentation the motivations for these decisions.

**Comment by jeromekelleher** [comment]
Well, this is a requirement we added ourselves and isn't motivated by the protocol. It's specific to how we handle the paging of the top level objects.

**Comment by jeromekelleher** [comment]
Closing this; seems safe enough for now.
