### ISSUE TITLE
Import/export data using command line API rather than copying files

### ISSUE THREAD

**Issue by diekhans** [ga4gh/server#573]
As the API evolves, it will become harder to robustly add data to the reference server  by manually installing files.  Suggest developing a command line API to install and remove data from a reference server.  Advantages include:

- Simplify and insure accurate install of standard file formats
- Isolate internal structure of files from user.
- Provide way to add additional metedata required by the API but not part of standard file format
- Allow for data validation before server is started
- Build required indexes, either standard ones, such as BAM indexes, or reference-server specific ones, such as identifier indexes
- Simplify automation of reference server setup for production sites

**Comment by jeromekelleher** [comment]
Good ideas...

**Comment by kozbo** [comment]
Looks like a duplicate of #814. @dcolligan should we close this too?

**Comment by dcolligan** [comment]
Yeah, this is the repo manager
