### ISSUE TITLE
Data hierarchy for ReadGroupSets and ReadGroups is wrong

### ISSUE THREAD

**Issue by jeromekelleher** [ga4gh/server#574]
As discussed in ga4gh/compliance#34, we have misinterpreted the mapping between SAM files and readgroups. Currently, we map a SAM file to a ReadGroup but it should map to a ReadGroupSet.

**Comment by jeromekelleher** [comment]
Copying a comment made by @lh3 here for reference: 

> One read group typically corresponds to one lane. For old data, one BAM usually contains multiple read groups. For typical resequencing, we use one BAM for one sample, though there are exceptions at times. A readgroupset usually corresponds to one BAM.

Thanks for the clarification @lh3!

**Comment by diekhans** [comment]
While a given SAM file can have multiple read groups, it is
often desirable to have a read group set split across multiple
BAM files.

This is a huge problem for TCGA.  Both the data distribution
model and many of the tools assume that all readgroups for a
given sample were in a single BAM.  However Broad's data
production model didn't generate data in this manner.  Often
additional readgroups would be sequenced at disjoint times when
more sequence capacity was available.

The TCGA model required new `top-off' BAMs be created with all
readgroups, generating hundreds of terabytes of data churn.

One of the advantages of API access to data is to remove all of
the assumptions around file organization and instead think in
terms of the actually immutable data production units.  In the
case of sequencing, this is readgroup, not readgroupset

I would encourage support a readgroupset being stored in one or
more BAMs.

**Comment by jeromekelleher** [comment]
(copying @lh3's comment here from  ga4gh/compliance#34 )
> All combinations happen in practice, but I think we should just implement the common practice (one bam per sample containing one or several read groups) and throw an error in the uncommon cases for now.

I agree --- let's assume the common case for now. This is just our data input layer, we can generalise later when the problem arises.

**Comment by dglazer** [comment]
I agree with @jeromekelleher that the ref server can start by assuming the common case, and adding complexity later if and when the problem arises.

(FYI, as I mentioned elsewhere, Google's import code supports the common case by default, but also lets you import data with other mappings -- see our [understanding readgroupset assignment](https://cloud.google.com/genomics/v1beta2/managing-reads?hl=en#readgroupsetids) doc for details.)

**Comment by macieksmuga** [comment]
The BAM files included in the proposed ["coherent" compliance data set](https://github.com/ga4gh/compliance/tree/compliance_redux/test-data) are of the type discussed here: Multiple `@RG` (ReadGroup) records per file. If the server is to work correctly on these (and thus conform to the compliance suite) it will need to adjust its hierarchy accordingly.

**Comment by dcolligan** [comment]
Fixed in #605
