### ISSUE TITLE
SearchReadGroupSetsRequest with name that doesn't match produces exception - should it?

### ISSUE THREAD

**Issue by hjellinek** [ga4gh/server#576]
I have a compliance test that executes `POST /readgroupsets/search` on a `SearchReadGroupSetsRequest` with a name that I know doesn't match anything.

```
{"datasetId": "compliance-dataset1", "name": "xyzzy", "pageSize": null, "pageToken": null}
```

The test expects to receive an empty list in a `SearchReadGroupSetsResponse`.  The `SearchReadGroupSetsResponse` schema comments tend to support this interpretation:

```
Gets a list of `ReadGroupSet` matching the search criteria.
```

The actual result is that the server throws a `DatasetNotFoundException`/returns 
a 404.  I'd expect that if I had executed `GET /readgroupsets/xyzzy`, but not when I do a search on `xyzzy`.

Also, this behavior seems inconsistent with the other types of searches, when last I looked.  Comments?

**Comment by hjellinek** [comment]
Likewise, passing a nonexistent dataset ID in a `SearchReadGroupSetsRequest` to `POST /readgroupsets/search` has a similar result.

```
{"datasetId": "foobar", "name": null, "pageSize": null, "pageToken": null}
```

returns a 404.  I have expected a `SearchReadGroupSetsResponse` containing an empty list.

**Comment by hjellinek** [comment]
Finally, based on the same reasoning I assumed that passing a `SearchReadGroupSetsRequest` containing a valid dataset ID but no name to `POST /readgroupsets/search` would return all read group sets.

```
{"datasetId": "compliance-dataset1", "name": null, "pageSize": null, "pageToken": null}
```
But it too returns a 404.

**Comment by hjellinek** [comment]
However we resolve these, we should update the comments in the `SearchReadGroupSetsRequest` and `SearchReadGroupSetsResponse` to explain.

**Comment by hjellinek** [comment]
Looks like my comment in our meeting about distinguishing between names and IDs was appropriate to this problem.  Whereas my tests used to be able to refer to datasets by what I'll call a name (even if it was passed in as something called a "dataset ID"), the current server identifies my datasets using opaque, apparently generated IDs:

```
DataSets
    Y29tcGxpYW5jZS1kYXRhc2V0MQ==

VariantSets
    Y29tcGxpYW5jZS1kYXRhc2V0MToxa2dQaGFzZTE=
```

It's important to be able to write programs, not to mention tests, that use known names to refer to particular objects.  How to do that now?

**Comment by jeromekelleher** [comment]
There are two separate issues here @hjellinek:

1. Should searching for something in a POST ``SearchXRequest`` that doesn't exist return an error, or an empty result set? Most of me thinks it should be an error, but I'm not certain. I am certain that the schema should explicitly specify this though, and the current documentation is not sufficient. (Which is universally true of error conditions: they simply are not defined, which is not good enough.)

2. I'm sorry for changing the IDs abruptly to this opaque format, but this was a deliberate step to prevent clients from assuming that the IDs were anything but opaque, internally defined values. The ID for a particular object will be the same on a particular server, but that's all that you can depend on. 

The ``name`` field I think is what you want for compliance tests --- in my interpretation, this is a more human-friendly identifier. I would say that for compliance tests we should mandate that  there is a dataset with ``name`` == "compliance_dataset_1", which contains exactly the variant sets and readgroupsets we expect. There should really be a ``name`` field in the ``VariantSet`` class for symmetry with ``Dataset``, ``ReadGroupSet`` and ``CallSet``. (``ReferenceSet`` doesn't have a ``name`` either, but that has quite a few other ways of identifying it. Should it also have a ``name``?)

**Comment by hjellinek** [comment]
Thanks @jeromekelleher, it was the absence of `name` fields in some that made me think that IDs were the correct way to reference them.  Let's not forget to add corresponding `name` fields to the relevant `search*` methods, too.

Regarding `ReferenceSet`, if any of the other fields can be used to unambiguously identify a given `ReferenceSet`, then I think adding `name` is unnecessary.  `md5checksum` would work, wouldn't it?

**Comment by jeromekelleher** [comment]
@hjellinek --- yes, I think either ``assemblyId`` of ``md5checksum`` should unambiguously identify the ``ReferenceSet`` so a name is probably superfluous. Consistency is nice though, so it might still be worth having it purely for keeping a consistent object model.

Anyway, apologies again for all the recent changes to the server in terms of IDs, URLs etc. These had been outstanding for a while, and I thought it was important to sort them out before we hit the big sync-up. The reference server is going to be interpreted as definitive soon, so I think it's important to get this sort of thing sorted out now.

**Comment by sarahhunt** [comment]
@jeromekelleher - re searching for something that doesn't exist -  We're currently returning HTTP/1.0 400 Bad Request and an endpoint specific error message. It seems more useful for the client to highlight the problem rather than leaving them to test for empty sets. 

I agree, error handling needs to be specified exhaustively.

**Comment by jeromekelleher** [comment]
@sarahhunt --- great, sounds like we're on the same page!

**Comment by dcolligan** [comment]
Can we close this issue?  Looks like it was mostly confusion about the obfuscated Ids...
