### ISSUE TITLE
Download script needs to get references

### ISSUE THREAD

**Issue by jeromekelleher** [ga4gh/server#578]
For each chromosome, we need to download the reference sequence for positions 0 to maxPos + 1000 (say). One way this can be done is using the [ENA Web APIs](http://www.ebi.ac.uk/ena/browse/data-retrieval-rest#sequence_region_fasta). To use this we need to get the accession numbers for the GRCh38 chromosomes which should be available [here](http://www.ncbi.nlm.nih.gov/projects/genome/assembly/grc/human/data/).

The reference data can then be saved in either a single FASTA or one-per-chromsome, whichever is simpler.

**Comment by dcolligan** [comment]
Fixed in #581
