### ISSUE TITLE
Fix our build so that we pass compliance tests with both tabix and wormtable backends 

### ISSUE THREAD

**Issue by kerrydc** [ga4gh/server#58]
We should also update our readme with instructions on how to run both backends against the compliance suite, and the expected results with the current build.

**Comment by jeromekelleher** [comment]
+1.

**Comment by bioinformed** [comment]
Knowing how to running the compliance suite would help me a lot, since I'm
coming into the codebase cold and am hoping to add a new backend.

**Comment by dcolligan** [comment]
@jeromekelleher close this issue?  Seems pretty irrelevant now.

**Comment by jeromekelleher** [comment]
Agreed.
