### ISSUE TITLE
Program fields in ReadGroup should be filled from @PG tags

### ISSUE THREAD

**Issue by jeromekelleher** [ga4gh/server#587]
The ``ReadGroup.programs`` field is currently not being populated. This should be filled in using the SAM @PG tags, if present.

**Comment by macieksmuga** [comment]
Considering that `ReadGroup` doesn't represent a BAM, whereas a `ReadGroupSet` does, shouldn't the `.programs` field be moved to the latter? (see #574)

**Comment by jeromekelleher** [comment]
@macieksmuga --- yes, probably. This would be a  schemas issue though.

**Comment by dcolligan** [comment]
Fixed in #590
