### ISSUE TITLE
SearchReads takes reference name, not ID

### ISSUE THREAD

**Issue by macieksmuga** [ga4gh/server#591]
SearchReads should take a referenceID (per schemas), but uses reference name instead. Thus, the following query (against my local server instance, yours may take different names & ID's) fails:

    ga4gh_client -vv reads-search http://localhost:8000 --readGroupId="YnJjYTE6MWtnLWxvdy1jb3ZlcmFnZTpCUkNBMV9IRzAwMDk2" --start=0 --end=200 --referenceId="aGczNzpoczM3ZDVfY2hyMTdfNDExOTYzMTItNDEyNzc1MDA="

while this one works:

    ga4gh_client reads-search http://localhost:8000 --readGroupId="YnJjYTE6MWtnLWxvdy1jb3ZlcmFnZTpCUkNBMV9IRzAwMDk2" --start=0 --end=200 --referenceId="ref_brca1"

**Comment by jeromekelleher** [comment]
This is a bug, thanks @macieksmuga.

**Comment by dcolligan** [comment]
Fixed in #597
