### ISSUE TITLE
'host' should not be hard-coded to 0.0.0.0

### ISSUE THREAD

**Issue by acthp** [ga4gh/server#592]
in cli::server_main

host should be configurable. Also, 0.0.0.0 is a poor default, because it exposes the server to the world, potentially leaking controlled data, and exposing the user to remote attacks.

Should be 127.0.0.1, and configurable.

**Comment by jeromekelleher** [comment]
Thanks for the bug report @acthp --- fix in PR #593.

**Comment by jeromekelleher** [comment]
Fixed in #593.
