### ISSUE TITLE
Requests made by client with key=invalid argument

### ISSUE THREAD

**Issue by dcolligan** [ga4gh/server#601]
This command

```
python client_dev.py -O variants-search http://localhost:8000 --variantSetId ZGF0YXNldDE6MWtnLXBoYXNlMQ==
```

results in a request to 

```
/variants/search?key=invalid
```

If the `key=invalid` part is not necessary (which I suspect it is not), we should not make requests with that argument.

**Comment by jeromekelleher** [comment]
This was done as a workaround for an obscure issue with authentication. The reasoning is buried in the discussion for #447 (search for "json document").

**Comment by david4096** [comment]
Moved https://github.com/ga4gh/ga4gh-client/issues/29
