### ISSUE TITLE
Support configuration

### ISSUE THREAD

**Issue by Naburimannu** [ga4gh/server#61]
In order to support [performance benchmarking] (https://github.com/ga4gh/server/issues/46) we should be able control whether or not the server is logging performance statistics, particularly those that are expensive - memory use or detailed profile data. This is a good impetus to start using [Flask configurations] (http://flask.pocoo.org/docs/0.10/config/).

This can be some combination of command-line, environment variables, Python classes, and files.

(Addresses a TODO in ga4gh/server/__init__.py)

**Comment by dcolligan** [comment]
Can this be closed?  Seems like bb79afd80d48df9d3fb8827ffd8c7f532c62620a addressed it.

**Comment by Naburimannu** [comment]
Yep, planned followup is captured in #69 and #70.
