### ISSUE TITLE
Create datadriven tests for strand PR

### ISSUE THREAD

**Issue by dcolligan** [ga4gh/server#610]
For this PR: #609

**Comment by dcolligan** [comment]
The issue that that PR fixes is https://github.com/ga4gh/server/issues/491

**Comment by ekalosak** [comment]
I'm working on this.

**Comment by ekalosak** [comment]
Thanks for connecting those dots, dcolligan. How do I set this as in progress?

**Comment by dcolligan** [comment]
I just added the label (which one can do with the UI on the right hand side of the issue screen).  I would also assign this issue to you, but I think you need to be added to the project in some admin config, and I am not an admin.  @benedictpaten , could you take care of that?

**Comment by ekalosak** [comment]
Thanks for connecting those dots, Danny! How do I mark this as in progress?

**Comment by jeromekelleher** [comment]
I've invited @ekalosak to join the Global Alliance contributors group, which should give the relevant permissions.

**Comment by dcolligan** [comment]
Still can't set it.  He probably needs to accept the invite first.

**Comment by ekalosak** [comment]
https://gist.github.com/ekalosak/b22399153a2dd0b019d7

**Comment by jeromekelleher** [comment]
Try running ``python scripts/download_data.py`` @ekalosak --- these scripts are intended to be run from the project root.

**Comment by dcolligan** [comment]
I'm walking him through it... he just doesn't have the right libraries installed.  See the issue I just created.
