### ISSUE TITLE
Warning: data input format has changed!

### ISSUE THREAD

**Issue by jeromekelleher** [ga4gh/server#618]
Since #605 was merged, the required input format for the server has changed. Now, readgroupsets are mapped to bam files, and so we expect all bam file to be in the ``datasetDir/reads`` directory, rather than in subdirectories of this.

The example data and documentation will be updated in a few days. This is just a heads-up for the developers at the bleeding edge.

**Comment by macieksmuga** [comment]
Thanks for the heads-up @jeromekelleher!

**Comment by dcolligan** [comment]
I presume everyone got the message... closing...
