### ISSUE TITLE
Client request for variants seems to be broken

### ISSUE THREAD

**Issue by pcingola** [ga4gh/server#620]
In cli.py:

    cli.py main[957]: addVariantsGetParser(subparsers)
        => addVariantsGetParser[921]: parser.set_defaults(runner=GetVariantRunner)
            => GetVariantRunner[579]: self._run(self._httpClient.runGetVariant)
            client.py: class HttpClient(object), apparently there is no 'runGetVariant' method

Related test cases seem to be missing as well.

**Comment by dcolligan** [comment]
huh, wonder how that one slipped through.  Good catch.

**Comment by jeromekelleher** [comment]
Well spotted @pcingola, thanks.

**Comment by dcolligan** [comment]
This turned out to be a trivial change that I fixed en route to fixing another bug... assigning myself... we should find a meatier issue for @pcingola

**Comment by jeromekelleher** [comment]
Fixed in #624.
