### ISSUE TITLE
Update documentation on expected data formats to include references.

### ISSUE THREAD

**Issue by macieksmuga** [ga4gh/server#628]
The `configuration.rst` doc doesn't yet contain a write-up on the expected data format for references.

For example: While FASTA files can generally contain multiple records, the reference server mandates that a reference FASTA contain a single record, whose name is identical to that of its containing file. If this requirement is not met, an `InconsistentReferenceNameException` is thrown.

**Comment by jeromekelleher** [comment]
Has this been clarified in the latest docs @macieksmuga?

**Comment by david4096** [comment]
Closed with https://github.com/ga4gh/server/commit/00d6b7962019a86d77e549f4be6d49436e602446
