### ISSUE TITLE
Metadata not set for ReferenceSets

### ISSUE THREAD

**Issue by jeromekelleher** [ga4gh/server#642]
Metadata such as NCBITaxonId and SourceAccessions are now supported for ``References`` but are not supported for ``ReferenceSets``. We should fix this by following the same pattern:

1. Add corresponding .json file next to the directory containing the ReferenceSet, which holds this metadata.
2. Update the ``download_data.py`` script to write this information for our example data.

**Comment by dcolligan** [comment]
The title of this issue says ReadGroupSets but the description says ReferenceSets... which one is it?

**Comment by jeromekelleher** [comment]
Oops, my bad; title edited.

**Comment by dcolligan** [comment]
Fixed in #657
