### ISSUE TITLE
Have download_data check for required libraries before running

### ISSUE THREAD

**Issue by dcolligan** [ga4gh/server#644]
Right now `download_data.py` can run and then choke in the middle of processing with an unintuitive error message if a user does not have the required programs on the path.  Change this so that if a user lacks the requirements a helpful error message is printed right at the beginning informing them of this.  Here is an example of what happens currently: https://gist.github.com/ekalosak/b22399153a2dd0b019d7

Anything that `runCommand` uses is required: `bcftools`, `bgzip`, `tabix`, `samtools`

**Comment by jeromekelleher** [comment]
Good idea.

**Comment by dcolligan** [comment]
We can generalize this to other scripts and refactor with a method in `utils`, but that can be the follow up issue

**Comment by dcolligan** [comment]
Fixed in #1297
