### ISSUE TITLE
Create an client implementation for IPython Notebook (hackathon idea)

### ISSUE THREAD

**Issue by bwalsh** [ga4gh/server#662]
"As a researcher, in order to incorporate GA4GH endpoints into my workflow, it would be a productivity boost to have the server client integrated into a notebook"

**Comment by diekhans** [comment]
I suspect an R interface would be very popular

**Comment by AAMargolin** [comment]
+1 -- I think client implementations (R, Python) in general for GA4GH APIs would be a very appropriate and useful hackathon topic.

**Comment by jeromekelleher** [comment]
This should use the client api: http://ga4gh-reference-implementation.readthedocs.org/en/develop/api.html#client-api

**Comment by hershman** [comment]
I'll dig into this

**Comment by jeromekelleher** [comment]
Close this issue with PR #746; but see #851.
