### ISSUE TITLE
Next version number

### ISSUE THREAD

**Issue by jeromekelleher** [ga4gh/server#665]
Get out the bike shed paint pallete!

We need to tag a release soon (next week really), so we need to decide what number it should be. The simplest choice for us would be '0.2.0a1', since we've been on the 0.1 series so far, and we've broken compatibility with it pretty heavily. I think it's important we go through a few alphas too, as this way we won't be the default install on pypi and won't upgrade people until we're happy it's stable.

However, there's another alternative. There's an argument for us tracking the version number of the schemas, so that it's easy to see which schema version corresponds to a given server version. So, we could have something like '0.6.0.0a1', where the first three digits are the schema version and the last segment is the server version. I think this would probably be a bad idea for a couple of reasons:

1. We're going to want to release versions a lot more often than the schemas, so we're going to end up with pretty silly version numbers;
2. Over time, the schema is going to reach stablity, and we're going to be stuck with a particular prefix. This means we couldn't have our own semantic versioning.

So, all-in-all, I think '0.2.0a1' is the best choice and we shouldn't track the schema version. I thought it was best to put the options forward so that we could make a consensus decision on it. Thoughts?

**Comment by dcolligan** [comment]
0.2.0a1 sounds good.

**Comment by skeenan** [comment]
I like the idea of the tracking schema version somehow.  I see your point about getting stuck with a schema version prefix. So how about suffixing the schema version to the server version. The composite would be `server version_schemaversion` e.g. `v0a1_0.6.0`

**Comment by jeromekelleher** [comment]
It's a nice idea @skeenan, but it would break compatibility with [pep 440](https://www.python.org/dev/peps/pep-0440/). We need to have version numbers that make sense for us a piece of software first, and the benefits of including the schema version number in there are out weighed by the advantages of being compatible with PyPI.

0.2.0a1 it is unless we hear otherwise I think.

**Comment by dcolligan** [comment]
So we've decided on 0.2.0a1, and we aren't going to make a release imminently... can we close this?
