### ISSUE TITLE
Hackathon labels explained

### ISSUE THREAD

**Issue by jeromekelleher** [ga4gh/server#669]
I've created two labels for the NYGC Hackathon. One is the "NYGC Hackathon" and is for everything that we're potentially interested in at the hackathon.

The other is "Hackathon assignment" which is for issues that are going to be assigned to people so they can get started on coding with the reference server. They will be assigned on the day, and hopefully we'll be able to get PRs merged for most of them. These should be relatively easy for people with no experience with the codebase to pick up and work through.

**Comment by dcolligan** [comment]
Closing this
