### ISSUE TITLE
Generate URL endpoints from schema definitions

### ISSUE THREAD

**Issue by jeromekelleher** [ga4gh/server#67]
It would be very useful to have a list of valid URL endpoints and the types of their arguments and return values for testing purposes. This information should be derivable from the Avro schemas and could be added to the auto generated file `_protocoldefinitions.py`. 

The general pattern is Search[Class]Request maps to the URL /[class]/search which takes a Search[Class]Request and returns a Search[Class]Response. We can scan for these class names in `scripts/generate_schemas.py` using a simple regex, and write a list of (url, requestClass, responseClass) triples at the end of the `_protocoldefinitions.py`.

A different (and inconsistent) pattern holds for GET requests, which should be dealt with later.

**Comment by dcolligan** [comment]
Starting work on this issue

**Comment by dcolligan** [comment]
Fixed in #74
