### ISSUE TITLE
Improve test for backend string parsing functions.

### ISSUE THREAD

**Issue by jeromekelleher** [ga4gh/server#682]
In ga4gh/backend.py, the ``_parseIntegerArgument`` function is responsible for parsing integer values passed as arguments in GET requests.

Add some tests for this in ``tests/unit/test_backends.py``. Add a  test method to the TestPrivateBackendMethods class to test positive results (i.e., do we correctly return the right value?) and another to test negative results (i.e., do we correctly raise a BadRequestIntegerException when called with non-integer values?).

We also want to improve the tests for the _parsePageToken function. We want to include tests for all negative results, as well as improved tests for the positive results. (The existing test is good, but we'd like to check more possibilities, like varying numbers of colon separated values)

**Comment by andrewyatz** [comment]
PR incoming
