### ISSUE TITLE
Add tests for backend methods, refactor and update docs

### ISSUE THREAD

**Issue by jeromekelleher** [ga4gh/server#683]
The documentation and class names for the ``tests/unit/test_backends.py`` module are a little out of date and need spring cleaning. The tests cases are also somewhat out of date, and need to be refocused on the local behaviour of the backend classes (code in ``ga4gh/backend.py``).

- To run the tests, run ``nosetests -vs tests/unit/test_backends.py``

- Remove the unused BackendForTesting class. 

-  Remove all methods from TestAbstractBackend (many of these are unused, and the stuff that is being tested is duplicated elsewhere). Update the comments to say "Tests for shared functionality between backends". Temporarily comment out the TestFileSystemBackend class. 

- Add tests for all the public functions on the AbstractBackendClass. For example, 

```python
    def setUp(self):
        self._backend = backend.AbstractBackend()
        
    def testAddOneDataset(self):
        datasetName = "ds"
        dataset = datasets.AbstractDataset(datasetName)
        self.assertEqual(self._backend.getNumDatasets(), 0)
        self._backend.addDataset(dataset)
        self.assertEqual(self._backend.getNumDatasets(), 1)
        self.assertEqual(self._backend.getDatasets(), [dataset])
        self.assertEqual(self._backend.getDatasetByIndex(0), dataset)
        self.assertEqual(self._backend.getDataset(dataset.getId), dataset)
```

We should have similar tests for testAddMultipleDatasets, testAddOneReferenceSet and testAddMultipleReferenceSets.

- Add a method called ``getDatasetByName`` to AbstractBackend, modelled after ``getReferenceSetByName``, and update the above tests to include checks for it working properly.

- Add tests to ensure that the exceptions like ``exceptions.DatasetNotFoundException`` are correctly raised when expected. For example,

```python
    def testGetDatasetBadId(self):
        for badId in ["", None, "NO SUCH ID"]:
            self.assertRaises(
                exceptions.DatasetNotFoundException,
                self._backend.getDataset, badId)
```

- Uncomment TestFileSystemBackend, and make it a subclass of unittest.TestCase.  Write some test cases to ensure that the backend has correctly gone through the file system at ``tests/data`` and created the correct objects. For example, we should have one dataset called "dataset1":

```python
def testDatasets(self):
        self.assertEqual(self._backend.getNumDatasets(), 1)
        dataset = self._backend.getDatasetByIndex(0)
        self.assertEqual(dataset.getLocalId(), "dataset1")
```

- Add a similar test for ReferenceSets. 

(We can generalise these tests to work with multiple datasets and reference sets later).

**Comment by sguthrie** [comment]
Working on this!

**Comment by sguthrie** [comment]
@jeromekelleher, what is the expected behavior for backend.getDatasets(), backend.getDatasetByIndex, backend.getDatasetByName (and the corresponding reference set functions) when no datasets are loaded? Should an empty response be given or an error thrown?
