### ISSUE TITLE
Unit tests for reads

### ISSUE THREAD

**Issue by jeromekelleher** [ga4gh/server#687]
We need some standalone unit tests for the ``ga4gh/datamodel/reads.py`` module. Create a new test module called ``tests/unit/test_reads.py`` modelled after ``tests/unit/test_variants.py``. Add some unit tests in here:

1. Create unit tests for ``parseMalformedBamHeader``. We want to have some input strings (basically BAM header values you might see from ``samtools view -H tests/data/datasets/dataset1/reads/HG00096.mapped.ILLUMINA.bwa.GBR.low_coverage.20120522.bam`` where tabs have been replaced by spaces), and verify that they are parsed correctly.

2. Create unit tests for the SamCigar utility class verifying that the mapping is handled correctly.

2. Create unit tests for the SamFlags utility class verifying that the mapping is handled correctly.

Run the tests using ``nosetests -vs tests/unit/test_reads.py``.

**Comment by andrewjesaitis** [comment]
PR #922 is for this issue

**Comment by david4096** [comment]
https://github.com/ga4gh/server/blob/master/tests/unit/test_reads.py
