### ISSUE TITLE
ReferenceID not set in VariantSet

### ISSUE THREAD

**Issue by jeromekelleher** [ga4gh/server#689]
Currently we have no way of associating a given referenceSet with a VariantSet. Ideally this should be derived from the ``reference`` and ``contig`` tags in the VCF header.

**Comment by Tixii** [comment]
Im working on this

**Comment by david4096** [comment]
bump, this renders the variants interface problematic. There is no way to tell which `referenceName` to send in a `searchVariants` request without knowing ahead of time what is in the VCF.

**Comment by diekhans** [comment]
VariantSet has referenceSetId, this is used to obtain the list
of references that could be in a variant set.

**Comment by david4096** [comment]
@diekhans As far as I can tell `referenceSetId` is pinned to a blank string here:

https://github.com/ga4gh/server/blob/master/ga4gh/datamodel/variants.py#L95

When trying to create a simple script for listing the variants for a variant set I found that one would have to brute force the `referenceName` field of a `SearchVariantsRequest` to find which contigs a variant set refers to.

**Comment by jeromekelleher** [comment]
There is no standard header for defining what reference a VCF uses. I think the only feasible solution here is to require the repository administrator to tell us what it is via the repo manager tool. Ideally, at import time we have an option saying "associate this variant set with this reference set".

**Comment by diekhans** [comment]
ouch.  references set name should be specified when the variant set is added
to by the repo manager.  Given that reference genomes are ubiquitous, I don't
see a reason for it to be optional.

**Comment by jeromekelleher** [comment]
Closed by #1166.
