### ISSUE TITLE
Select among configuration subclasses from the command line

### ISSUE THREAD

**Issue by Naburimannu** [ga4gh/server#69]
After #61 is addressed, http://flask.pocoo.org/docs/0.10/config/#development-production suggests subclassing ga4gh.server.config:DefaultConfig for test, development, production, or other use cases. Once we have a use for them, we should support a command-line argument ("--config=..."?) to select among them.

**Comment by dcolligan** [comment]
Starting work on this issue

**Comment by Naburimannu** [comment]
Do we have any example of actually needing it yet?
We only landed #61 because I originally thought I'd want it for performance testing; I wasn't going to add any more complexity until we knew it'd be useful.

**Comment by dcolligan** [comment]
@jeromekelleher might have an opinion; he identified it as an issue that I could work on

**Comment by jeromekelleher** [comment]
I'm not sure it's that urgent, but I thought it would be a good place for @dcolligan to start with on our Flask setup. We do need to figure out how to do our testing config properly soon, so it's probably no harm in tackling this now.

**Comment by dcolligan** [comment]
Fixed in 22df2e1e4db47b98e46e37cc441a850f28e813d3
