### ISSUE TITLE
Specify configuration override file from the command line

### ISSUE THREAD

**Issue by Naburimannu** [ga4gh/server#70]
Once #61 is addressed, we would like to be able to specify a configuration override file from the command line ("--config_file=..."?) in the same way we can with the GA4GH_CONFIGURATION environment variable.

**Comment by dcolligan** [comment]
What format should this config file be in?  What data should we be expecting to be in the file?

**Comment by Naburimannu** [comment]
@dcolligan: Although I haven't read the Flask source to be sure, the usual convention (http://flask.pocoo.org/docs/0.10/config/) and our assumption when we merged https://github.com/ga4gh/server/pull/62 is that the file is a sequence of
    KEY = Value
where keys are all-caps underscore-separated identifier, and values are python expressions. The only key which is defined so far is MAX_CONTENT_LENGTH. The config documentation page lists several other keys which Flask respects.

The application's main config.py is a set of classes, each of which looks like a config file, and #69 captures choosing among them.

This is good, straightforward work to do, but the reason I pushed back when you jumped into #69 is that I don't know that we have any examples that you can use for reasonable tests; my tests for https://github.com/ga4gh/server/pull/62 were all artificial. You could try setting DEBUG = True in a file and see how the server behavior changes?

**Comment by dcolligan** [comment]
So, we're going to have three ways of specifying configuration variables:

1) environment variable
2) configuration file
3) cmd line switch to pick from pre-defined configurations

Are all of these necessary?  Specifically, does 1 make sense anymore?

And, in any event, if some of these conflict with each other what should be the resolution steps?

**Comment by Naburimannu** [comment]
We implemented (1) and (2) because it was what Flask seemed to support. I think @jeromekelleher and I would both *think* (1) is unnecessary given (2) and (3), but I'd want to talk to people with actual deployment experience - @pashields, do have any sense of how much people use environment variables in production? Or have an idea who'd be good to ask?

The examples in the Flask doc lead me to expect that the configuration file is there mostly to override particular parts of the pre-defined sets. Since Flask doesn't seem to embrace command-line switches I don't see any guidance there about what you do when both environment variable and command line specify configuration files.
