### ISSUE TITLE
Update coverage checks to include branch misses

### ISSUE THREAD

**Issue by jeromekelleher** [ga4gh/server#700]
We use the [coverage](https://coverage.readthedocs.org/en/latest/index.html) module as integrated with [nosetests](https://nose.readthedocs.org/en/latest/) to measure the test code coverage.

Update the configuration in .travis.yml to include [branch coverage](https://coverage.readthedocs.org/en/latest/branch.html), and adjust the required threshold downwards to account for our lower coverage under this setup.

Examine the reports, and open some issues if there are places where code coverage could be improved by adding some test cases.

**Comment by dcolligan** [comment]
Fixed in #779
