### ISSUE TITLE
Add more tests to test_client_json test.

### ISSUE THREAD

**Issue by jeromekelleher** [ga4gh/server#704]
The command line interface client tool provides an easy way to get the JSON for objects in the server. For example, we can run 
```
$ python client_dev.py referencesets-search http://localhost:8000  -O json | jq .
```
to get
```json
{
  "name": null,
  "sourceURI": "TODO",
  "assemblyId": "TODO",
  "sourceAccessions": [],
  "ncbiTaxonId": 9606,
  "isDerived": false,
  "id": "R1JDaDM4LXN1YnNldA==",
  "md5checksum": "234ea63052f999c21c2bdb6f60e61038",
  "description": "TODO"
}
```
(We use jq here to pretty-print the JSON output for convenience).

The ``tests/end_to_end/test_client_json.py`` tests the command line interface to ensure that the JSON output is exactly what we expect. However, only a couple of the endpoints have been covered in this test. We should aim to cover all the arguments to the various commands so that we are sure we're parsing and interpreting the command line options correctly.

Expand these tests to include tests for variantsets-search, variantsets-get,  etc. Use 
```
$ python client_dev.py --help
```
to get a full list of the client endpoints.

The [client API documentation](http://ga4gh-reference-implementation.readthedocs.org/en/develop/api.html#client-api) will be useful for working the client commands required. See ``ga4gh/cli.py`` for example of how the client API is used, and for the source code of the command line client interface.

**Comment by andrewjesaitis** [comment]
Since this was merged, it can be closed as well.
