### ISSUE TITLE
Fix strand bug in ga2sam

### ISSUE THREAD

**Issue by jeromekelleher** [ga4gh/server#705]
(This issue is part of a trio of closely related issues #705, #706 and #707 that would be well suited to a group of people working together on.)

Running 
```
$ python ga2sam_dev.py http://localhost:8000 MWtnLXAzLXN1YnNldDpIRzAwMDk2OlNSUjA2MjY0MQ== --referenceId=R1JDaDM4LXN1YnNldDoz
```
with a server running on the ga4gh-example-data results in an error.

Fix this issue. The code for this is in ``ga4gh/converters.py`` in the ``SamConverter`` class.

**Comment by mp15** [comment]
Does #728 fix this?

**Comment by jeromekelleher** [comment]
I think this was solved earlier today to fix CI issues. I've just verified it's fixed. Closing.
