### ISSUE TITLE
Improve installation time/travis build time

### ISSUE THREAD

**Issue by jeromekelleher** [ga4gh/server#71]
Installation of the `ga4gh` package in a virtualenv is very slow because we must compile [pysam](https://github.com/pysam-developers/pysam) each time. This also happens for our TravisCI builds, which is bad for both us and TravisCI.

Can we speed this up in any way?  Would a [binary wheel](http://lucumr.pocoo.org/2014/1/27/python-on-wheels/)  for pysam on Travis's infrastructure be feasible/desirable?

**Comment by bioinformed** [comment]
+1 feasible (I use pysam wheels all the time)

**Comment by jeromekelleher** [comment]
Excellent! Any quick pointers on how to go about this?

**Comment by bioinformed** [comment]
The best solution is for Andreas and I to upload wheels to PyPI.  I'll ask
him if this is something he is willing to do.

Alternatively (and in the mean time), it isn't hard to set up a local wheel
cache to avoid rebuilding packages.  There are many sources of online
guides to setting up a local "wheelhouse", including
http://vincent.is/using-the-wheel/

**Comment by bioinformed** [comment]
Here is a StackOverflow answer that gives a very detailed recipe for
TravisCI:
http://stackoverflow.com/questions/18067073/speedup-virtualenv-creation-with-numpy-and-pandas

**Comment by dcolligan** [comment]
If I'm reading this correctly, it looks like we'd have to set up some remote server (not Travis) to host the wheels.  @jeromekelleher can we / do we want to do that?

Alternatively, if just anyone can upload arbitrary wheels to PyPI we could do that too... we could have a ga4gh-server-wheels package or something where we package pysam and whatever else we need.

**Comment by jeromekelleher** [comment]
I think the bandwidth requirements would be fairly small @dcolligan, and it would be well worth it. If we get them built, I'm sure we'll find the required infrastructure to serve them. How much hassle is it to build the wheels? I've had a quick look a few times, and it never seems particularly trivial.

PyPI isn't an option as binary wheels for Linux aren't supported AFAIK.

**Comment by dcolligan** [comment]
Here's some information on what travis is running:

http://docs.travis-ci.com/user/ci-environment/

"Travis CI virtual machines are based on Ubuntu 12.04 LTS Server Edition 64 bit"

**Comment by dcolligan** [comment]
Fixed in #225
