### ISSUE TITLE
Add FASTA output option for client list-reference-bases command

### ISSUE THREAD

**Issue by jeromekelleher** [ga4gh/server#712]
The server supports the list-reference-bases command to provide 
an easy way to get reference sequence over a given interval. This 
is implemented in the references-list-bases command in the command
line client. For example, we can run

``` bash
$ python client_dev.py references-list-bases http://localhost:8000 R1JDaDM4LXN1YnNldDoz
```

which prints out the sequences to stdout. We want to add the option
to print the sequences to stdout in FASTA format. Open `ga4gh/cli.py`
and find ListReferenceBasesRunner.
- First, fix a bug in the current implementation so it looks like

``` python
    def run(self):
        sequence = self._client.listReferenceBases(
            self._referenceId, self._start, self._end)
        print(sequence)
```
- Then add the following to `addReferencesBasesListParser`

``` python
    parser.add_argument(
        "--outputFormat", "-O", choices=['text', 'fasta'], default="text",
        help=(
            "The format for sequence output. Currently supported are "
            "'text' (default), which prints the sequence out directly and"
            "'fasta', which formats the sequence into fixed width FASTA"))
```
- Update ListReferenceBasesRunner to look like

``` python
    def run(self):
        sequence = self._client.listReferenceBases(
            self._referenceId, self._start, self._end)
        if self._outputFormat == "text":
            print(sequence)
        else:
            print("FASTA", sequence)
```
- Try this out with the `-O fasta` and `-O text` options.
- Write the FASTA output; the `textwrap` module will be useful
  here.
- Generalise the addOutputFormatArgument method to cover
  our needs here as well as the JSON output elsewhere.

**Comment by marghoob** [comment]
Working on this one.

**Comment by marghoob** [comment]
@jeromekelleher, need more clarification on the last bullet.

**Comment by david4096** [comment]
Moved https://github.com/ga4gh/ga4gh-client/issues/25
