### ISSUE TITLE
Create interesting client API example touching all parts of the API

### ISSUE THREAD

**Issue by jeromekelleher** [ga4gh/server#718]
We need an example of the API working across all parts of the data. We need to show how we can link up variants, references and reads with simple Python code. 

The API docs are [here](http://ga4gh-reference-implementation.readthedocs.org/en/develop/api.html).

The existing demo for using the [variants API](http://ga4gh-reference-implementation.readthedocs.org/en/develop/demo.html) is a good place to start.

**Comment by david4096** [comment]
Some WIP towards fulfilling this, examples with the variant API.

https://github.com/david4096/bioapi-examples

**Comment by jeromekelleher** [comment]
Looks good @david4096!
