### ISSUE TITLE
Generalise the captureOutput function

### ISSUE THREAD

**Issue by jeromekelleher** [ga4gh/server#720]
Generalise the captureOutput function in ``tests/end_to_end/test_client_json.py`` to also capture stderr, and take arbitrary functions as arguments.

- Create a new function ``utils.captureOutput`` function, and refactor ``test_client_json.py`` to use this.

- Add some test cases for this function to ensure it's working correctly.

**Comment by diekhans** [comment]
Instead of formatting command as strinsg and then parsing back into a vector of arguments, how about just constructing it as a vector?

- Hand constructing shell-compatible quoted strings is fragile and hard to get right in corner cases
- commands as lists are easier to incremental build

**Comment by delagoya** [comment]
+1
