### ISSUE TITLE
Add nose cover plugin to requirements.txt

### ISSUE THREAD

**Issue by dcolligan** [ga4gh/server#723]
Jerome was really sad when his demo didn't work.  Let's ensure this tragedy never happens again.

`nosetests` was reporting that there was no such flag as `cover-min-percentage`

I believe this is the required plugin: http://nose.readthedocs.org/en/latest/plugins/cover.html

**Comment by dcolligan** [comment]
I just built the server and ran the tests from scratch and didn't encounter any problems... it seems weird that we would encounter problems since that coverage plugin seems to come with nose by default... @jeromekelleher can you reproduce this?

**Comment by jeromekelleher** [comment]
Thanks for looking at this @dcolligan; it was a quirk of my setup. Turns out I had Debian Wheezy's version of nose installed which was on my path before the local version, and this was getting run instead.
