### ISSUE TITLE
Return reference in searchVariantSets

### ISSUE THREAD

**Issue by bartgrantham** [ga4gh/server#751]
Working on a beacon implementation that leverages the reference implementation and the Beacon v0.2 schema includes a field for the reference and id of a dataset: BeaconInformationResource.datasets.reference/id

It'd be nice of this was included in the results of the searchVariantSets call so that I could just pass this through to the user.

**Comment by dcolligan** [comment]
Returning additional information like that seems incongruous with the design of the stack.  What do you think, @jeromekelleher ?

**Comment by jeromekelleher** [comment]
In the schema there is a field ``VariantSet.referenceSetId`` that we're not setting at the moment @dcolligan, which is a bug on our side. We need to figure out a way to tie VCF's and referenceSets together. Technically we could do this using some values in the header of the VCF, but I don't know how well standardised they are (not very, I suspect). Basically, we need to decide whether we come up with our own out-of-band method of tying a referenceSet to a VariantSet or if we require the existence of a particular header in the VCF. Either way it's going to be messy in practise.

**Comment by jeromekelleher** [comment]
Closed by #1166.
