### ISSUE TITLE
Info tag mushes up arrays and ints into strings so can't roundtrip SAM

### ISSUE THREAD

**Issue by mp15** [ga4gh/server#758]
Whilst attempting to write a test for SAM roundtrip I found the following:

```
AssertionError: Lists differ: [('PG', 'colt'), ('RG', 'fish'... != [('PG', 'colt'), ('RG', 'fish'...

First differing element 2:
('XX', [12561, 2, 20, 112])
('XX', '[12561, 2, 20, 112]')

- [('PG', 'colt'), ('RG', 'fish'), ('XX', [12561, 2, 20, 112]), ('YY', 100)]
+ [('PG', 'colt'), ('RG', 'fish'), ('XX', '[12561, 2, 20, 112]'), ('YY', '100')]
?                                         +                   +          +   +
```

The line responsible is:
https://github.com/ga4gh/server/blob/a9a7c57e538298a2fbc38fe7fabf9522abd1870e/ga4gh/datamodel/reads.py#L594

**Comment by jeromekelleher** [comment]
Isn't this what's required by the schema though?

https://github.com/ga4gh/schemas/blob/master/src/main/resources/avro/reads.avdl#L280

Awesome that you're looking at this @mp15!

**Comment by mp15** [comment]
Yes the schema is rather silly in that respect, I suspect it might have been a placeholder. Unless anyone can think of a good reason why we love casting to string I'll put in a pull request to schema and see what folk say.

**Comment by jeromekelleher** [comment]
Sounds good to me @mp15, let's see what folks think on the schema side.

**Comment by dcolligan** [comment]
Can we close this since this is a schema issue?

**Comment by mp15** [comment]
Not really unless we want to drop support for ga2sam_dev.py and info fields in general. The server may be compliant but that means nothing if it doesn't work for the common use case and it's still going to require code changes to fix. If I can't get the schema change approved we may have to make a list of well known tags and their types and use that to recover type instead.

Incidentally for reference the schema issue is schema#445.

**Comment by diekhans** [comment]
See https://github.com/ga4gh/schemas/issues/445 for discussion on richer and common representations of attributes.

**Comment by david4096** [comment]
We are now able to better represent [other types](https://github.com/ga4gh/schemas/blob/master/src/main/proto/ga4gh/reads.proto#L75) in our info fields but the server still coerces them to strings [here](https://github.com/ga4gh/server/blob/master/ga4gh/datamodel/reads.py#L170). To satisfy this, some introspection on the type of the tag will have to be done before adding to the info field.
