### ISSUE TITLE
use accessions rather than chromosome names for reference sequences 

### ISSUE THREAD

**Issue by reece** [ga4gh/server#759]
Using chromosome names as labels for reference sequences is likely to lead to insidious bugs and user errors. It would be much better to use identifiers that map to immutable sequences (e.g., a sequence hash or accession), then map these to human aliases. In addition to decreasing the likelihood of bugs, this approach makes it much easier to handle patch regions and alternate assemblies.

**Comment by reece** [comment]
@dcolligan: created issue as you requested at the hackathon.

**Comment by jeromekelleher** [comment]
I completely agree @reece, using labels like `chr1` in code is a terrible idea. However, this is a schemas issue --- we can only implement what's defined there. I think your perspective would be very valuable in the great ID/name/label etc debate. See https://github.com/ga4gh/schemas/issues/418

My take is that _all_ API linkage points between objects should be via server IDs, without exception.

**Comment by reece** [comment]
I thought it should be schemas too, but Danny asked for it here. I was unaware of ga4gh/schemas#418 and agree that it should be there.

I'm going to close this issue since it's neither a bug nor an immediately actionable task.

**Comment by dcolligan** [comment]
@reece sorry to lead you astray here!

**Comment by reece** [comment]
No prob! And I didn't mean for that to read as blame!
I was just telling someone that I'm looking forward to the next hackathon!
