### ISSUE TITLE
Extend client library to include full protocol

### ISSUE THREAD

**Issue by jeromekelleher** [ga4gh/server#76]
The client library needs to support the full GA4GH protocol. We should develop and test this against existing implementations.

**Comment by dcolligan** [comment]
Working on this.

**Comment by jeromekelleher** [comment]
Not sure what happened here, but reopening this as we haven't implemented the complete protocol yet,

**Comment by dcolligan** [comment]
I think GitHub automatically closes an issue if it is referenced in a commit that is merged to master... kind of annoying (since it implies that issues can't be long running and addressed in a series of commits)

**Comment by dcolligan** [comment]
The next PR will close this issue... there's still three client endpoints in the 0.5.1 spec to implement
