### ISSUE TITLE
Simplify seqfetcher code for specific needs in download_data.py

### ISSUE THREAD

**Issue by jeromekelleher** [ga4gh/server#768]
This is a follow on from PR #754, which is in turn adressing #635 and #719. Closing this issue should resolve both of these issues too.

The code in #754 is very powerful, but is really a lot more than we need. All we want is a simple method to download GRCh37 sequences, and no more. Therefore, adapt the code in #754 as follows:

1) Copy the function fetch_seq_ncbi to ``scripts/download_data.py``, and rename to fetchSequence. CamelCase the variables and rename to follow the local conventions (e.g, use accession, startIndex rather than acc, start_i).
2) Replace the code in downloadFastas where we make calls to the ENA apis to use this function instead.
3) Add  command line option ``--test`` that runs the doctests for the ``fetchSequence`` function.
4) Change the accessions around line 135 from (e.g.) CM000663.2 to CM000663.1.

@reece -- would you like to tackle this? All the hard work is done, and it's just a case of removing stuff. No worries if you don't want it.

**Comment by reece** [comment]
Okay, seqfetcher code incorporated.

I did 1, 2, 4 as described. 

I did not add the --test option (3, above) because I would like to encourage that we add more conventional doctests support separately. (If this were part of the main server code, I would consider testing essential, but that's not the case here.)

I also verified that the previous GRCh38 reference excerpts matched those now downloaded for GRCh37, byte-for-byte after removing LFs to account for wrapping width differences.

Tests pass.

PR to follow in a few minutes.

**Comment by jeromekelleher** [comment]
Looks great, thanks @reece. Re doctests, what sort of thing would you like to see done for this? I've never really used doctests, so any input you'd have here would be very valuable.

**Comment by reece** [comment]
Follow up to comment re: GRCh37 and 38 sequence equivalence: The sequences are not equivalent, but tests still pass.

**Comment by reece** [comment]
@jeromekelleher I recommend adding doctests for commonly used public functions that don't involve extensive computation. This should probably be part of the documentation project.

Then, one can test them by adding something like the following to setup.cfg (adjacent to setup.py):

```
[nosetests]
doctest-extension=rst
doctest-options=+ELLIPSIS,+NORMALIZE_WHITESPACE
with-doctest=1
```

(For an example, see https://bitbucket.org/biocommons/hgvs/. All the documentation, including the README.rst is run through doctests. If the doctests fail, the CI tests fail just as if a unittest failed.)

**Comment by jeromekelleher** [comment]
Sounds good to me @reece --- I've opened a new issue on it #775.
