### ISSUE TITLE
Step-by-step installation instructions needed for OSX

### ISSUE THREAD

**Issue by jeromekelleher** [ga4gh/server#769]
Lots of people struggled to get the server working on OSX during the hackathon. We need clear instructions to install the prerequisites using (e.g.) homebrew. The crypto requirements are particularly problematic, so we need to improve this.

**Comment by mbaudis** [comment]
+1 on this!

**Comment by dcolligan** [comment]
@david4096 Please close this if #1279 solved this

**Comment by david4096** [comment]
Thanks @dcolligan
