### ISSUE TITLE
Move git branching model to master/topic/release

### ISSUE THREAD

**Issue by macieksmuga** [ga4gh/server#771]
Move the git branching model of this repo to match the branching models of the other ga4gh repos:
Master branch has the latest development checkins that pass CI, topic branches for active development of features and release branches for release maintenance.

**Comment by dcolligan** [comment]
Was there ever a whiteboard session at the conference about releases?

**Comment by diekhans** [comment]
just a brief presentation by Benedict.

**Comment by jeromekelleher** [comment]
What do we need to do to make this happen?

1. Clear out any remaining PRs against develop;
1. Update developer docs to s/develop/master/g
1. mv develop master, and update GitHub's default branch.

Anything else?

**Comment by dcolligan** [comment]
4. signal to everyone somehow (probably creating an issue) that they should now make pulls against master

I think that covers it.

**Comment by dcolligan** [comment]
This is accomplished.  Closing.
