### ISSUE TITLE
Protobuf transition overview

### ISSUE THREAD

**Issue by jeromekelleher** [ga4gh/server#784]
This issue is to collect discussion about the transition to protobuf, and to provide a high-level overview of the planned transition.

1. On the protobuf branch, we make the minimal possible changes to the current server in order to replace Avro. This will happen through a series of PRs. The first PR will probably be the initial chanegover for the main server code, with any problematic tests disabled via nose decorators. Subsequent follow-up PRs will then gradually reenable these test cases, or replace them if they are too Avro specific.

2. Once the protobuf schema has been formally accepted upstream in the schemas repository, we can then merge the protobuf branch into our mainline development branch. Mainline development will then happen on protobuf based server.

3. Once we are sure we can make a release based on the protobuf version that can be reliably installed by users, we begin the process of changing the codebase over from the current camelCase convention to snake_case. Once we have fully transitioned to snake_case, we can consider the conversion to protobuf complete.

**Note** During the transition period, we will have an odd coding convention that is a mixture of snake_case when we are interacting with the protobuf generated classes, and the existing camelCase convention for everything else. This will cause confusion, but it seems to be the lesser of a number of unpalatable evils.

**Comment by jacmarjorie** [comment]
Question - perhaps I am missing something, but it looks like responses are being returned as JSON, at least currently. Are there plans to support receiving protobuf messages as requests and/or sending protobuf messages as the response, I'm assuming in addition to JSON?

**Comment by jeromekelleher** [comment]
The initial plan is to keep  JSON on-the-wire, and to move to protobuf as the Interface Definition Language. There will be a few minor incompatibilities between the different versions of the protocol (i.e. the one defined in Avro and the one defined in Protobuf), but no more that we would see between two minor versions of the protocol in any case.

Once the dust has settled, I think that there is strong interest in adding protobuf as a second, optional encoding for messages on-the-wire.

**Comment by dcolligan** [comment]
@jeromekelleher can you provide an update on the to-dos wrt protobuf or close this issue?

**Comment by jeromekelleher** [comment]
Closing --- protobuf is done. The only remaining issue is the snake_case and camelCase mess, but this is something we'll just have to work at to fix over time.
