### ISSUE TITLE
change pypi package name to allow for other GA4GH packages

### ISSUE THREAD

**Issue by diekhans** [ga4gh/server#785]
We are going to want to have a python client library in the near future,  and hopeful more python software

**Comment by jeromekelleher** [comment]
Why do we want to do this? It'll be a lot of work pulling apart the client and the server, and I don't think we'd gain much from it. For example, we need pysam for both, and this is by far the biggest dependency. I think we should worry about this at a later date when it becomes a problem.

**Comment by diekhans** [comment]
This PR is only to setup pypi to allow for multiple GA4GH
packages with clear names.  The longer we go with package ga4gh
being the ga4gh reference server, the hard it will be to change.

I agree it is not currently a priority to separate out the
python client library.  However, if we are successful, we will
want at least one python client library.  It might not even be
the one with the server.  Hopefully we have thousands of users
of clients for ever server user.

It's not the weight of combined packages in bytes, it's the
weight in mental space of going through large doc to only use a
small part of it.  Having to do a full server release to get
client library development is also very restrictive.

I would really hate for someone to have to download the
compliance suite to get a Java client library.

**Comment by jeromekelleher** [comment]
OK, I agree with you in principle. Are there any ideas on the mechanics of this though? We have a ``ga4gh`` package, which currently maps to the name of the pypi package. This is very much the recommended way to do things. Unless we go for a wholesale reorganisation of the code, I think any renaming is going to make things worse.

**Comment by diekhans** [comment]
The issues is really is what do we want the python name space to
look like going forward.  While the ref server is the only
significant piece of software, ga4gh is a lot bigger then the
server.

While having ga4gh.refserver ga4gh.clientlib, etc would be ideal,
I don't know how well this works in practice.  I know if you
have two ga4gh on PYTHONPATH, it doesn't work.  However, with
virtualenv, it depends on the install.

Other option would be ga4gh_refserver, which hopefully isn't a
painful rename.

**Comment by jeromekelleher** [comment]
@dcolligan, any thoughts here?

**Comment by dcolligan** [comment]
I'm +0 on this right now.  We know we're going to have to split the code up at some point, but that's a lot of work, and there doesn't seem to be a compelling reason to do it right now.  The server package is going to have to depend on the client package (for running a lot of the tests) so we should have the infrastructure in place to sync these repositories and a plan for how that is done before going forward with the rupture.  The rest of the discussion, I think, is just a battle about naming where we just need to pick some name(s) and go with it.

**Comment by diekhans** [comment]
This is *not* a suggestion to split the code at this time. Only
to change the package naming in pypi so that it is easy to split
in the future.

**Comment by jeromekelleher** [comment]
There's no easy way to do this @diekhans; if we change the name of the package, we have to change the code. All of the code. And all the docs. Given that we're supposed to be releasing in a matter of days, and we have a major technology transition going on concurrently, I have no appetite for anything that makes life any more difficult. We have lots of work to lose, and absolutely nothing to gain in the short term.

Look at it this way. We're squatting on the ga4gh package name in pypi so no one else can take it. We can do what we want with this in the future when we have a problem that we need to solve. Right now, there is no problem, so let's not try to solve it. There's enough to do.

**Comment by david4096** [comment]
I made a branch of the server that removes unnecessary dependencies when just wanting to run the client. I'm working on demonstration usage of a GA4GH compliant server and I believe there's good cause to have the client available as a standalone package.

https://github.com/david4096/server-1/tree/client

**Comment by jeromekelleher** [comment]
I agree it is useful to have a standalone client, but it does imply some maintenance overhead. Do we maintain these packages separately, or do we keep the master copy in the server repo and copy across the code each time we want to make a release of the client?

More fundamentally, _why_ are we doing this? If it's just to make installation easier and to avoid compiling pysam (which is a drag) then there are other ways to do this. Making a package for [BioConda](http://bioconda.github.io/) would make installing the dependencies simple and would mean that everything installs in a few seconds. I very, very much doubt that the average client user would care if they pulled in some extra code that allowed them to run servers as well as the client.

**Comment by diekhans** [comment]
The main reason for splitting of the client libraries isn't
bytes consumed, it's neurons consumes understanding it.

The client and server are suppose to be independent components
bound together only by the API.  Having the client library
buried in the server means having the documentation buried in
the server.  We would like to have client libraries developed
for multiple languages, and having similar conceptual models.

While someone could go off a develop an independent python
library, I would rather have us lead it. Being buried as part of
the server doesn't lead.

Note, this ticket is about setting a path to do this by changing
pypi package structure to not have a monolithic python project.

**Comment by jeromekelleher** [comment]
Here are the docs: http://ga4gh-reference-implementation.readthedocs.org/en/stable/api.html

Other than the side bar at the side of the screen, there is no indication _at all_ that the code is bound up with the server. I agree that in the fullness of time it will be good to separate out the client and server code, but for now:

1. Realistically, any user of our client library _must_ use our server, as there are zero other implementations of the 0.6 API at the moment. Therefore, binding them together in the same package is substantially easier for this putative user.

2. We expect the API to evolve fairly rapidly over the next 6 months. Having separate client and server packages substantially increases the probability of version mismatches, and therefore troubles for users.

3. There are a bunch of real problems that we need to solve right now, and splitting the package makes our lives needlessly complex for no real gain.

So, I would like to shelve this issue until it becomes a real problem. This means, at a minimum, some other GA4GH server working with the 0.6 API. I agree that compiling pysam all the time is a real problem, but that's something that affects the server too, so we should look into other ways to solve this (BioConda is a good solution IMO).

**Comment by david4096** [comment]
+1 on making the namespace easier to use for others

**Comment by dcolligan** [comment]
related to #1230

**Comment by david4096** [comment]
https://github.com/BD2KGenomics/ga4gh-integration/issues/38

**Comment by david4096** [comment]
@dcolligan it's this one, closes this https://github.com/ga4gh/server/pull/1454
