### ISSUE TITLE
Use setuptools_scm to set version numbers

### ISSUE THREAD

**Issue by jeromekelleher** [ga4gh/server#790]
The pypa now recommend using [setuptools_scm](https://pypi.python.org/pypi/setuptools_scm/) to set version numbers from git tags. This looks very useful indeed --- we should use it unless some gotchas happen along the way.

Hat tip to @reece!

**Comment by reece** [comment]
On Wed, Nov 18, 2015 at 12:35 PM, Jerome Kelleher <notifications@github.com>
wrote:

> The pypa now recommend using setuptools_scm
> <https://pypi.python.org/pypi/setuptools_scm/> to set version numbers
> from git tags. This looks very useful indeed --- we should use it unless
> some gotchas happen along the way.
>
> Hat tip to @reece <https://github.com/reece>!
>

I'm happy to implement this. The benefit is that the repo becomes the sole
authoritative source for versioning in code, docs, and packaging. My
release process is essentially 'hg tag 1.2.3 && hg push && python setup.py
sdist bdist_egg bdist_wheel upload'. (setuptools_scm works with hg and git)

Unknowns: 1) What's the best way to work into CI flow? 2) How to work into
java packaging. No obvious blockers for either, but needs thought.

**Comment by jeromekelleher** [comment]
Go for it!

1) Do we need to integrate this into CI flow?
2) I'm not sure what Java packaging has to do with this; this is just for the server, right?

**Comment by reece** [comment]
On Mon, Nov 23, 2015 at 1:02 PM, Jerome Kelleher <notifications@github.com>
wrote:

> 2) I'm not sure what Java packaging has to do with this; this is just for
> the server, right?


I was thinking schemas too, but they're definitely distinct issues.

-Reece

**Comment by dcolligan** [comment]
I'm -0 on integrating this into the CI flow, but the steps should be documented in the release process (see #810).

If we did integrate this into CI, we could just simulate a release with a dummy version number at the end of CI.

**Comment by dcolligan** [comment]
Fixed in #822
