### ISSUE TITLE
netLoc property in object obtained from urlparse.

### ISSUE THREAD

**Issue by macieksmuga** [ga4gh/server#794]
I'm getting an error on attempting to run the develop branch of the server:
```
  File "/Users/maciek/Documents/dev/maciek-ga4gh-server/ga4gh/frontend.py", line 202, in configure
    dataSource.netLoc, dataSource.path))
AttributeError: 'ParseResult' object has no attribute 'netLoc'
```
I see that there's a `netloc` property on `urlparse.ParseResult` objects, but none capitalized as `netLoc`.

**Comment by jeromekelleher** [comment]
Thanks @macieksmuga, exactly right. Clearly our test coverage on the configure function is pretty shaky...
