### ISSUE TITLE
GA4GH server 0.1.2 broken

### ISSUE THREAD

**Issue by mkzia** [ga4gh/server#797]
It seems that the update has broken the server or the documentation have not been updated. I am very sure that couple of weeks ago when I followed the API demo documentation things were working. 
There seems to be two problems.

First, the server now requires the following directories that are not part of the example data set
```
OSError: [Errno 2] No such file or directory: '*/ga4gh-example-data/variants'
OSError: [Errno 2] No such file or directory: '*/ga4gh-example-data/references'
OSError: [Errno 2] No such file or directory: */ga4gh-example-data/reads'
```
Second, executing 
```
"curl --data '{}' --header 'Content-Type: application/json' \http://localhost:8000/datasets/search
```
gives the following error message
```
{"errorCode": 523835337, "message": "The request path was not found"}
```

**Comment by jeromekelleher** [comment]
Thanks for the bug report @mkzia. A few more details would be useful: are you using the version of the server from pypi or from github? 

I agree the situation with the released version and the version in github being quite different is very unfortunate and confusing. We hope to  rectify this soon with an updated release, and we can then update all of the documentation as well.

**Comment by mkzia** [comment]
I downloaded it using pip, which shows that the version is ga4gh==0.1.2.

**Comment by jeromekelleher** [comment]
The correct documentation should then be 

http://ga4gh-reference-implementation.readthedocs.org/en/stable/index.html

Does this clear things up? 

Unfortunately it's not at all clear that this is the case, and I apologise for the confusion. The main problem is that the development version has diverged quite a lot from the released version. Hopefully we'll be able to release an update soon.

**Comment by mkzia** [comment]
Yes. I was following the wrong documentation. Thanks!

**Comment by jeromekelleher** [comment]
OK, thanks @mkzia. Closing this issue.
