### ISSUE TITLE
Multiple Read Group Requests fail test

### ISSUE THREAD

**Issue by david4096** [ga4gh/server#801]
<img width="917" alt="screen shot 2015-12-09 at 11 19 48 am" src="https://cloud.githubusercontent.com/assets/3795586/11695953/da886884-9e66-11e5-8c61-c7e2d2f55052.png">

Line 495 in backend.py tests for the number of readGroupIds explicitly

            if len(request.readGroupIds) != 1:
            raise exceptions.NotImplementedException(
                "Exactly one read group id must be specified")

Current documentation suggests that multiple read group IDs should be accepted.

"A query which specifies only read group IDs yields all reads in those read groups, including unmapped reads."

http://ga4gh-schemas.readthedocs.org/en/master/schemas/readmethods.html

**Comment by jeromekelleher** [comment]
This is a known limitation in the server --- basically, this is too hard to do in our stateless design under the current paging requirements.
