### ISSUE TITLE
Change ``ga4gh_`` prefix to ``ga``?

### ISSUE THREAD

**Issue by jeromekelleher** [ga4gh/server#813]
Currently, we have two first class command line interface programs: ``ga4gh_server`` and ``ga4gh_client``. These are somewhat verbose and clumsy. I propose that we replace these with ``gaserver`` and ``gaclient`` respectively. These are shorter and more POSIX-y. They do not clash with any program names in the Ubuntu repositories. There is a package on PyPI called ``gaclient`` but I don't think they export a command line interface.

Since we are breaking backward compatibility with 0.1.x series with the 0.2.x series, I think now is the time to make this change, if we are going to make it.

Thoughts?

**Comment by dcolligan** [comment]
I like the clarity of the current names

**Comment by diekhans** [comment]
I would agree with Danny that a simple `gaclient' isn't very
clear.

How about just `ga4gh' for the client, and leave the server
ga4gh_server.  Very few unix client programs name themselves
*client.  It's ftp and ftpd, not ftpclient.

**Comment by jeromekelleher** [comment]
The idea with the `ga` prefix is to be consistent across all of our CLIs. Right now, we have
```
ga4gh_client
ga4gh_server
ga4gh_configtest
ga2vcf
ga2sam
```
We'll also soon have ``ga4gh_repo`` or something similar. I agree ``gaclient`` is less obvious than ``ga4gh_client``, but it is easier to type, and CLI users are used to remembering these sort of obscure things. If I know at all GA4GH programs start with ``ga``, I can type ``ga``, tab complete and get a list of them.

**Comment by diekhans** [comment]
`ga' doesn't seem very obvious to me.

All except for ga4gh_client are infrequently used.

I would suggest following the unix conventions and calling
rename `ga4gh_client' to simple `ga4gh', akin to `ftp'
instead of `ftp_client'.

**Comment by jeromekelleher** [comment]
OK, what do you suggest so @diekhans:
```
ga4gh_client -> ga4gh
ga4gh_server -> ga4ghd
ga4gh_configtest -> ??
ga2vcf -> ga4gh2vcf
ga2sam -> ga4gh2sam
```
and what do we call the repo manager? ga4ghrepomanager?

**Comment by diekhans** [comment]
Suggest :
        ga4gh_client -> ga4gh

everything else ga4gh_*

although I do like the ring of ga4ghd ;-)

**Comment by reece** [comment]
On Mon, Jan 4, 2016 at 7:59 AM, Danny Colligan <notifications@github.com>
wrote:

> I like the clarity of the current names


I like the ga4gh prefix over ga.
I like parallelism and patterns.
I would reserve naked ga4gh for future use, such as a subcommand-style
interface (a la git).
Ergo, I'd do nothing to rename them.

**Comment by jeromekelleher** [comment]
OK, it seems like there isn't enough enthusiasm for name changes right now, and no consensus on what we should rename to. Closing the issue.
