### ISSUE TITLE
Refactor backends classes for dependency injection

### ISSUE THREAD

**Issue by kerrydc** [ga4gh/server#82]
Our backends package now is difficult to test, due to the dependency the VariantSet classes have on the filesystem. We should change the VariantSets to take objects in their constructors instead of file paths, and create these objects using a factory.

**Comment by jeromekelleher** [comment]
Sounds good @kerrydc.

**Comment by dcolligan** [comment]
Working on this

**Comment by jeromekelleher** [comment]
Closing this, as it has been effectively solved in recent developments.
