### ISSUE TITLE
Version 0.2.0 released!

### ISSUE THREAD

**Issue by jeromekelleher** [ga4gh/server#824]
Version 0.2.0 has been pushed to pypi and the documentation on readthedocs updated.

Next stop, version 0.2.1!

**Comment by dcolligan** [comment]
(clap, clap clap)

Is creating issues like this necessary?  People subscribed to the repo already get a notification when a GitHub release is created (I think?).

**Comment by jeromekelleher** [comment]
We should figure out a way to announce stuff properly. Should we set up a mailing list for server users? Or just spam the DWG lists?

**Comment by skeenan** [comment]
@dcolligan not sure I saw any automated notification of a release in addition to this message. @jeromekelleher I could create a ga4gh-dwg-announce mailing list. How does that sound?

**Comment by jeromekelleher** [comment]
@skeenan I like the sound of the ga4gh-dwg-announce --- this would be a good place to make these announcements.

**Comment by diekhans** [comment]
Spam DWG list.  We need to get the word out widely.
