### ISSUE TITLE
Variant Annotation - reformat HGVS

### ISSUE THREAD

**Issue by sarahhunt** [ga4gh/server#838]
HGVS descriptions moved to nested sub-record:

https://github.com/ga4gh/schemas/pull/531/files

**Comment by david4096** [comment]
Resolved in https://github.com/ga4gh/server/pull/845
https://github.com/david4096/server-1/commit/93ede8a8a0934f76a6cac9e0f7193dc3932fe0a8#diff-f9ce58fdc26b5bb89ea0a4aa47a608faR661

**Comment by david4096** [comment]
I reformatted the responses to follow this spec and will be reflected in #845. @sarahhunt could you give us some idea of what you expect for HGVS genomic coordinates? Is this read directly from the line of the VCF file or does it need to be computed somehow?

**Comment by sarahhunt** [comment]
@david4096  - I would expect it to be read from the file. I didn't notice where the ref server annotation VCF was, but I see HGVSg descriptions aren't in the compliance test data , so I have added them in  https://github.com/ga4gh/compliance/pull/162. I can add them to the server VCF if you point me to it.

**Comment by david4096** [comment]
Fixed with #868
