### ISSUE TITLE
Simulator required for variant annotations

### ISSUE THREAD

**Issue by jeromekelleher** [ga4gh/server#842]
There is currently no test coverage for the majority of the variant annotation code, and so it is very difficult to judge whether it works correctly or not. The best way to get test coverage is to implement a simulator, following the example of all the other data model objects.

The simulator does not have to be particularly realistic, it just has to be able to generate some data randomly so we can test the full API stack using the existing testing methods.

**Comment by david4096** [comment]
Closed with #884
