### ISSUE TITLE
Full test suite in test_simulated_stack required

### ISSUE THREAD

**Issue by jeromekelleher** [ga4gh/server#843]
The variation annotations code needs tests for all API endpoints in the test_simulated_stack test module. This should exercise all API functionality, and ensure that the correct behaviour is observed based on simulated data.

Depends on #842.

**Comment by macieksmuga** [comment]
Quick procedural question: Does this issue (and other topic branch-specific ones like it) get resolved once the solution code is accepted via PR into the topic branch, or when it gets into master?

**Comment by jeromekelleher** [comment]
Topic branch. Anything labelled with "Variant Annotation" refers to the topic branch.

**Comment by jeromekelleher** [comment]
Your call @david4096; it looks good to me, but I don't have time to really get into the guts of it.
