### ISSUE TITLE
Data driven tests for variant annotations required

### ISSUE THREAD

**Issue by jeromekelleher** [ga4gh/server#844]
There are no data driven tests for variant annotations to check that input data of various forms is handled correctly. Test data should be added to the test suite in the appropriate place, and data driven tests added.

**Comment by david4096** [comment]
The python `vcf` module is used for the data driven variant sets, but it gives different results from `pysam` for VCFs that have a split info field. This causes annotated VCFs to fail a data driven test.

https://gist.github.com/david4096/925f6ebad62fa0bec0e6

**Comment by diekhans** [comment]
@dcolligan can you help with this?

**Comment by david4096** [comment]
Closed with #917
