### ISSUE TITLE
Break cli.py into separate modules

### ISSUE THREAD

**Issue by dcolligan** [ga4gh/server#847]
`cli.py` is getting pretty huge, there are several distinct sections marked off by huge comments delineating them, and there is no (or not much?) shared functionality between the sections -- this is usually a good clue that we should break each section into its own module.

**Comment by jeromekelleher** [comment]
Sure --- make a cli package with submodules and keep shared code in the ``__init__.py``? Perhaps it would be good to do this after the initial version of the repo management tool, so we get a better idea of what should go where?

**Comment by dcolligan** [comment]
Fixed in #1381
