### ISSUE TITLE
New development branch is master!

### ISSUE THREAD

**Issue by jeromekelleher** [ga4gh/server#852]
The new main development branch is now ``master``, and the develop branch has been deleted. 

Until we release 0.1.1, the [stable docs](http://ga4gh-reference-implementation.readthedocs.org/en/stable/development.html) will be inaccurate.

In addition, this branch is now [protected](https://github.com/blog/2051-protected-branches-and-required-status-checks) and requires CI checks to pass before code can be merged.

**Comment by macieksmuga** [comment]
Many thanks, @jeromekelleher!

**Comment by jeromekelleher** [comment]
Everyone should have taken this on board by now. Closing.
