### ISSUE TITLE
Create wiki page documenting branch managers, active long-running branches

### ISSUE THREAD

**Issue by dcolligan** [ga4gh/server#870]

**Comment by dcolligan** [comment]
Notes from call:
g2p - brian
variant_annotations - david
protobuf - jerome
rna - sean

**Comment by dcolligan** [comment]
Page is here: https://github.com/ga4gh/server/wiki/Long-running-topic-branches-and-branch-managers

**Comment by jeromekelleher** [comment]
Thanks @dcolligan.
