### ISSUE TITLE
Client callsets text output garbled

### ISSUE THREAD

**Issue by jeromekelleher** [ga4gh/server#875]
In the protobuf implementation, the output of calls is garbled in the client. Run

```
$ python client_dev.py variants-search http://localhost:8000 --pageSize=5 --callSetIds=MWtnLXAzLXN1YnNldDptdm5jYWxsOkhHMDA1MzM=
```

The output is no longer on a single line.

**Comment by jeromekelleher** [comment]
Also garbled without callsets argument.

**Comment by david4096** [comment]
Moved https://github.com/ga4gh/ga4gh-client/issues/27
