### ISSUE TITLE
Proto definitions not within ga4gh package

### ISSUE THREAD

**Issue by jeromekelleher** [ga4gh/server#876]
Currently, the protobuf schema definitions live in the ``proto`` directory. While this works well for development, there are potential issues with packaging. For example, when we create a distribution package, we will need to install two Python package ``ga4gh`` and ``proto``. This will create potential conflicts with existing packages. In any case, keeping source code required for the ga4gh package in an external namespace is confusing and untidy.

We should seek to move all the proto definitions to within the ga4gh directory, so that all code is encapsulated within the ``ga4gh`` package. This requires schema updates. Comments from @palfrey in #799:
 >>So, would it be possible to have the proto stuff contained in the ga4gh package?

> Yes, but not without changes to schemas. They all specify the package path as starting "proto", and this cascades down to their dependencies, so it would have to change there as well. I had a quick go at it, and here's the experimental set of changes that would do that https://github.com/lshift/ga4gh-schemas/compare/proto3...lshift:proto3-ga4gh?expand=1

**Comment by david4096** [comment]
Currently implemented [as suggested](https://github.com/ga4gh/server/tree/master/ga4gh), so can close. Stands to change with https://github.com/ga4gh/server/pull/1446 .
