### ISSUE TITLE
JSON for info fields incompatible

### ISSUE THREAD

**Issue by jeromekelleher** [ga4gh/server#879]
Info fields such as found in variants and reads currently looks like
```json
"info": {"MD": ["63"] }
```
Under the current protobuf implementation they look like
```json
{"info": {"MD": {"values": [{"stringValue": "63"}]}}
```
These are clearly incompatible. Is this an intentional schema difference, or part of our implementation?

**Comment by jeromekelleher** [comment]
@palfrey, can you comment on this please? This seems like an important issue.

**Comment by palfrey** [comment]
This is a schema issue really, as the JSON output is an accurate depiction of what the Protobuf schema says. Part of that could be solved by making the maps string -> "list of string" rather than the more precise typing of the Value type, but the best we could do is then

```json
{"info": {"MD": {"values": ["63"]}}
```

because we'd need to do 

```protobuf
message StringList {
    repeated string value = 1;
}

message CallSet {
// ... lots of other fields ...
  map<string, StringList> info = 7;
}
```

as sadly
```protobuf
map<string, repeated string> info = 7;
```
isn't a valid Protocol buffer message, but that's what the Avro definition was doing with `map<array<string>> info = {};`

**Comment by jeromekelleher** [comment]
OK, thanks @palfrey. One to add to the incompatibility list.

**Comment by calbach** [comment]
@palfrey to double check, the original JSON in this issue was produced via a `map<string, google.protobuf.ListValue>`. If so, this is not working to [spec](https://developers.google.com/protocol-buffers/docs/proto3?hl=en#json) (see ListValue); I will reach out to the developer immediately.

**Comment by palfrey** [comment]
@calbach Confirmed. I thought for a bit it might be because the schemas repo had a copy of src/main/resources/proto/google/protobuf/struct.proto rather than using the upstream one, but I've just tried with that and still seems to get the same result...

**Comment by calbach** [comment]
OK, reached out to the author and confirmed that Python Proto<->JSON support for `ListValue` has not yet been released; however it is in progress. Will provide an ETA as soon as I have one.

**Comment by calbach** [comment]
OK, I've cherry-picked the necessary functionality into protobuf master: https://github.com/google/protobuf/pull/1195. Perhaps you can integrate this locally at least to validate your approach.

I've been told there will be a tagged release this month. That's the best ETA I have at the moment unfortunately.

**Comment by calbach** [comment]
The functionality should now be available by upgrading to 3.0.0b2.post2. https://pypi.python.org/pypi?:action=display&name=protobuf&version=3.0.0b2.post2

I pulled this in locally and verified that it produces JSON as expected for the `ListValue` case.

**Comment by jeromekelleher** [comment]
Thanks @calbach, I'll test this out over the next couple of days. Apologies for the slow response.

**Comment by david4096** [comment]
This works and is used throughout in the `info` field. https://github.com/ga4gh/server/blob/master/ga4gh/datamodel/bio_metadata.py#L49
