### ISSUE TITLE
Implement internal api for getCallset and searchCallset on LocalClient

### ISSUE THREAD

**Issue by andrewjesaitis** [ga4gh/server#893]
Currently there is a cli endpoint for get and search callset, but no internal api on the local backend. At the very least this prohibits writing integration tests as discussed in PR #888, but would additionally make the internal api more consistent.

**Comment by andrewjesaitis** [comment]
I'll pick this up

**Comment by jeromekelleher** [comment]
Has this been resolved @andrewjesaitis?

**Comment by andrewjesaitis** [comment]
Yes. Merged in with PR #912
