### ISSUE TITLE
clean up rna topic branches

### ISSUE THREAD

**Issue by saupchurch** [ga4gh/server#895]
per PR #836
1) create new protected topic branch for rna api development off master
2) remove existing rna branches

**Comment by jeromekelleher** [comment]
Sounds good @saupchurch --- do you have permissions to do this, or do you need me or @dcolligan to create the branches? Ping one of us here or offline if you need anything.

**Comment by saupchurch** [comment]
@david4096 has taken care of this and we have a clean rna topic branch now
