### ISSUE TITLE
Update data prep script for annotations

### ISSUE THREAD

**Issue by david4096** [ga4gh/server#896]
The script for munging the compliance test data needs to be updated to support the variant annotation test data.

**Comment by david4096** [comment]
@dcolligan would you mind taking a look to see if this has been made obsolete by the repo manager?

**Comment by dcolligan** [comment]
This is `scripts/prepare_compliance_data.py`, right?

As of right now, that script seems to do several things that the repo manager does not do.  The repo manager does not modify any bioinformatics files, it just copies them around.  But the script seems to compress files, write headers, index files, etc.

Perhaps we will add these features to the repo manager in the future, but at the moment we can't swap in the repo manager to completely replace the functionality in the script.

**Comment by dcolligan** [comment]
In any event the repo manager will not make this script 'obsolete' ... the script (at some point) will need to import the repo manager library and use its methods to move data from the test-data directory to another directory.

**Comment by david4096** [comment]
Closed by removing the need for JSON sidecar of Variant Annotation sets in server and changing naming structure and adding sequence ontology text to compliance test-data.

https://github.com/david4096/compliance/commit/9cfaffd31e5dffc1de4a5932ed50dfa8c4cdb319
