### ISSUE TITLE
g2p branch needs updating

### ISSUE THREAD

**Issue by jeromekelleher** [ga4gh/server#911]
The g2p branch should be updated by merging from master before the initial code drop. See #882 for example.

**Comment by bwalsh** [comment]
updated from master

**Comment by jeromekelleher** [comment]
Can you make a PR with this update please @bwalsh? We need to have the g2p feature branch in this repo level with master. See #882 for an example of how this works.

**Comment by jeromekelleher** [comment]
Done in #927
