### ISSUE TITLE
Data driven tests pick up hidden files

### ISSUE THREAD

**Issue by david4096** [ga4gh/server#913]
When running test_variants I ran into an issue where it was trying to load some `.DS_Store` files.

To replicate:

    touch tests/data/datasets/dataset1/variants/.DS_Store
    nosetests --nocapture tests.datadriven.test_variants

I found this handy: `find . -name \*.DS_Store -delete`

**Comment by jeromekelleher** [comment]
Well spotted @david4096, I'm looking forward to the fix PR!
