### ISSUE TITLE
Explore using __slots__ for protocol objects

### ISSUE THREAD

**Issue by Naburimannu** [ga4gh/server#92]
Some of our memory burden (observed #10 ) comes from the dict allocated for every object; we can have a quarter million or more objects allocated on the server to answer a single query. Python classes can explicitly declare `__slots__` = [...] with a fixed immutable list of fields to prevent dict allocation.

This might save 15% of the peak memory burden (and perhaps provide speedup due to lack of memory churn?); @pashields points out that only a couple of lines of change in the codegen script will be needed. It would be cleaner, more pythonic, and more amenable to error handling than my previously prototyped ad-hoc string aggregation.

**Comment by Naburimannu** [comment]
Waiting until we have server benchmark and heap memory profiling live to investigate.

**Comment by Naburimannu** [comment]
Short of a formal investigation: https://github.com/Naburimannu/server/commit/8fbf3f526c14c907b5751d57d9a68494b9182376 spends  6.45-7.1 seconds in server_benchmark.py and never measures more than about 350MB on top; without that one patch, server_benchmark.py takes 10+ seconds and measures more than 650MB on top - considerably more savings than I expected.

We should be able to do this in a more principled way by using `__slots__` for all the protocol classes. The drawback is that our users won't be able to attach arbitrary new fields to protocol objects. There may well be a way that lets us cleanly use `__dict__` on the more heavyweight objects, and just switch to `__slots__` for GACalls (which server_benchmark is handling 250,000 of).

The designed way around that inflexibility in Python would be for them to create their own subclasses, which by default get a __dict__ and can be freely extended, but then (1) we have to provide them with some sort of factory access, and (2) when they do drop in a non-slots subclass of GACall they lose all this performance.

**Comment by pashields** [comment]
This seems like a really good idea with big savings, unless I've missed something huge. @Naburimannu I'm moderately familiar with the code if you want a hand with this at any point.

**Comment by jeromekelleher** [comment]
I've no objection to using `__slots__` if it doesn't make things more complicated. It seems like a pretty hefty performance gain, so I'd be very enthusiastic about this change. I don't think it's a huge loss that the protocol classes don't allow arbitrary fields being added - arguably, this is a good thing as it prevents common spelling errors.

**Comment by Naburimannu** [comment]
Note "considerably more savings than I expected" - after fixing a couple of bugs in JSON encoding/decoding (71efce3e946f3c36050adec34c96e638a3ea4807) this is closer to what I originally predicted, with 15-20% space savings and inconsistent time savings. It's also a tiny bit less clean - four unit tests broke because they directly referenced `__dict__`, which no longer exists.
