### ISSUE TITLE
Add confirm step for datarepo commands that destroy data

### ISSUE THREAD

**Issue by jeromekelleher** [ga4gh/server#921]
A potentially useful addition to the semantics of the data repo manager would be to provide a confirmation dialogue when running commands that destroy data. E.g.
```bash
$ python repo_dev.py destroy  testrepo
Are you sure you want delete all data in 'testrepo'? [y|N] 
Repo at 'testrepo'
Destroyed
```

This will stop people from potentially shooting themselves in the foot quite badly (there could be terabytes of data held in the repo directory). For users who know what they are doing, we provide a --force -f option to override it:
```bash
$ python repo_dev.py destroy  -f testrepo
Repo at 'testrepo'
Destroyed
```

**Comment by dcolligan** [comment]
Fixed in #923
