### ISSUE TITLE
G2P needs repo manager interface

### ISSUE THREAD

**Issue by jeromekelleher** [ga4gh/server#937]
There is currently no way to add G2P data to the server using the repo manager CLI. This should be fixed.

Issues:

1. Currently there is one server-wide G2PDataset, which conflicts with the design of the rest of the API and server. Hopefully this will be resolved in the schemas soon. (See https://github.com/ga4gh/schemas/pull/560 and  https://github.com/ga4gh/schemas/pull/432 for discussion on this).

2. We should do some sort of data checking on the way in, and not just blindly copy the files we get. Is it in the format we expect? How do we verify that something is well formed G2P data?

**Comment by dcolligan** [comment]
We need a well-specified data model before we can provide a repo manager interface to it.  I'll start getting my hands dirty with the g2p branch in a bit...

**Comment by jeromekelleher** [comment]
Great news, thanks @dcolligan!

**Comment by bwalsh** [comment]
@dcolligan  thanks very much.  Let me know what help you need:   `well-specified data model`

**Comment by david4096** [comment]
This should help, then the server conventions for adding FPA sets can be done: https://github.com/ga4gh/schemas/pull/563

**Comment by dcolligan** [comment]
This has been addressed.  Closing...
