### ISSUE TITLE
 CORS unit test broken

### ISSUE THREAD

**Issue by Naburimannu** [ga4gh/server#94]
@jeromekelleher @dcolligan : the merge in 6b9ef7e4e seems to have broken @melaniedc 's new CORS unit test? If I check out 399e96 or earlier SHAs, nosetests completes.

I think what's going on here is that we no longer call cors.CORS() for all invocations, but only in frontend.configure(), which is only called when we're entering through server_main().

Does nosetests not execute server_main()?

**Comment by dcolligan** [comment]
I have a fix in a PR... see https://github.com/ga4gh/server/pull/95

**Comment by dcolligan** [comment]
#93 fixes this
