### ISSUE TITLE
Refactor  tests/unit/test_g2p.py

### ISSUE THREAD

**Issue by jeromekelleher** [ga4gh/server#940]
Currently, the tests in  tests/unit/test_g2p.py are a mix of data driven and frontend HTTP tests. These tests should be split out into the data driven tests (which can explicitly depend on the known data) and frontend HTTP tests (which should be put into tests/test_views.py, and follow the patterns in there).

Paging tests should be done in test_simulated_stack.py, following the approach used for ListReferenceBases.

**Comment by david4096** [comment]
This is at least partially fulfilled by the last PR:
Unit tests are [here](https://github.com/ga4gh/server/blob/g2p/tests/unit/test_genotype_phenotype.py) and those tests were moved to [test_views](https://github.com/ga4gh/server/blob/g2p/tests/unit/test_views.py#L121). To really call this done I think there is at least one other unit test to write and the paging tests moved to test_simulated_stack.

**Comment by bwalsh** [comment]
@dcolligan I think these comments have been largely resolved #1345

**Comment by dcolligan** [comment]
Er, maybe @jeromekelleher was talking about `tests/end_to_end/test_g2p.py` ?

**Comment by jeromekelleher** [comment]
Yes, sorry @dcolligan that was a typo. I was talking about ``tests/end_to_end/test_g2p.py``.

**Comment by dcolligan** [comment]
@jeromekelleher has this been resolved to your satisfaction?

**Comment by kozbo** [comment]
@jeromekelleher bump

**Comment by jeromekelleher** [comment]
Thanks yes, looks good.
