### ISSUE TITLE
Refactor ga4gh/datamodel/genotype_phenotype.py required

### ISSUE THREAD

**Issue by jeromekelleher** [ga4gh/server#941]
We need to refactor ga4gh/datamodel/genotype_phenotype.py to 

1) Follow the conventions used elsewhere in the code more closely;  
2) Break the code up into testable chunks; and
3) Make unit tests to test those chunks.

This issue is necessarily a bit vague, but we can discuss the details in the thread if/when particular issues pop up.

**Comment by bwalsh** [comment]
@dcolligan I believe this has been addressed with #953 and subsequent commits

**Comment by dcolligan** [comment]
I'll defer to @jeromekelleher here.  If it's refactored to his satisfaction we can close this.

**Comment by kozbo** [comment]
@jeromekelleher bump

**Comment by jeromekelleher** [comment]
Yes, it's much better now. Closing.
