### ISSUE TITLE
avro.io.validate doesn't check for extra fields

### ISSUE THREAD

**Issue by dcolligan** [ga4gh/server#951]
From discussion in https://github.com/ga4gh/server/issues/942

Avro's validate method does not care about extra fields in the record, it just ignores them:

```
>>> import avro.io
>>> import ga4gh.avrotools as avrotools
>>> import ga4gh.protocol as protocol
>>> creator = avrotools.Creator(protocol.Call)
>>> instance = creator.getTypicalInstance()
>>> jsonDict = instance.toJsonDict()
>>> avro.io.validate(protocol.Call.schema, jsonDict)
True
>>> jsonDict['extra'] = 'extra'
>>> avro.io.validate(protocol.Call.schema, jsonDict)
True
```

Therefore any request that is sent into the server with extra fields will continue as if the request is valid.  Questions:

1) Is this the desired behavior?  (My view: probably not)

2) If not, how do we want to fix this? (One possibility: use avrotools for validation instead)

3) Do we want to fix this? (Possible considerations: imminent switch to protobuf, possible performance issues of using avrotools on every request)

**Comment by diekhans** [comment]
Just wait for protocol buffers.

Python avro validation also doesn't agree with java avro
validation.  Python will accept things that are not valid
in java avro.  Java Avro imposes constraints that are not
considered valid in JSON.

**Comment by jeromekelleher** [comment]
Very much in agreement with @diekhans. A quote from Douglas Adams comes to mind for some reason:

> SIRIUS CYBERNETICS CORPORATION PRODUCTS

> It is very easy to be blinded to the essential uselessness of them by the sense of achievement you get from getting them to work at all
> In other words - and this is the rock solid principle on which the whole of the Corporation's Galaxy-wide success is founded - their fundamental design flaws are completely hidden by their superficial design flaws.

**Comment by jeromekelleher** [comment]
Closing this as a WONTFIX.
