### ISSUE TITLE
Support single FASTA ReferenceSets

### ISSUE THREAD

**Issue by jeromekelleher** [ga4gh/server#955]
We need to support ReferenceSets based on a single FASTA file for CRAM support (see #928). Splitting the references by chromosome seems artificial, and will be messy if there are large numbers of contigs in an alignment (perfectly possible in non-model organisms that don't have a good reference).

This may introduce a backward incompatibility with the data repo format currently supported, so we should look carefully at what the best option is:

1) Only support single FASTA ReferenceSets, and provide a script to update old data repo formats to the new one;
2) Only support single FASTA ReferenceSets, and not worry about existing users (there may not be any not using the example data);
3)  Support both single FASTA ReferenceSets and multi-fasta ReferenceSets.

Any thoughts @dcolligan, @diekhans?

**Comment by dcolligan** [comment]
Hm, do we have any idea of which use case is more common?  Or what the preference of the users might be?

**Comment by diekhans** [comment]
A single fasta is most like the more common approach and it's
easy to create a single fasta from multiple fastas.

For less finished assembles, there can be tens of thousands of
scaffolds, so contig per fasta would be a big problem.

**Comment by macieksmuga** [comment]
#829

**Comment by diekhans** [comment]
what is the ETA on finishing this?

**Comment by macieksmuga** [comment]
I'm putting it on my next week (March 28) sprint schedule

**Comment by jeromekelleher** [comment]
Closed by #1166.
