### ISSUE TITLE
Add hooks into repo manager into variation_annotation branch

### ISSUE THREAD

**Issue by dcolligan** [ga4gh/server#957]

**Comment by dcolligan** [comment]
@david4096 I know we talked about this a bit on the call, but could you specify if there is any functionality you want here, if any?

**Comment by david4096** [comment]
Sorry for not getting back to you sooner on this! I believe the adding of [ontology maps](https://github.com/ga4gh/server/pull/980) and some documentation were what was needed. Variant annotation sets are added by the add-variantset interface since they add both an annotation set and a variant set.

**Comment by david4096** [comment]
https://github.com/ga4gh/server/pull/980

**Comment by dcolligan** [comment]
Closed in #980
