### ISSUE TITLE
Search by name always returns a single result

### ISSUE THREAD

**Issue by david4096** [ga4gh/server#964]
Here is the bit of code that handles readgroupset searching.

```
    def readGroupSetsGenerator(self, request):
        """
        Returns a generator over the (readGroupSet, nextPageToken) pairs
        defined by the specified request.
        """
        dataset = self.getDataRepository().getDataset(request.datasetId)
        if request.name is None:
            return self._topLevelObjectGenerator(
                request, dataset.getNumReadGroupSets(),
                dataset.getReadGroupSetByIndex)
        else:
            try:
                readGroupSet = dataset.getReadGroupSetByName(request.name)
            except exceptions.ReadGroupSetNameNotFoundException:
                return self._noObjectGenerator()
            return self._singleObjectGenerator(readGroupSet)
```

It appears that search by name will always only return a single result. This doesn't seem like intended behavior in the schemas. `Only return read group sets with this name (case-sensitive, exact match).`

Perhaps we can ignore this issue if we consider that we enforce names to be unique because "names" in this case map directly to filenames in a directory? Should search-by-name in the schemas be rewritten as get-by-name?

**Comment by jeromekelleher** [comment]
This is a property of our implementation where a name is a 'local ID' within a particular set. In my opinion the language in the schemas is poor, but there have been many discussion about what names and IDs mean. I think the situation at the moment is that implementations are free to do what they want, so our implementation is correct and I'm going to close this issue.
