### ISSUE TITLE
Call sets always have a single variantSetId

### ISSUE THREAD

**Issue by david4096** [ga4gh/server#966]
From schemas:
```
  /** The IDs of the variant sets this call set has calls in. */
  array<string> variantSetIds = [];
```

In `variants.py`:
```
gaCallSet.variantSetIds = [variantSet.getId()]
```

The schema seems to suggest that given some callset I can find other variant sets that it is a part of, but our implementation always returns a single variant set.

**Comment by jeromekelleher** [comment]
This is a limitation we inherit from VCF files. Closing this issue until we have a reason to support multiple variant sets for a call set.

**Comment by david4096** [comment]
Does this mean the schemas don't make sense around this? Is it possible to have a call set in multiple variant sets outside the scope of the reference server? @diekhans 

https://github.com/ga4gh/schemas/issues/583

**Comment by jeromekelleher** [comment]
This is the subject of long argument @david4096; people feel that it's important that the schema be flexible enough to support this. However, it's not something we support in the reference implementation currently, given our dependence on VCF metadata.

**Comment by diekhans** [comment]
The was the subject of a three month, circular discussion in
github last summer that was never resolved.  Our conclusion was
someone who had deep understanding of the way variant analysis
is done needs review and document the design.  We have not
found anyone to do this.

In the mean time, the schema stands, however the reference
server is allowed to put restrictions on the data it servers
and only one instance of a call set is a restriction that
can be lived with.
