### ISSUE TITLE
Remote files in repo manager

### ISSUE THREAD

**Issue by david4096** [ga4gh/server#970]
I was under the impression that we are able to support remote files. An example of this using the repo manager is needed.

**Comment by david4096** [comment]
Testing support on AWS #335

**Comment by dcolligan** [comment]
We had remote file support in for a while, but then took it out since we determined that the underlying htslib code was too unreliable (it was routinely dumping core on us).  This is in the process of getting resolved, as the thread you linked indicates -- Jerome is heading up that effort.

**Comment by david4096** [comment]
We're going to need this feature even though we're still testing this feature. I'm going to leave it open.

**Comment by dcolligan** [comment]
Ok, I took out the remote capabilities here: 17ba04600f048d897a33492c4f651f52b4e2dead

**Comment by diekhans** [comment]
Do we have a htslib ticket URL for the remote access problems?

**Comment by dcolligan** [comment]
They've resolved the issue in the latest branch; Jerome is working it out in the linked AWS ticket

**Comment by jeromekelleher** [comment]
Closed by #1166.
