### ISSUE TITLE
Replace prepare_compliance_data with repo manager

### ISSUE THREAD

**Issue by david4096** [ga4gh/server#978]
The functionality of the prepare compliance data script is more or less covered by the repo manager. We could do away with that script, or at least simplify it to be a series of calls to the repo manager. It could then be a bash script.

**Comment by diekhans** [comment]
Good idea; although please leave it as a python program, as I
don't think we have any bash.  Writing bash is easy, writing
robust bash isn't a common skill.

**Comment by david4096** [comment]
This should be done as part of the move to the SQL registry.

**Comment by david4096** [comment]
Closed with this commit: 
https://github.com/ga4gh/server/pull/1189/files#diff-0daf61941b83c615dfe385b45d7fdd2d
