### ISSUE TITLE
provide for basic logging of gets and puts made against the reference server

### ISSUE THREAD

**Issue by kozbo** [ga4gh/server#979]
Once the server is deployed we will want to know the history of access on the server:
1. Will be very helpful for understanding the context of any problems that come up
2. Will be nice to build some metrics for how much the server is being used

Format of message should include at least the following:
- time and date stamp
- client information (IP? what else do we know here?)
- get or put message along with parameters

**Comment by diekhans** [comment]
Apache already has the ability to log request URLs.   You need to use mod_dumpio to log post date.  The logging is highly configurable and lots of tools to parse the files.

If it proves desirable to implement logging withing the server, it should have the option to log to syslog.
This is supported by the python logger.  I have code I could donate to handling configuration from the command line.

**Comment by jeromekelleher** [comment]
Agreed with @diekhans --- the recommended deployment option is through Apache. We should either verify that Apache supplies the required information (which I think by default it probably provides most stuff we'd want) and close this issue or update with more specific requirements so we can update.

**Comment by kozbo** [comment]
I have done some testing with the default logging levels specified in the ga4gh installation instructions and found that the /var/log/appache2/access.log file has an adequate amount of logging.  After running the demo.py program I got the following output in the log 
<
128.114.59.148 - - [24/Mar/2016:23:48:39 +0000] "POST /ga4gh/datasets/search HTTP/1.1" 200 310 "-" "python-requests/2.7.0 CPython/2.7.10 Darwin/15.3.0"
128.114.59.148 - - [24/Mar/2016:23:48:39 +0000] "POST /ga4gh/variantsets/search HTTP/1.1" 200 6807 "-" "python-requests/2.7.0 CPython/2.7.10 Darwin/15.3.0"
128.114.59.148 - - [24/Mar/2016:23:48:39 +0000] "POST /ga4gh/variants/search HTTP/1.1" 200 29990 "-" "python-requests/2.7.0 CPython/2.7.10 Darwin/15.3.0"
>
We have the requestors IP, the time stamp and the request information. This should be fine until we know what other information we need, and possibly all that we will ever need.  Will close this.
