### ISSUE TITLE
reversing filter order changes number of results from searchVariantAnnnotations

### ISSUE THREAD

**Issue by reece** [ga4gh/server#981]
The behavior of [searchVariantAnnotations](https://ga4gh-schemas.readthedocs.org/en/latest/schemas/alleleAnnotationmethods.html#searchVariantAnnotations) is unclear to me, especially when multiple effect filters are described.

While investigating this question, I noticed that the number of results returned changed depending on the filter order.

The two obvious behavior options with multiple effects are conjunction (AND) and inclusive disjunction (OR) of the effect criteria. Since both options commutative, reversing the order of the filter should not matter.

In fact, it appears that the server is using only the first effect term.

See https://gist.github.com/reece/9db77d7f43af7c4fb8fc for demonstration code.

**Comment by david4096** [comment]
Thanks Reece, looking into it!
