### ISSUE TITLE
gff3 parser improvements

### ISSUE THREAD

**Issue by david4096** [ga4gh/server#988]
The GFF3 parser maxes out my system's memory pretty quickly. It should be possible to simplify the parser to match the shape of our database without reading it entirely into memory.

**Comment by diekhans** [comment]
There is no requirement for order on GFF3 rows, however for many GFF3, such as GENCODE, they are 
grouped by gene (top level).  While we still have to support the read the whole thing into memory, however we can add an option to do this.

@diekhans contributed the GFF3 parser and will provide this option.

**Comment by macieksmuga** [comment]
I've made some modifications to the gff3->db ingestion script in the latest sequence-annotations PR update #1036 that should considerably ease the pain.

**Comment by kozbo** [comment]
This issue is now covered by #1080 so closing it.
