### ISSUE TITLE
Extra spaces in _protocol_definitions.py docstrings

### ISSUE THREAD

**Issue by dcolligan** [ga4gh/server#993]
E.g. for the `Call` doc:

In `alleleAnnotations.avdl`:
```
over the parent `VariantSet` is guaranteed to match the ordering
```

Turns into:
```
to match   the ordering...
```
Somewhere `process_schemas.py` is inserting extra spaces.

Low priority.

**Comment by macieksmuga** [comment]
The records and their documentation are over-indented in the affected schema files, causing spurious spaces to appear in automatic documentation. We could re-indent the affected files (in the schema repo) or just fix the `process_schemas.py` script in the reference server  to remove these spurious spaces while parsing the docs.

**Comment by diekhans** [comment]
or ignore the problem until we get the protocol buffer framework
and see if the problem still exists.

**Comment by jeromekelleher** [comment]
Yeah, let's shelve this one. This will be completely new code when we use protobuf.
